// src/config/languages.js

export const translations = {
  english: {
    ourApproachBadge: "Our Approach",
    whyWeBuiltTitle: "Why we built",
    whyWeBuiltHighlight: "Sakshar",
    approachSubtitle: "Four beliefs that shape every lesson, every prompt and every line of feedback on the platform.",
    literacyGapTitle: "The literacy gap is human",
    literacyGapBody: "Millions of adults speak fluently but were never taught to read or write with confidence. That's not a technology problem to route around — it's a human one to design for, with patience and dignity.",
    oneSizeFitsTitle: "One size fits no one",
    oneSizeFitsBody: "Traditional classes assume a starting point. Sakshar begins with a short assessment and shapes a path that adapts to the learner's own pace, language and level.",
    aiListensTitle: "AI that listens back",
    aiListensBody: "Real-time pronunciation feedback, character tracing and applied reasoning turn passive lessons into a two-way conversation — patient, private and always available.",
    fluencyMotherTitle: "Fluency in the mother tongue",
    fluencyMotherBody: "Learning lands deepest in the language you dream in. Sakshar teaches across 20+ Indian regional languages, detecting your voice from the very first tap.",
    thePlatformBadge: "The Platform",
    platformTitle: "A classroom that adapts to every learner",
    platformSubtitle: "Three intelligent modules work together to build reading, writing and speaking — one confident step at a time.",
    mod1Tag: "01 / READING",
    mod1Title: "Interactive Reading",
    mod1Desc: "Custom content decks built around daily local tasks, with tap-to-explain glossaries for unfamiliar words.",
    mod2Tag: "02 / WRITING",
    mod2Title: "Real-Time Tracing",
    mod2Desc: "Trace characters on screen and get stroke-by-stroke correction — try it above in the live sandbox.",
    mod3Tag: "03 / SPEAKING",
    mod3Title: "Voice Verification",
    mod3Desc: "Speak aloud and hear how close you are — private, patient pronunciation feedback powered by AI.",
    stat1Label: "Regional Languages",
    stat2Label: "Pronunciation Accuracy",
    stat3Label: "Learners Onboarded",
    stat4Label: "Literacy Modules",
    aiCompanionBadge: "The AI Literacy Companion",
    voiceDetectorLabel: "AI Voice Language Selector",
    listening: "Listening…",
    voiceListeningPrompt: "Speak now in your mother tongue…",
    detectedLabel: "Detected",
    tryLiveDemo: "Try Live Demo",
    voiceAiLabel: "Voice AI",
    tracingLabel: "Tracing",
    scrollLabel: "Scroll",
    micBtnTooltip: "Click and speak your language!",
    secReading: "Reading",
    secWriting: "Writing",
    secSpeaking: "Speaking",
    secReasoning: "Reasoning",
    langHindi: "Hindi",
    langTamil: "Tamil",
    langBengali: "Bengali",
    ourApproachBadge: "Our Approach",
    whyWeBuiltTitle: "Why we built",
    whyWeBuiltHighlight: "Sakshar",
    approachSubtitle: "Four beliefs that shape every lesson, every prompt and every line of feedback on the platform.",
    literacyGapTitle: "The literacy gap is human",
    literacyGapBody: "Millions of adults speak fluently but were never taught to read or write with confidence. That's not a technology problem — it's a human one to design for, with patience and dignity.",
    oneSizeFitsTitle: "One size fits no one",
    oneSizeFitsBody: "Traditional classes assume a starting point. Sakshar begins with a short assessment and shapes a path that adapts to the learner's own pace, language and level.",
    aiListensTitle: "AI that listens back",
    aiListensBody: "Real-time pronunciation feedback, character tracing and applied reasoning turn passive lessons into a two-way conversation — patient, private and always available.",
    fluencyMotherTitle: "Fluency in the mother tongue",
    fluencyMotherBody: "Learning lands deepest in the language you dream in. Sakshar teaches across 20+ Indian regional languages, detecting your voice from the very first tap.",
    thePlatformBadge: "The Platform",
    platformTitle: "A classroom that adapts to every learner",
    platformSubtitle: "Three intelligent modules work together to build reading, writing and speaking — one confident step at a time.",
    mod1Tag: "01 / READING",
    mod1Title: "Interactive Reading",
    mod1Desc: "Custom content decks built around daily local tasks, with tap-to-explain glossaries for unfamiliar words.",
    mod2Tag: "02 / WRITING",
    mod2Title: "Real-Time Tracing",
    mod2Desc: "Trace characters on screen and get stroke-by-stroke correction — try it above in the live sandbox.",
    mod3Tag: "03 / SPEAKING",
    mod3Title: "Voice Verification",
    mod3Desc: "Speak aloud and hear how close you are — private, patient pronunciation feedback powered by AI.",
    stat1Label: "Regional Languages",
    stat2Label: "Pronunciation Accuracy",
    stat3Label: "Learners Onboarded",
    stat4Label: "Literacy Modules",
    beginYourJourney: "Begin Your Journey",
    ctaHeadlineLine1: "Every word you learn",
    ctaHeadlineLine2: "opens a door.",
    getStartedFree: "Get Started Free",
    watchDemo: "Watch the Demo",
    home: "Home", signIn: "Sign In", createAccount: "Create Account", welcomeBack: "Welcome back",
    signInSub: "Sign in to continue your learning journey.", email: "✉️ Email Address", password: "🔒 Password", fullName: "👤 Full Name", or: "or",
    googleSignIn: "Continue with Google", newHere: "New here?", alreadyHaveAccount: "Already have an account?", landingTitle: "Empowering Literacy Through AI Intelligence",
    landingTitleLine1: "Empowering Literacy", landingTitleLine2: "Through AI Intelligence",
    aiConvertedMsg: "AI converted in selected language",
    landingSub: "A personalized learning companion designed to help adults and first-generation learners acquire foundational reading, writing, and speaking skills in regional languages.",
    getStarted: "Get Started", registerTitle: "Create your account", registerSub: "Join our community and expand your learning horizons.",
    languageLabel: "🌐 Preferred Native Language",
    wantToLearnLabel: "🎯 Language You Want to Learn",
    registerLeftTitle: "Your journey to literacy starts here.",
    registerLeftSub: "Create a profile to unlock voice practice assessments, real-time feedback, and adaptive daily reading lessons.",
    loginLeftTitle: "Every word you learn opens a new door.", loginLeftSub: "Personalized reading, writing, and speaking practice — in your own language, at your own pace.",
    dashboardTitle: "Welcome to Your Dashboard!", logout: "Log Out"
  },
  hindi: {
    ourApproachBadge: "हमारा दृष्टिकोण",
    whyWeBuiltTitle: "हमने क्यों बनाया",
    whyWeBuiltHighlight: "साक्षर",
    approachSubtitle: "चार विश्वास जो मंच पर हर पाठ, हर प्रॉम्प्ट और हर प्रतिक्रिया को आकार देते हैं।",
    literacyGapTitle: "साक्षरता का अंतर मानवीय है",
    literacyGapBody: "लाखों वयस्क धाराप्रवाह बोलते हैं लेकिन उन्हें कभी आत्मविश्वास से पढ़ना या लिखना नहीं सिखाया गया। यह कोई तकनीक की समस्या नहीं है — यह धैर्य और गरिमा के साथ डिज़ाइन की जाने वाली एक मानवीय समस्या है।",
    oneSizeFitsTitle: "एक आकार सभी के लिए उपयुक्त नहीं होता",
    oneSizeFitsBody: "पारंपरिक कक्षाएं एक ही शुरुआती बिंदु मानती हैं। साक्षर एक संक्षिप्त मूल्यांकन से शुरू होता है और शिक्षार्थी की गति, भाषा और स्तर के अनुकूल मार्ग तैयार करता है।",
    aiListensTitle: "एआई जो वापस सुनता है",
    aiListensBody: "वास्तविक समय का उच्चारण फीडबैक और अक्षर ट्रेसिंग निष्क्रिय पाठों को दो-तरफा बातचीत में बदल देते हैं — धैर्यवान, निजी और हमेशा उपलब्ध।",
    fluencyMotherTitle: "मातृभाषा में धाराप्रवाहता",
    fluencyMotherBody: "सीखना उसी भाषा में सबसे गहरा होता है जिसमें आप सपने देखते हैं। साक्षर 20+ भारतीय क्षेत्रीय भाषाओं में सिखाता है, आपके पहले टैप से ही आपकी आवाज पहचानता है।",
    thePlatformBadge: "मंच",
    platformTitle: "एक कक्षा जो हर शिक्षार्थी के अनुकूल बनती है",
    platformSubtitle: "तीन बुद्धिमान मॉड्यूल पढ़ने, लिखने और बोलने के कौशल का निर्माण करने के लिए एक साथ काम करते हैं।",
    mod1Tag: "01 / पठन",
    mod1Title: "इंटरएक्टिव पठन",
    mod1Desc: "दैनिक स्थानीय कार्यों के आसपास निर्मित कस्टम सामग्री डेक, अपरिचित शब्दों के लिए शब्दावली के साथ।",
    mod2Tag: "02 / लेखन",
    mod2Title: "रियल-टाइम ट्रेसिंग",
    mod2Desc: "स्क्रीन पर अक्षरों को ट्रेस करें और स्ट्रोक-दर-स्ट्रोक सुधार प्राप्त करें।",
    mod3Tag: "03 / संभाषण",
    mod3Title: "आवाज सत्यापन",
    mod3Desc: "जोर से बोलें और सुनें कि आप कितने सटीक हैं — एआई द्वारा संचालित निजी, धैर्यवान उच्चारण फीडबैक।",
    stat1Label: "क्षेत्रीय भाषाएं",
    stat2Label: "उच्चारण सटीकता",
    stat3Label: "शिक्षार्थी शामिल हुए",
    stat4Label: "साक्षरता मॉड्यूल",
    aiCompanionBadge: "एआई साक्षरता साथी",
    voiceDetectorLabel: "एआई वॉयस भाषा चयनकर्ता",
    listening: "सुन रहा है…",
    voiceListeningPrompt: "अपनी मातृभाषा में बोलें…",
    detectedLabel: "पहचाना गया",
    tryLiveDemo: "लाइव डेमो आज़माएं",
    voiceAiLabel: "वॉयस एआई",
    tracingLabel: "ट्रेसिंग",
    scrollLabel: "नीचे स्क्रॉल करें",
    micBtnTooltip: "माइक पर क्लिक करें और बोलें!",
    secReading: "पठन",
    secWriting: "लेखन",
    secSpeaking: "संभाषण",
    secReasoning: "तर्क",
    langHindi: "हिन्दी",
    langTamil: "तमिल",
    langBengali: "बांग्ला",
    ourApproachBadge: "हमारा दृष्टिकोण",
    whyWeBuiltTitle: "हमने क्यों बनाया",
    whyWeBuiltHighlight: "साक्षर",
    approachSubtitle: "चार विश्वास जो मंच पर हर पाठ, हर प्रॉम्प्ट और हर प्रतिक्रिया को आकार देते हैं।",
    literacyGapTitle: "साक्षरता का अंतर मानवीय है",
    literacyGapBody: "लाखों वयस्क धाराप्रवाह बोलते हैं लेकिन उन्हें कभी आत्मविश्वास से पढ़ना या लिखना नहीं सिखाया गया। यह कोई तकनीक की समस्या नहीं है — यह धैर्य और गरिमा के साथ डिज़ाइन की जाने वाली एक मानवीय समस्या है।",
    oneSizeFitsTitle: "एक आकार सभी के लिए उपयुक्त नहीं होता",
    oneSizeFitsBody: "पारंपरिक कक्षाएं एक ही शुरुआती बिंदु मानती हैं। साक्षर एक संक्षिप्त मूल्यांकन से शुरू होता है और शिक्षार्थी की गति, भाषा और स्तर के अनुकूल मार्ग तैयार करता है।",
    aiListensTitle: "एआई जो वापस सुनता है",
    aiListensBody: "वास्तविक समय का उच्चारण फीडबैक और अक्षर ट्रेसिंग निष्क्रिय पाठों को दो-तरफा बातचीत में बदल देते हैं — धैर्यवान, निजी और हमेशा उपलब्ध।",
    fluencyMotherTitle: "मातृभाषा में धाराप्रवाहता",
    fluencyMotherBody: "सीखना उसी भाषा में सबसे गहरा होता है जिसमें आप सपने देखते हैं। साक्षर 20+ भारतीय क्षेत्रीय भाषाओं में सिखाता है, आपके पहले टैप से ही आपकी आवाज पहचानता है।",
    thePlatformBadge: "मंच",
    platformTitle: "एक कक्षा जो हर शिक्षार्थी के अनुकूल बनती है",
    platformSubtitle: "तीन बुद्धिमान मॉड्यूल पढ़ने, लिखने और बोलने के कौशल का निर्माण करने के लिए एक साथ काम करते हैं।",
    mod1Tag: "01 / पठन",
    mod1Title: "इंटरएक्टिव पठन",
    mod1Desc: "दैनिक स्थानीय कार्यों के आसपास निर्मित कस्टम सामग्री डेक, अपरिचित शब्दों के लिए टैप-टू-एक्सप्लेन शब्दावली के साथ।",
    mod2Tag: "02 / लेखन",
    mod2Title: "रियल-टाइम ट्रेसिंग",
    mod2Desc: "स्क्रीन पर अक्षरों को ट्रेस करें और स्ट्रोक-दर-स्ट्रोक सुधार प्राप्त करें।",
    mod3Tag: "03 / संभाषण",
    mod3Title: "आवाज सत्यापन",
    mod3Desc: "जोर से बोलें और सुनें कि आप कितने सटीक हैं — एआई द्वारा संचालित निजी, धैर्यवान उच्चारण फीडबैक।",
    stat1Label: "क्षेत्रीय भाषाएं",
    stat2Label: "उच्चारण सटीकता",
    stat3Label: "शिक्षार्थी शामिल हुए",
    stat4Label: "साक्षरता मॉड्यूल",
    beginYourJourney: "अपनी यात्रा शुरू करें",
    ctaHeadlineLine1: "आपके द्वारा सीखा गया हर शब्द",
    ctaHeadlineLine2: "एक नया दरवाजा खोलता है।",
    getStartedFree: "मुफ्त में शुरू करें",
    watchDemo: "डेमो देखें",
    home: "होम", signIn: "साइन इन करें", createAccount: "खाता बनाएं", welcomeBack: "आपका स्वागत है",
    signInSub: "अपनी सीखने की यात्रा जारी रखने के लिए साइन इन करें।", email: "✉️ ईमेल पता", password: "🔒 पासवर्ड", fullName: "👤 पूरा नाम", or: "या",
    googleSignIn: "गूगल के साथ जारी रखें", newHere: "यहाँ नए हैं?", alreadyHaveAccount: "पहले से ही एक खाता है?", landingTitle: "एआई बुद्धिमत्ता द्वारा साक्षरता का सशक्तिकरण",
    landingTitleLine1: "साक्षरता का सशक्तिकरण", landingTitleLine2: "एआई बुद्धिमत्ता द्वारा",
    aiConvertedMsg: "एआई चयनित भाषा में परिवर्तित हुआ",
    landingSub: "एक व्यक्तिगत शिक्षण साथी जो वयस्कों और पहली पीढ़ी के शिक्षार्थियों को क्षेत्रीय भाषाओं में बुनियादी पढ़ने, लिखने और बोलने के कौशल हासिल करने में मदद करने के लिए डिज़ाइन किया गया है।",
    getStarted: "शुरू करें", registerTitle: "अपना खाता बनाएं", registerSub: "हमारे समुदाय में शामिल हों और अपने सीखने के क्षितिज का विस्तार करें।",
    languageLabel: "🌐 पसंदीदा मातृभाषा",
    wantToLearnLabel: "🎯 भाषा जो आप सीखना चाहते हैं",
    registerLeftTitle: "आपकी साक्षरता की यात्रा यहीं से शुरू होती है।",
    registerLeftSub: "आवाज अभ्यास आकलन, वास्तविक समय प्रतिक्रिया, और अनुकूली दैनिक पढ़ने के पाठों को अनलॉक करने के लिए एक प्रोफ़ाइल बनाएं।",
    loginLeftTitle: "आपके द्वारा सीखा गया हर शब्द एक नया दरवाजा खोलता है।", loginLeftSub: "व्यक्तिगत पढ़ने, लिखने और बोलने का अभ्यास — आपकी अपनी भाषा में, आपकी अपनी गति से।",
    dashboardTitle: "आपके डैशबोर्ड में आपका स्वागत है!", logout: "लॉग आउट"
  },
  telugu: {
    ourApproachBadge: "మా విధానం",
    whyWeBuiltTitle: "మేము ఎందుకు నిర్మించాము",
    whyWeBuiltHighlight: "సాక్షర్",
    approachSubtitle: "ప్లాట్‌ఫారమ్‌లోని ప్రతి పాఠం, ప్రతి ప్రాంప్ట్ మరియు ప్రతి అభిప్రాయాన్ని రూపొందించే నాలుగు నమ్మకాలు.",
    literacyGapTitle: "అక్షరాస్యత అంతరం మానవీయమైనది",
    literacyGapBody: "లక్షలాది మంది పెద్దలు అనర్గళంగా మాట్లాడతారు కానీ చదవడం లేదా రాయడం ఎప్పుడూ నేర్పించబడలేదు. ఇది సాంకేతిక సమస్య కాదు — ఓర్పు మరియు గౌరవంతో రూపొందించాల్సిన మానవ సమస్య.",
    oneSizeFitsTitle: "ఒకే పరిమాణం అందరికీ సరిపోదు",
    oneSizeFitsBody: "సాంప్రదాయ తరగతులు ప్రారంభ బిందువును ఊహిస్తాయి. సాక్షర్ చిన్న అసెస్‌మెంట్‌తో ప్రారంభమై అభ్యాసకుడి స్వంత వేగం, భాష మరియు స్థాయికి అనుగుణంగా మార్గాన్ని రూపొందిస్తుంది.",
    aiListensTitle: "తిరిగి వినే AI",
    aiListensBody: "రియల్ టైమ్ ఉచ్చారణ ఫీడ్‌బ్యాక్ మరియు క్యారెక్టర్ ట్రేసింగ్ నిష్క్రియాత్మక పాఠాలను ద్విమార్గ సంభాషణగా మారుస్తాయి — ఓపికగా, ప్రైవేట్‌గా మరియు ఎల్లప్పుడూ లభిస్తాయి.",
    fluencyMotherTitle: "మాతృభాషలో నైపుణ్యం",
    fluencyMotherBody: "మీరు కలలు కనే భాషలోనే నేర్చుకోవడం లోతుగా ఉంటుంది. సాక్షర్ 20+ భారతీయ ప్రాంతీయ భాషలలో బోధిస్తుంది, మొదటి ట్యాప్ నుండే మీ స్వరాన్ని గుర్తిస్తుంది.",
    thePlatformBadge: "ప్లాట్‌ఫారమ్",
    platformTitle: "ప్రతి అభ్యాసకుడికి అనుగుణంగా మారే తరగతి గది",
    platformSubtitle: "మూడు తెలివైన మాడ్యూల్స్ కలిసి చదవడం, రాయడం మరియు మాట్లాడటాన్ని నిర్మించడానికి కలిసి పనిచేస్తాయి.",
    mod1Tag: "01 / చదవడం",
    mod1Title: "ఇంటరాక్టివ్ పఠనం",
    mod1Desc: "రోజువారీ స్థానిక పనుల చుట్టూ నిర్మించిన కస్టమ్ కంటెంట్ డెక్‌లు.",
    mod2Tag: "02 / రాయడం",
    mod2Title: "రియల్ టైమ్ ట్రేసింగ్",
    mod2Desc: "స్క్రీన్‌పై అక్షరాలను ట్రేస్ చేయండి మరియు స్ట్రోక్-బై-స్ట్రోక్ దిద్దుబాటు పొందండి.",
    mod3Tag: "03 / మాట్లాడటం",
    mod3Title: "వాయిస్ పరిశీలన",
    mod3Desc: "గట్టిగా మాట్లాడండి మరియు మీ ఉచ్చారణ ఖచ్చితత్వాన్ని వినండి.",
    stat1Label: "ప్రాంతీయ భాషలు",
    stat2Label: "ఉచ్చారణ ఖచ్చితత్వం",
    stat3Label: "అభ్యాసకులు చేరారు",
    stat4Label: "సాక్షరతా మాడ్యూల్స్",
    aiCompanionBadge: "AI అక్షరాస్యత సహచరుడు",
    voiceDetectorLabel: "AI వాయిస్ భాషా ఎంపిక",
    listening: "వింటోంది…",
    voiceListeningPrompt: "మీ మాతృభాషలో మాట్లాడండి…",
    detectedLabel: "గుర్తించబడింది",
    tryLiveDemo: "లైవ్ డెమో ప్రయత్నించండి",
    voiceAiLabel: "వాయిస్ AI",
    tracingLabel: "ట్రేసింగ్",
    scrollLabel: "స్క్రోల్ చేయండి",
    micBtnTooltip: "మైక్ క్లిక్ చేసి మాట్లాడండి!",
    secReading: "చదవడం",
    secWriting: "రాయడం",
    secSpeaking: "మాట్లాడటం",
    secReasoning: "ఆలోచన",
    langHindi: "హిందీ",
    langTamil: "తమిళ్",
    langBengali: "బెంగాలీ",
    ourApproachBadge: "మా విధానం",
    whyWeBuiltTitle: "మేము ఎందుకు నిర్మించాము",
    whyWeBuiltHighlight: "సాక్షర్",
    approachSubtitle: "ప్లాట్‌ఫారమ్‌లోని ప్రతి పాఠం, ప్రతి ప్రాంప్ట్ మరియు ప్రతి అభిప్రాయాన్ని రూపొందించే నాలుగు నమ్మకాలు.",
    literacyGapTitle: "అక్షరాస్యత అంతరం మానవీయమైనది",
    literacyGapBody: "లక్షలాది మంది పెద్దలు అనర్గళంగా మాట్లాడతారు కానీ చదవడం లేదా రాయడం ఎప్పుడూ నేర్పించబడలేదు. ఇది సాంకేతిక సమస్య కాదు — ఓర్పు మరియు గౌరవంతో రూపొందించాల్సిన మానవ సమస్య.",
    oneSizeFitsTitle: "ఒకే పరిమాణం అందరికీ సరిపోదు",
    oneSizeFitsBody: "సాంప్రదాయ తరగతులు ప్రారంభ బిందువును ఊహిస్తాయి. సాక్షర్ చిన్న అసెస్‌మెంట్‌తో ప్రారంభమై అభ్యాసకుడి స్వంత వేగం, భాష మరియు స్థాయికి అనుగుణంగా మార్గాన్ని రూపొందిస్తుంది.",
    aiListensTitle: "తిరిగి వినే AI",
    aiListensBody: "రియల్ టైమ్ ఉచ్చారణ ఫీడ్‌బ్యాక్ మరియు క్యారెక్టర్ ట్రేసింగ్ నిష్క్రియాత్మక పాఠాలను ద్విమార్గ సంభాషణగా మారుస్తాయి — ఓపికగా, ప్రైవేట్‌గా మరియు ఎల్లప్పుడూ లభిస్తాయి.",
    fluencyMotherTitle: "మాతృభాషలో నైపుణ్యం",
    fluencyMotherBody: "మీరు కలలు కనే భాషలోనే నేర్చుకోవడం లోతుగా ఉంటుంది. సాక్షర్ 20+ భారతీయ ప్రాంతీయ భాషలలో బోధిస్తుంది, మొదటి ట్యాప్ నుండే మీ స్వరాన్ని గుర్తిస్తుంది.",
    thePlatformBadge: "ప్లాట్‌ఫారమ్",
    platformTitle: "ప్రతి అభ్యాసకుడికి అనుగుణంగా మారే తరగతి గది",
    platformSubtitle: "మూడు తెలివైన మాడ్యూల్స్ కలిసి చదవడం, రాయడం మరియు మాట్లాడటాన్ని నిర్మించడానికి కలిసి పనిచేస్తాయి.",
    mod1Tag: "01 / చదవడం",
    mod1Title: "ఇంటరాక్టివ్ పఠనం",
    mod1Desc: "రోజువారీ స్థానిక పనుల చుట్టూ నిర్మించిన కస్టమ్ కంటెంట్ డెక్‌లు.",
    mod2Tag: "02 / రాయడం",
    mod2Title: "రియల్ టైమ్ ట్రేసింగ్",
    mod2Desc: "స్క్రీన్‌పై అక్షరాలను ట్రేస్ చేయండి మరియు స్ట్రోక్-బై-స్ట్రోక్ దిద్దుబాటు పొందండి.",
    mod3Tag: "03 / మాట్లాడటం",
    mod3Title: "వాయిస్ పరిశీలన",
    mod3Desc: "గట్టిగా మాట్లాడండి మరియు మీరు ఎంత దగ్గరగా ఉన్నారో వినండి — ప్రైవేట్, రోగి ఉచ్చారణ అభిప్రాయం.",
    stat1Label: "ప్రాంతీయ భాషలు",
    stat2Label: "ఉచ్చారణ ఖచ్చితత్వం",
    stat3Label: "అభ్యాసకులు చేరారు",
    stat4Label: "సాక్షరతా మాడ్యూల్స్",
    beginYourJourney: "మీ ప్రయాణాన్ని ప్రారంభించండి",
    ctaHeadlineLine1: "మీరు నేర్చుకునే ప్రతి పదం",
    ctaHeadlineLine2: "ఒక కొత్త తలుపును తెరుస్తుంది.",
    getStartedFree: "ఉచితంగా ప్రారంభించండి",
    watchDemo: "డెమో చూడండి",
    home: "హోమ్", signIn: "సైన్ ఇన్ చేయండి", createAccount: "ఖాతాను సృష్టించండి", welcomeBack: "తిరిగి સ્વાगतम",
    signInSub: "మీ అభ్యాస ప్రయాణాన్ని కొనసాగించడానికి సైన్ ఇన్ చేయండి.", email: "✉️ ఇమెయిల్ చిరునామా", password: "🔒 పాస్‌వర్డ్", fullName: "👤 పూర్తి పేరు", or: "లేదా",
    googleSignIn: "గూగుల్‌తో కొనసాగండి", newHere: "ఇక్కడ కొత్తవారా?", alreadyHaveAccount: "ఇప్పటికే खाता ఉందా?", landingTitle: "AI ద్వారా అక్షరాస్యత సాధికారత",
    landingTitleLine1: "అక్షరాస్యత సాధికారత", landingTitleLine2: "AI మేధస్సు ద్వారా",
    landingSub: "ప్రాంతీయ భాషలలో ప్రాథమిక పఠనం, రాయడం మరియు మాట్లాడే నైపుణ్యాలను పొందడంలో పెద్దలు మరియు మొదటి తരം అభ్యాసకులకు సహాయపడటానికి రూపొందించబడిన వ్యక్తిగతీకరించిన అభ్యాస సహచరుడు.",
    getStarted: "ప్రారంభించండి", registerTitle: "మీ ఖాతాన్ని సృష్టించండి", registerSub: "మా సంఘంలో చేరండి మరియు మీ అభ్యాస పరిధులను విస్తృతం చేసుకోండి.",
    languageLabel: "🌐 ఇష్టపడే మాతృభాష", registerLeftTitle: "మీ అక్షరాస్యత ప్రయాణం ఇక్కడే ప్రారంభమవుతుంది.",
    registerLeftSub: "వాయిస్ ప్రాక్టీస్ అసెస్‌మెంట్‌లు, రియల్ టైమ్ ఫీడ్‌బ్యాక్ మరియు అదాప్టివ్ రోజువారీ పఠన పాఠాలను అన్‌లాక့် చేయడానికి ప్రొఫైల్‌ను సృష్టించండి.",
    loginLeftTitle: "మీరు నేర్చుకునే ప్రతి పదం ఒక కొత్త తలుపును తెరుస్తుంది.", loginLeftSub: "వ్యक्तिগত పఠనం, రాయడం మరియు మాట్లాడటం ప్రాక్టీस — మీ స్వంత భాషలో, మీ స్వంత వేగంతో.",
    dashboardTitle: "మీ డాష్‌బోర్డుకు స్వాगతం!", logout: "లాగ్ అవుట్"
  },
  punjabi: {
    ourApproachBadge: "ਸਾਡਾ ਪਹੁੰਚ",
    whyWeBuiltTitle: "ਅਸੀਂ ਕਿਉਂ ਬਣਾਇਆ",
    whyWeBuiltHighlight: "ਸਾਖਰ",
    approachSubtitle: "ਚਾਰ ਵਿਸ਼ਵਾਸ ਜੋ ਪਲੇਟਫਾਰਮ 'ਤੇ ਹਰ ਪਾਠ ਅਤੇ ਪ੍ਰਤੀਕਿਰਿਆ ਨੂੰ ਆਕਾਰ ਦਿੰਦੇ ਹਨ।",
    literacyGapTitle: "ਸਾਖਰਤਾ ਦਾ ਅੰਤਰ ਮਾਨਵੀ ਹੈ",
    literacyGapBody: "ਲਾੱਖਾਂ ਬਾਲਗ ਰਵਾਨਗੀ ਨਾਲ ਬੋਲਦੇ ਹਨ ਪਰ ਉਹਨਾਂ ਨੂੰ ਕਦੇ ਵਿਸ਼ਵਾਸ ਨਾਲ ਪੜ੍ਹਨਾ ਜਾਂ ਲਿਖਣਾ ਨਹੀਂ ਸਿਖਾਇਆ ਗਿਆ। ਇਹ ਤਕਨਾਲੋਜੀ ਦੀ ਸਮੱਸਿਆ ਨਹੀਂ ਹੈ — ਇਹ ਸਬਰ ਅਤੇ ਸਤਿਕਾਰ ਨਾਲ ਡਿਜ਼ਾਈਨ ਕਰਨ ਦੀ ਮਾਨਵੀ ਸਮੱਸਿਆ ਹੈ।",
    oneSizeFitsTitle: "ਇੱਕ ਨਾਪ ਸਭ ਲਈ ਢੁਕਵਾਂ ਨਹੀਂ",
    oneSizeFitsBody: "ਸਾਖਰ ਇੱਕ ਛੋਟੇ ਮੁਲਾਂਕਣ ਨਾਲ ਸ਼ੁਰੂ ਹੁੰਦਾ ਹੈ ਅਤੇ ਸਿੱਖਣ ਵਾਲੇ ਦੀ ਆਪਣੀ ਗਤੀ, ਭਾਸ਼ਾ ਅਤੇ ਪੱਧਰ ਦੇ ਅਨੁਕੂਲ ਰਸਤਾ ਬਣਾਉਂਦਾ ਹੈ।",
    aiListensTitle: "AI ਜੋ ਵਾਪਸ ਸੁਣਦਾ ਹੈ",
    aiListensBody: "ਰੀਅਲ-ਟਾਈਮ ਉਚਾਰਨ ਫੀਡਬੈਕ ਅਤੇ ਅੱਖਰ ਟ੍ਰੇਸਿੰਗ ਪਾਠਾਂ ਨੂੰ ਦੋ-ਪਾਸੜ ਗੱਲਬਾਤ ਵਿੱਚ ਬਦਲਦੇ ਹਨ।",
    fluencyMotherTitle: "ਮਾਤ ਭਾਸ਼ਾ ਵਿੱਚ ਰਵਾਨਗੀ",
    fluencyMotherBody: "ਜਿਸ ਭਾਸ਼ਾ ਵਿੱਚ ਤੁਸੀਂ ਸੁਪਨੇ ਦੇਖਦੇ ਹੋ ਉਸ ਵਿੱਚ ਸਿੱਖਣਾ ਸਭ ਤੋਂ ਡੂੰਘਾ ਹੁੰਦਾ ਹੈ। ਸਾਖਰ 20+ ਭਾਰਤੀ ਭਾਸ਼ਾਵਾਂ ਵਿੱਚ ਸਿਖਾਉਂਦਾ ਹੈ।",
    thePlatformBadge: "ਪਲੇਟਫਾਰਮ",
    platformTitle: "ਇੱਕ ਜਮਾਤ ਜੋ ਹਰ ਸਿੱਖਣ ਵਾਲੇ ਦੇ ਅਨੁਕੂਲ ਹੁੰਦੀ ਹੈ",
    platformSubtitle: "ਪੜ੍ਹਨਾ, ਲਿਖਣਾ ਅਤੇ ਬੋਲਣਾ ਸਿਖਾਉਣ ਲਈ ਤਿੰਨ ਬੁੱਧੀਮਾਨ ਮੋਡੀਊਲ ਮਿਲ ਕੇ ਕੰਮ ਕਰਦੇ ਹਨ।",
    mod1Tag: "01 / ਪੜ੍ਹਨਾ",
    mod1Title: "ਇੰਟਰਐਕਟਿਵ ਪੜ੍ਹਨਾ",
    mod1Desc: "ਰੋਜ਼ਾਨਾ ਦੇ ਸਥਾਨਕ ਕੰਮਾਂ ਦੇ ਆਲੇ-ਦੁਆਲੇ ਬਣਾਏ ਗਏ ਕਸਟਮ ਸਮੱਗਰੀ ਡੈੱਕ।",
    mod2Tag: "02 / ਲਿਖਣਾ",
    mod2Title: "ਰੀਅਲ-ਟਾਈਮ ਟ੍ਰੇਸਿੰਗ",
    mod2Desc: "ਸਕ੍ਰੀਨ 'ਤੇ ਅੱਖਰ ਟ੍ਰੇਸ ਕਰੋ ਅਤੇ ਸੁਧਾਰ ਪ੍ਰਾਪਤ ਕਰੋ।",
    mod3Tag: "03 / ਬੋਲਣਾ",
    mod3Title: "ਆਵਾਜ਼ ਤਸਦੀਕ",
    mod3Desc: "ਊਚੀ ਬੋਲੋ ਅਤੇ ਸੁਣੋ ਕਿ ਤੁਸੀਂ ਕਿੰਨੇ ਸਹੀ ਹੋ।",
    stat1Label: "ਖੇਤਰੀ ਭਾਸ਼ਾਵਾਂ",
    stat2Label: "ਉਚਾਰਨ ਸ਼ੁੱਧਤਾ",
    stat3Label: "ਸਿੱਖਣ ਵਾਲੇ ਸ਼ਾਮਲ ਹੋਏ",
    stat4Label: "ਸਾਖਰਤਾ ਮੋਡੀਊਲ",
    aiCompanionBadge: "AI ਸਾਖਰਤਾ ਸਾਥੀ",
    voiceDetectorLabel: "AI ਆਵਾਜ਼ ਭਾਸ਼ਾ ਚੋਣਕਾਰ",
    listening: "ਸੁਣ ਰਿਹਾ ਹੈ…",
    voiceListeningPrompt: "ਆਪਣੀ ਮਾਤ ਭਾਸ਼ਾ ਵਿੱਚ ਬੋਲੋ…",
    detectedLabel: "ਪਛਾਣਿਆ ਗਿਆ",
    tryLiveDemo: "ਲਾਇਵ ਡੈਮੋ ਅਜ਼ਮਾਓ",
    voiceAiLabel: "ਆਵਾਜ਼ AI",
    tracingLabel: "ਟ੍ਰੇਸਿੰਗ",
    scrollLabel: "ਹੇਠਾਂ ਸਕ੍ਰੋਲ ਕਰੋ",
    micBtnTooltip: "ਮਾਈਕ 'ਤੇ ਕਲਿੱਕ ਕਰੋ ਅਤੇ ਬੋਲੋ!",
    secReading: "ਪੜ੍ਹਨਾ",
    secWriting: "ਲਿਖਣਾ",
    secSpeaking: "ਬੋਲਣਾ",
    secReasoning: "ਤਕ",
    langHindi: "ਹਿੰਦੀ",
    langTamil: "ਤਮਿਲ",
    langBengali: "ਬੰਗਾਲੀ",
    ourApproachBadge: "ਸਾਡਾ ਪਹੁੰਚ",
    whyWeBuiltTitle: "ਅਸੀਂ ਕਿਉਂ ਬਣਾਇਆ",
    whyWeBuiltHighlight: "ਸਾਖਰ",
    approachSubtitle: "ਚਾਰ ਵਿਸ਼ਵਾਸ ਜੋ ਪਲੇਟਫਾਰਮ 'ਤੇ ਹਰ ਪਾਠ ਅਤੇ ਪ੍ਰਤੀਕਿਰਿਆ ਨੂੰ ਆਕਾਰ ਦਿੰਦੇ ਹਨ।",
    literacyGapTitle: "ਸਾਖਰਤਾ ਦਾ ਅੰਤਰ ਮਾਨਵੀ ਹੈ",
    literacyGapBody: "ਲਾੱਖਾਂ ਬਾਲਗ ਰਵਾਨਗੀ ਨਾਲ ਬੋਲਦੇ ਹਨ ਪਰ ਉਹਨਾਂ ਨੂੰ ਕਦੇ ਵਿਸ਼ਵਾਸ ਨਾਲ ਪੜ੍ਹਨਾ ਜਾਂ ਲਿਖਣਾ ਨਹੀਂ ਸਿਖਾਇਆ ਗਿਆ। ਇਹ ਤਕਨਾਲੋਜੀ ਦੀ ਸਮੱਸਿਆ ਨਹੀਂ ਹੈ — ਇਹ ਸਬਰ ਅਤੇ ਸਤਿਕਾਰ ਨਾਲ ਡਿਜ਼ਾਈਨ ਕਰਨ ਦੀ ਮਾਨਵੀ ਸਮੱਸਿਆ ਹੈ।",
    oneSizeFitsTitle: "ਇੱਕ ਨਾਪ ਸਭ ਲਈ ਢੁਕਵਾਂ ਨਹੀਂ",
    oneSizeFitsBody: "ਸਾਖਰ ਇੱਕ ਛੋਟੇ ਮੁਲਾਂਕਣ ਨਾਲ ਸ਼ੁਰੂ ਹੁੰਦਾ ਹੈ ਅਤੇ ਸਿੱਖਣ ਵਾਲੇ ਦੀ ਆਪਣੀ ਗਤੀ, ਭਾਸ਼ਾ ਅਤੇ ਪੱਧਰ ਦੇ ਅਨੁਕੂਲ ਰਸਤਾ ਬਣਾਉਂਦਾ ਹੈ।",
    aiListensTitle: "AI ਜੋ ਵਾਪਸ ਸੁਣਦਾ ਹੈ",
    aiListensBody: "ਰੀਅਲ-ਟਾਈਮ ਉਚਾਰਨ ਫੀਡਬੈਕ ਅਤੇ ਅੱਖਰ ਟ੍ਰੇਸਿੰਗ ਪਾਠਾਂ ਨੂੰ ਦੋ-ਪਾਸੜ ਗੱਲਬਾਤ ਵਿੱਚ ਬਦਲਦੇ ਹਨ।",
    fluencyMotherTitle: "ਮਾਤ ਭਾਸ਼ਾ ਵਿੱਚ ਰਵਾਨਗੀ",
    fluencyMotherBody: "ਜਿਸ ਭਾਸ਼ਾ ਵਿੱਚ ਤੁਸੀਂ ਸੁਪਨੇ ਦੇਖਦੇ ਹੋ ਉਸ ਵਿੱਚ ਸਿੱਖਣਾ ਸਭ ਤੋਂ ਡੂੰਘਾ ਹੁੰਦਾ ਹੈ। ਸਾਖਰ 20+ ਭਾਰਤੀ ਭਾਸ਼ਾਵਾਂ ਵਿੱਚ ਸਿਖਾਉਂਦਾ ਹੈ।",
    thePlatformBadge: "ਪਲੇਟਫਾਰਮ",
    platformTitle: "ਇੱਕ ਜਮਾਤ ਜੋ ਹਰ ਸਿੱਖਣ ਵਾਲੇ ਦੇ ਅਨੁਕੂਲ ਹੁੰਦੀ ਹੈ",
    platformSubtitle: "ਪੜ੍ਹਨਾ, ਲਿਖਣਾ ਅਤੇ ਬੋਲਣਾ ਸਿਖਾਉਣ ਲਈ ਤਿੰਨ ਬੁੱਧੀਮਾਨ ਮੋਡੀਊਲ ਮਿਲ ਕੇ ਕੰਮ ਕਰਦੇ ਹਨ।",
    mod1Tag: "01 / ਪੜ੍ਹਨਾ",
    mod1Title: "ਇੰਟਰਐਕਟਿਵ ਪੜ੍ਹਨਾ",
    mod1Desc: "ਰੋਜ਼ਾਨਾ ਦੇ ਸਥਾਨਕ ਕੰਮਾਂ ਦੇ ਆਲੇ-ਦੁਆਲੇ ਬਣਾਏ ਗਏ ਕਸਟਮ ਸਮੱਗਰੀ ਡੈੱਕ।",
    mod2Tag: "02 / ਲਿਖਣਾ",
    mod2Title: "ਰੀਅਲ-ਟਾਈਮ ਟ੍ਰੇਸਿੰਗ",
    mod2Desc: "ਸਕ੍ਰੀਨ 'ਤੇ ਅੱਖਰ ਟ੍ਰੇਸ ਕਰੋ ਅਤੇ ਸੁਧਾਰ ਪ੍ਰਾਪਤ ਕਰੋ।",
    mod3Tag: "03 / ਬੋਲਣਾ",
    mod3Title: "ਆਵਾਜ਼ ਤਸਦੀਕ",
    mod3Desc: "ਊਚੀ ਬੋਲੋ ਅਤੇ ਸੁਣੋ ਕਿ ਤੁਸੀਂ ਕਿੰਨੇ ਸਹੀ ਹੋ।",
    stat1Label: "ਖੇਤਰੀ ਭਾਸ਼ਾਵਾਂ",
    stat2Label: "ਉਚਾਰਨ ਸ਼ੁੱਧਤਾ",
    stat3Label: "ਸਿੱਖਣ ਵਾਲੇ ਸ਼ਾਮਲ ਹੋਏ",
    stat4Label: "ਸਾਖਰਤਾ ਮੋਡੀਊਲ",
    beginYourJourney: "ਆਪਣੀ ਯਾਤਰਾ ਸ਼ੁਰੂ ਕਰੋ",
    ctaHeadlineLine1: "ਤੁਹਾਡਾ ਸਿੱਖਿਆ ਹਰ ਸ਼ਬਦ",
    ctaHeadlineLine2: "ਇੱਕ ਨਵਾਂ ਦਰਵਾਜ਼ਾ ਖੋਲ੍ਹਦਾ ਹੈ।",
    getStartedFree: "ਮੁਫ਼ਤ ਸ਼ੁਰੂ ਕਰੋ",
    watchDemo: "ਡੈਮੋ ਦੇਖੋ",
    home: "ਹੋਮ", signIn: "ਸਾਈਨ ਇਨ", createAccount: "ਖਾਤਾ ਬਣਾਓ", welcomeBack: "ਜੀ ਆਇਆਂ ਨੂੰ",
    signInSub: "ਆਪਣੀ ਸਿੱਖਣ ਦੀ ਯਾਤਰਾ ਜਾਰੀ ਰੱਖਣ ਲਈ ਸਾਈਨ ਇਨ ਕਰੋ।", email: "✉️ ਈਮੇਲ ਪਤਾ", password: "🔒 ਪਾਸਵਰਡ", fullName: "👤 ਪੂਰਾ ਨਾਮ", or: "ਜਾਂ",
    googleSignIn: "ਗੂਗਲ ਨਾਲ ਜਾਰੀ ਰੱਖੋ", newHere: "ਇੱਥੇ ਨਵੇਂ ਹੋ?", alreadyHaveAccount: "ਖਾਤਾ ਹੈਗਾ ਹੈ?", landingTitle: "ਵਿਅਕਤੀਗਤ AI ਰਾਹੀਂ ਸਾਖਰਤਾ ਦਾ ਸਸ਼ਕਤੀਕਰਨ",
    landingTitleLine1: "ਸਾਖਰਤਾ ਦਾ ਸਸ਼ਕਤੀਕਰਨ", landingTitleLine2: "AI ਬੁੱਧੀ ਰਾਹੀਂ",
    landingSub: "ਇੱਕ ਅਨੁਕੂਲ ਸਿੱਖਣ ਪਲੇਟਫਾਰਮ ਜੋ ਬਾਲਗਾਂ ਅਤੇ ਪਹਿਲੀ ਪੀੜ੍ਹੀ ਦੇ ਸਿੱਖਣ ਵਾਲਿਆਂ ਨੂੰ ਉਹਨਾਂ ਦੀਆਂ ਖੇਤਰੀ ਮਾਤ੍ਰਭਾਸ਼ਾਵਾਂ ਦੀ ਵਰਤੋਂ ਕਰਕੇ ਮੁਢਲੀ ਪੜ੍ਹਨ, ਲਿਖਣ ਅਤੇ ਬੋਲਣ ਦਾ ਵਿਸ਼ਵਾਸ ਹਾਸਲ ਕਰਨ ਵਿੱਚ ਮਦਦ ਕਰਦਾ ਹੈ।",
    getStarted: "ਸ਼ੁਰూ ਕਰੋ", registerTitle: "ਆਪਣੀ ਪ੍ਰੋਫਾਈਲ ਬਣਾਓ", registerSub: "ਸਾਡੇ ਭਾਈਚਾਰੇ ਵਿੱਚ ਸਭਲ ਹੋਵੋ ਅਤੇ ਆਪਣੇ ਸਿੱਖਣ ਦੇ ਦਾਇਰੇ ਦਾ ਵਿਸਤਾਰ ਕਰੋ।",
    languageLabel: "🌐 ਪਸੰਦੀਦਾ ਮਾਤਭਾਸ਼ਾ", registerLeftTitle: "ਤੁਹਾਡੀ ਸਾਖਰਤਾ ਦੀ ਯਾਤਰਾ ਇੱਥੋਂ ਸੁਰੂ ਹੁੰਦੀ ਹੈ।",
    registerLeftSub: "ਆਵਾਜ਼ ਅਭਿਆਸ ਮੁਲਾਂਕਣ, ਰੀਅਲ-ਟਾਈਮ ਫੀਡਬੈਕ, ਅਤੇ ਰੋਜ਼ਾਨਾ ਪੜ੍ਹਨ ਦੇ ਪਾਠਾਂ ਨੂੰ ਅਨਲੌਕ ਕਰਨ ਲਈ ਇੱਕ ਪ੍ਰੋਫਾਈਲ ਬਣਾਓ।",
    loginLeftTitle: "ਤੁਹਾਡਾ ਸਿੱਖਿਆ ਹਰ ਸ਼ਬਦ ਇੱਕ ਨਵਾਂ ਦਰਵਾਜ਼ਾ ਖੋਲ੍ਹਦਾ ਹੈ।", loginLeftSub: "ਨਿੱਜੀ ਪੜ੍ਹਨ, ਲਿਖਣ ਅਤੇ ਬੋਲਣ ਦਾ ਅਭਿਆਸ — ਤੁਹਾਡੀ ਆਪਣੀ ਭਾਸ਼ਾ ਵਿੱਚ, ਤੁਹਾਡੀ ਆਪਣੀ ਰਫ਼ਤਾਰ ਨਾਲ।",
    dashboardTitle: "ਤੁਹਾਡੇ ਡੈਸ਼ਬੋਰਡ ਵਿੱਚ ਜੀ ਆਇਆਂ ਨੂੰ!", logout: "ਲੌਗ ਆਊਟ"
  },
  bengali: {
    ourApproachBadge: "আমাদের দৃষ্টিভঙ্গি",
    whyWeBuiltTitle: "কেন আমরা তৈরি করেছি",
    whyWeBuiltHighlight: "স্বাক্ষর",
    approachSubtitle: "চারটি বিশ্বাস যা প্ল্যাটফর্মের প্রতিটি পাঠ এবং প্রতিক্রিয়া তৈরি করে।",
    literacyGapTitle: "সাক্ষরতার ব্যবধান মানবিক",
    literacyGapBody: "লক্ষ লাখ প্রাপ্তবয়স্ক মানুষ সাবলীলভাবে কথা বলেন কিন্তু তাদের কখনো আত্মবিশ্বাসের সাথে পড়তে বা লিখতে শেখানো হয়নি। এটি কোনও প্রযুক্তির সমস্যা নয় — এটি ধৈর্য ও মর্যাদার সাথে তৈরি করার একটি মানবিক সমস্যা।",
    oneSizeFitsTitle: "এক মাপ সবার জন্য নয়",
    oneSizeFitsBody: "ঐতিহ্যগত ক্লাসগুলি একটি নির্দিষ্ট সূচনা ধরে নেয়। স্বাক্ষর একটি ছোট মূল্যায়নের মাধ্যমে শুরু হয় এবং শিক্ষার্থীর নিজস্ব গতি, ভাষা ও স্তরের সাথে মানিয়ে নেওয়া পথ তৈরি করে।",
    aiListensTitle: "এআই যা প্রতিক্রিয়া শোনে",
    aiListensBody: "রিয়েল-টাইম উচ্চারণ প্রতিক্রিয়া এবং অক্ষর ট্রেসিং নিষ্ক্রিয় পাঠকে দ্বিমুখী কথোপকথনে পরিণত করে।",
    fluencyMotherTitle: "মাতৃভাষায় সাবলীলতা",
    fluencyMotherBody: "যে ভাষায় আপনি স্বপ্ন দেখেন সেই ভাষায় শেখা সবচেয়ে গভীর হয়। স্বাক্ষর ২০টিরও বেশি ভারতীয় আঞ্চলিক ভাষায় শিক্ষা দেয়।",
    thePlatformBadge: "প্ল্যাটফর্ম",
    platformTitle: "একটি শ্রেণীকক্ষ যা প্রতিটি শিক্ষার্থীর সাথে খাপ খাইয়ে নেয়",
    platformSubtitle: "তিনটি বুদ্ধিমত্তা মডিউল পড়া, লেখা এবং বলা তৈরি করতে একসাথে কাজ করে।",
    mod1Tag: "01 / পঠন",
    mod1Title: "ইন্টারেক্টিভ পঠন",
    mod1Desc: "দৈনন্দিন স্থানীয় কাজের চারপাশে তৈরি কাস্টম কন্টেন্ট ডেক।",
    mod2Tag: "02 / লিখন",
    mod2Title: "রিয়েল-টাইম ট্রেসিং",
    mod2Desc: "স্ক্রিনে অক্ষর ট্রেস করুন এবং স্ট্রোক-বাই-স্ট্রোক সংশোধন পান।",
    mod3Tag: "03 / কথন",
    mod3Title: "ভয়েস যাচাইকরণ",
    mod3Desc: "উচ্চস্বরে বলুন এবং শুনুন আপনি কত কাছাকাছি।",
    stat1Label: "আঞ্চলিক ভাষা",
    stat2Label: "উচ্চারণ নির্ভুলতা",
    stat3Label: "শিক্ষার্থী যুক্ত হয়েছে",
    stat4Label: "সাক্ষরতা মডিউল",
    aiCompanionBadge: "এআই সাক্ষরতা সঙ্গী",
    voiceDetectorLabel: "এআই ভয়েস ভাষা নির্বাচক",
    listening: "শুনছে…",
    voiceListeningPrompt: "আপনার মাতৃভাষায় কথা বলুন…",
    detectedLabel: "সনাক্ত করা হয়েছে",
    tryLiveDemo: "লাইভ ডেমো চেষ্টা করুন",
    voiceAiLabel: "ভয়েস এআই",
    tracingLabel: "ট্রেসিং",
    scrollLabel: "স্ক্রোল করুন",
    micBtnTooltip: "মাইকে ক্লিক করুন এবং কথা বলুন!",
    secReading: "পঠন",
    secWriting: "লিখন",
    secSpeaking: "কথন",
    secReasoning: "যুক্তি",
    langHindi: "হিন্দি",
    langTamil: "তামিল",
    langBengali: "বাংলা",
    ourApproachBadge: "আমাদের দৃষ্টিভঙ্গি",
    whyWeBuiltTitle: "কেন আমরা তৈরি করেছি",
    whyWeBuiltHighlight: "স্বাক্ষর",
    approachSubtitle: "চারটি বিশ্বাস যা প্ল্যাটফর্মের প্রতিটি পাঠ এবং প্রতিক্রিয়া তৈরি করে।",
    literacyGapTitle: "সাক্ষরতার ব্যবধান মানবিক",
    literacyGapBody: "লক্ষ লাখ প্রাপ্তবয়স্ক মানুষ সাবলীলভাবে কথা বলেন কিন্তু তাদের কখনো আত্মবিশ্বাসের সাথে পড়তে বা লিখতে শেখানো হয়নি। এটি কোনও প্রযুক্তির সমস্যা নয় — এটি ধৈর্য ও মর্যাদার সাথে তৈরি করার একটি মানবিক সমস্যা।",
    oneSizeFitsTitle: "এক মাপ সবার জন্য নয়",
    oneSizeFitsBody: "ঐতিহ্যগত ক্লাসগুলি একটি নির্দিষ্ট সূচনা ধরে নেয়। স্বাক্ষর একটি ছোট মূল্যায়নের মাধ্যমে শুরু হয় এবং শিক্ষার্থীর নিজস্ব গতি, ভাষা ও স্তরের সাথে মানিয়ে নেওয়া পথ তৈরি করে।",
    aiListensTitle: "এআই যা প্রতিক্রিয়া শোনে",
    aiListensBody: "রিয়েল-টাইম উচ্চারণ প্রতিক্রিয়া এবং অক্ষর ট্রেসিং নিষ্ক্রিয় পাঠকে দ্বিমুখী কথোপকথনে পরিণত করে।",
    fluencyMotherTitle: "মাতৃভাষায় সাবলীলতা",
    fluencyMotherBody: "যে ভাষায় আপনি স্বপ্ন দেখেন সেই ভাষায় শেখা সবচেয়ে গভীর হয়। স্বাক্ষর ২০টিরও বেশি ভারতীয় আঞ্চলিক ভাষায় শিক্ষা দেয়।",
    thePlatformBadge: "প্ল্যাটফর্ম",
    platformTitle: "একটি শ্রেণীকক্ষ যা প্রতিটি শিক্ষার্থীর সাথে খাপ খাইয়ে নেয়",
    platformSubtitle: "তিনটি বুদ্ধিমত্তা মডিউল পড়া, লেখা এবং বলা তৈরি করতে একসাথে কাজ করে।",
    mod1Tag: "01 / পঠন",
    mod1Title: "ইন্টারেক্টিভ পঠন",
    mod1Desc: "দৈনন্দিন স্থানীয় কাজের চারপাশে তৈরি কাস্টম কন্টেন্ট ডেক।",
    mod2Tag: "02 / লিখন",
    mod2Title: "রিয়েল-টাইম ট্রেসিং",
    mod2Desc: "স্ক্রিনে অক্ষর ট্রেস করুন এবং স্ট্রোক-বাই-স্ট্রোক সংশোধন পান।",
    mod3Tag: "03 / কথন",
    mod3Title: "ভয়েস যাচাইকরণ",
    mod3Desc: "উচ্চস্বরে বলুন এবং শুনুন আপনি কত কাছাকাছি — এআই চালিত উচ্চারণ প্রতিক্রিয়া।",
    stat1Label: "আঞ্চলিক ভাষা",
    stat2Label: "উচ্চারণ নির্ভুলতা",
    stat3Label: "শিক্ষার্থী যুক্ত হয়েছে",
    stat4Label: "সাক্ষরতা মডিউল",
    beginYourJourney: "আপনার যাত্রা শুরু করুন",
    ctaHeadlineLine1: "আপনার শেখা প্রতিটি শব্দ",
    ctaHeadlineLine2: "একটি নতুন দরজা খুলে দেয়।",
    getStartedFree: "বিনামূল্যে শুরু করুন",
    watchDemo: "ডেমো দেখুন",
    home: "হোম", signIn: "সাইন ইন", createAccount: "অ্যাকাউন্ট তৈরি করুন", welcomeBack: "স্বাগতম",
    signInSub: "আপনার শেখার যাত্রা চালিয়ে যেতে সাইন ইন করুন।", email: "✉️ ইমেল ঠিকানা", password: "🔒 পাসওয়ার্ড", fullName: "👤 পুরো নাম", or: "অথবা",
    googleSignIn: "গুগল এর সাথে এগিয়ে যান", newHere: "এখানে নতুন?", alreadyHaveAccount: "ইতিমধ্যে অ্যাকাউন্ট আছে?", landingTitle: "এআই এর মাধ্যমে সাক্ষরতার ক্ষমতায়ন",
    landingTitleLine1: "সাক্ষরতার ক্ষমতায়ন", landingTitleLine2: "AI বুদ্ধিমত্তার মাধ্যমে",
    landingSub: "একটি ব্যক্তিগতকৃত শেখার সঙ্গী যা প্রাপ্তবয়স্ক এবং প্রথম প্রজন্মের শিক্ষার্থীদের আঞ্চলিক ভাষায় মৌলিক পড়া, লেখা এবং বলার দক্ষতা অর্জন করতে সহায়তা করার জন্য ডিজাইন করা হয়েছে।",
    getStarted: "শুরু করুন", registerTitle: "আপনার অ্যাকাউন্ট তৈরি করুন", registerSub: "আমাদের সম্প্রদায়ে যোগ দিন এবং আপনার শেখার দিগন্ত প্রসারিত করুন।",
    languageLabel: "🌐 পছন্দের মাতৃভাষা", registerLeftTitle: "আপনার সাক্ষরতার যাত্রা এখানেই শুরু।",
    registerLeftSub: "ভয়েস প্র্যাকটিস অ্যাসেসমেন্ট, রিয়েল-টাইম ফিডব্যাক এবং অভিযোজিত দৈনিক পাঠ আনলক করতে একটি প্রোফাইল তৈরি করুন।",
    loginLeftTitle: "আপনার শেখা প্রতিটি শব্দ একটি নতুন দরজা খুলে দেয়।", loginLeftSub: "ব্যক্তিগতকৃত পড়া, লেখা এবং বলার অনুশীলন — আপনার নিজস্ব ভাষায়, আপনার নিজস্ব গতিতে।",
    dashboardTitle: "আপনার ড্যাশবোর্ডে স্বাগতম!", logout: "লগ আউট"
  },
  marathi: {
    ourApproachBadge: "आमचा दृष्टीकोन",
    whyWeBuiltTitle: "आम्ही का बनवले",
    whyWeBuiltHighlight: "साक्षर",
    approachSubtitle: "प्लॅटफॉर्मवरील प्रत्येक धडा आणि अभिप्रायाला आकार देणारे चार विश्वास.",
    literacyGapTitle: "साक्षरतेतील दरी ही मानवी आहे",
    literacyGapBody: "कोट्यवधी प्रौढ अस्खलितपणे बोलतात पण त्यांना आत्मविश्वासाने वाचायला किंवा लिहायला शिकवले गेले नाही. ही तंत्रज्ञानाची समस्या नाही — ती संयमाने आणि आदराने हाताळण्याची मानवी समस्या आहे.",
    oneSizeFitsTitle: "एकच माप सर्वांना बसत नाही",
    oneSizeFitsBody: "पारंपारिक वर्ग एकच सुरुवात मानतात. साक्षर एका लहान मूल्यांकनापासून सुरू होतो आणि शिकणाऱ्याच्या गती आणि भाषेनुसार मार्ग तयार करतो.",
    aiListensTitle: "ऐकणारे AI",
    aiListensBody: "रिअल-टाइम उच्चार अभिप्राय आणि अक्षर ट्रेसिंग धड्यांना दोन-मार्गी संभाषणात बदलतात.",
    fluencyMotherTitle: "मातृभाषेत अस्खलितता",
    fluencyMotherBody: "ज्या भाषेत तुम्ही स्वप्न पाहता त्यात शिकणे सर्वात खोलवर रुजते. साक्षर २०+ भारतीय भाषांमध्ये शिकवतो.",
    thePlatformBadge: "प्लॅटफॉर्म",
    platformTitle: "प्रत्येक शिकणाऱ्याशी जुळवून घेणारा वर्ग",
    platformSubtitle: "वाचन, लेखन आणि भाषण कौशल्य विकसित करण्यासाठी तीन बुद्धिमत्ता मॉड्यूल एकत्र काम करतात.",
    mod1Tag: "01 / वाचन",
    mod1Title: "इंटरअॅक्टिव्ह वाचन",
    mod1Desc: "दैनंदिन स्थानिक कामांवर आधारित कस्टम सामग्री डेक.",
    mod2Tag: "02 / लेखन",
    mod2Title: "रिअल-टाइम ट्रेसिंग",
    mod2Desc: "स्क्रीनवर अक्षरे ट्रेस करा आणि सुधारात्मक अभिप्राय मिळवा.",
    mod3Tag: "03 / भाषण",
    mod3Title: "व्हॉइस पडताळणी",
    mod3Desc: "मोठ्याने बोला आणि तुमचे उच्चार किती अचूक आहेत ते ऐका.",
    stat1Label: "प्रादेशिक भाषा",
    stat2Label: "उच्चार अचूकता",
    stat3Label: "शिकणारे जोडले गेले",
    stat4Label: "साक्षरता मॉड्यूल",
    aiCompanionBadge: "एआय साक्षरता सोबती",
    voiceDetectorLabel: "एआय व्हॉइस भाषा निवडक",
    listening: "ऐकत आहे…",
    voiceListeningPrompt: "तुमच्या मातृभाषेत बोला…",
    detectedLabel: "ओळखले गेले",
    tryLiveDemo: "लाइव्ह डेमो वापरून पहा",
    voiceAiLabel: "व्हॉइस एआय",
    tracingLabel: "ट्रेसिंग",
    scrollLabel: "खाली स्क्रोल करा",
    micBtnTooltip: "माइकवर क्लिक करा आणि बोला!",
    secReading: "वाचन",
    secWriting: "लेखन",
    secSpeaking: "भाषण",
    secReasoning: "तर्क",
    langHindi: "हिंदी",
    langTamil: "तमिळ",
    langBengali: "बंगाली",
    ourApproachBadge: "आमचा दृष्टीकोन",
    whyWeBuiltTitle: "आम्ही का बनवले",
    whyWeBuiltHighlight: "साक्षर",
    approachSubtitle: "प्लॅटफॉर्मवरील प्रत्येक धडा आणि अभिप्रायाला आकार देणारे चार विश्वास.",
    literacyGapTitle: "साक्षरतेतील दरी ही मानवी आहे",
    literacyGapBody: "कोट्यवधी प्रौढ अस्खलितपणे बोलतात पण त्यांना आत्मविश्वासाने वाचायला किंवा लिहायला शिकवले गेले नाही. ही तंत्रज्ञानाची समस्या नाही — ती संयमाने आणि आदराने हाताळण्याची मानवी समस्या आहे.",
    oneSizeFitsTitle: "एकच माप सर्वांना बसत नाही",
    oneSizeFitsBody: "पारंपारिक वर्ग एकच सुरुवात मानतात. साक्षर एका लहान मूल्यांकनापासून सुरू होतो आणि शिकणाऱ्याच्या गती आणि भाषेनुसार मार्ग तयार करतो.",
    aiListensTitle: "ऐकणारे AI",
    aiListensBody: "रिअल-टाइम उच्चार अभिप्राय आणि अक्षर ट्रेसिंग धड्यांना दोन-मार्गी संभाषणात बदलतात.",
    fluencyMotherTitle: "मातृभाषेत अस्खलितता",
    fluencyMotherBody: "ज्या भाषेत तुम्ही स्वप्न पाहता त्यात शिकणे सर्वात खोलवर रुजते. साक्षर २०+ भारतीय भाषांमध्ये शिकवतो.",
    thePlatformBadge: "प्लॅटफॉर्म",
    platformTitle: "प्रत्येक शिकणाऱ्याशी जुळवून घेणारा वर्ग",
    platformSubtitle: "वाचन, लेखन आणि भाषण कौशल्य विकसित करण्यासाठी तीन बुद्धिमत्ता मॉड्यूल एकत्र काम करतात.",
    mod1Tag: "01 / वाचन",
    mod1Title: "इंटरअॅक्टिव्ह वाचन",
    mod1Desc: "दैनंदिन स्थानिक कामांवर आधारित कस्टम सामग्री डेक.",
    mod2Tag: "02 / लेखन",
    mod2Title: "रिअल-टाइम ट्रेसिंग",
    mod2Desc: "स्क्रीनवर अक्षरे ट्रेस करा आणि सुधारात्मक अभिप्राय मिळवा.",
    mod3Tag: "03 / भाषण",
    mod3Title: "व्हॉइस पडताळणी",
    mod3Desc: "मोठ्याने बोला आणि तुमचे उच्चार किती अचूक आहेत ते ऐका.",
    stat1Label: "प्रादेशिक भाषा",
    stat2Label: "उच्चार अचूकता",
    stat3Label: "शिकणारे जोडले गेले",
    stat4Label: "साक्षरता मॉड्यूल",
    beginYourJourney: "तुमचा प्रवास सुरू करा",
    ctaHeadlineLine1: "तुम्ही शिकलेला प्रत्येक शब्द",
    ctaHeadlineLine2: "एक नवीन दार उघडतो.",
    getStartedFree: "विनामूल्य सुरू करा",
    watchDemo: "डेमो पहा",
    home: "होम", signIn: "साइन इन", createAccount: "खाते तयार करा", welcomeBack: "स्वागत आहे",
    signInSub: "तुमचा शिकण्याचा प्रवास सुरू ठेवण्यासाठी साइन इन करा.", email: "✉️ ईमेल पत्ता", password: "🔒 पासवर्ड", fullName: "👤 पूर्ण नाव", or: "किंवा",
    googleSignIn: "गुगलसह पुढे जा", newHere: "नवीन आहात?", alreadyHaveAccount: "आधीच खाते आहे का?", landingTitle: "एआई द्वारे साक्षरतेचे सक्षमीकरण",
    landingTitleLine1: "साक्षरता सक्षमीकरण", landingTitleLine2: "एआई बुद्धिमत्तेद्वारे",
    landingSub: "एक वैयक्तिकृत शिक्षण सोबती जो प्रौढ आणि पहिल्या पिढीतील शिकणाऱ्यांना प्रादेशिक भाषांमध्ये मूलभूत वाचन, लेखन आणि बोलण्याचे कौशल्य आत्मसात करण्यास मदत करण्यासाठी डिझाइन केलेले है.",
    getStarted: "सुरू करा", registerTitle: "तुमचे खाते तयार करा", registerSub: "आमच्या समुदायात सामील व्हा आणि तुमच्या शिकण्याच्या कक्षा रुंदावा.",
    languageLabel: "🌐 पसंतीची मातृभाषा", registerLeftTitle: "तुमचा साक्षरतेचा प्रवास इथून सुरू होतो.",
    registerLeftSub: "व्हॉइस प्रॅक्टिस असेसमेंट, रिअल-टाइम फीडबॅक आणि अडॅप्टिव्ह डेली रीडिंग धडे अनलॉक करण्यासाठी एक प्रोफाईल तयार करा.",
    loginLeftTitle: "तुम्ही शिकलेला प्रत्येक शब्द एक नवीन दार उघडतो.", loginLeftSub: "वैयक्तिकृत वाचन, लेखन आणि बोलण्याचा सराव — तुमच्या स्वतःच्या भाषेत, तुमच्या स्वतःच्या गतीने.",
    dashboardTitle: "तुमच्या डॅशबोर्डवर स्वागत आहे!", logout: "लॉग आउट"
  },
  tamil: {
    ourApproachBadge: "எங்கள் அணுகுமுறை",
    whyWeBuiltTitle: "நாங்கள் ஏன் உருவாக்கினோம்",
    whyWeBuiltHighlight: "சாக்ஷர்",
    approachSubtitle: "தளத்தில் உள்ள ஒவ்வொரு பாடத்தையும் வடிவமைக்கும் நான்கு நம்பிக்கைகள்.",
    literacyGapTitle: "எழுத்தறிவு இடைவெளி மனிதநேயமானது",
    literacyGapBody: "மில்லியன் கணக்கான பெரியவர்கள் சரளமாகப் பேசுகிறார்கள், ஆனால் படிக்கவோ எழுதவோ கற்பிக்கப்படவில்லை. இது ஒரு தொழில்நுட்பப் பிரச்சினை அல்ல — பொறுமையுடன் வடிவமைக்கப்பட வேண்டிய மனிதப் பிரச்சினை.",
    oneSizeFitsTitle: "ஒரு அளவு அனைவருக்கும் பொருந்தாது",
    oneSizeFitsBody: "சாக்ஷர் ஒரு குறுகிய மதிப்பீட்டோடு தொடங்கி, கற்பவரின் சொந்த வேகம், மொழி மற்றும் நிலைக்கு ஏற்ப பாதையை உருவாக்குகிறது.",
    aiListensTitle: "திரும்பி கேட்கும் AI",
    aiListensBody: "நிகழ்நேர உச்சரிப்பு கருத்து மற்றும் எழுத்து ட்ரேசிங் செயலற்ற பாடங்களை இருவழி உரையாடலாக மாற்றுகின்றன.",
    fluencyMotherTitle: "தாய்மொழியில் ஆளுமை",
    fluencyMotherBody: "நீங்கள் கனவு காணும் மொழியில் கற்றல் மிகவும் ஆழமாகப் பதிகிறது. சாக்ஷர் 20+ இந்திய பிராந்திய மொழிகளில் கற்பிக்கிறது.",
    thePlatformBadge: "தளம்",
    platformTitle: "ஒவ்வொரு கற்பவருக்கும் ஏதுவாக மாறும் வகுப்பறை",
    platformSubtitle: "மூன்று நுண்ணறிவு தொகுதிகள் வாசிப்பு, எழுதுதல் மற்றும் பேசுதலை உருவாக்க ஒன்றாகச் செயல்படுகின்றன.",
    mod1Tag: "01 / வாசிப்பு",
    mod1Title: "இன்டராக்டிவ் வாசிப்பு",
    mod1Desc: "அன்றாட உள்ளூர் பணிகளைச் சுற்றி உருவாக்கப்பட்ட தனிப்பயன் உள்ளடக்க தொகுப்புகள்.",
    mod2Tag: "02 / எழுதுதல்",
    mod2Title: "நிகழ்நேர ட்ரேசிங்",
    mod2Desc: "திரையில் எழுத்துக்களை ட்ரேஸ் செய்து பக்கவாட்டு திருத்தத்தைப் பெறுங்கள்.",
    mod3Tag: "03 / பேசுதல்",
    mod3Title: "குரல் சரிபார்ப்பு",
    mod3Desc: "சத்தமாகப் பேசி உச்சரிப்பு துல்லியத்தைக் கேளுங்கள்.",
    stat1Label: "பிராந்திய மொழிகள்",
    stat2Label: "உச்சரிப்பு துல்லியம்",
    stat3Label: "சேர்ந்த கற்பவர்கள்",
    stat4Label: "எழுத்தறிவு தொகுதிகள்",
    aiCompanionBadge: "AI எழுத்தறிவு துணைவன்",
    voiceDetectorLabel: "AI குரல் மொழி தேர்வி",
    listening: "கேட்கிறது…",
    voiceListeningPrompt: "உங்கள் தாய்மொழியில் பேசுங்கள்…",
    detectedLabel: "கண்டறியப்பட்டது",
    tryLiveDemo: "லைவ் டெமோ முயற்சிக்கவும்",
    voiceAiLabel: "குரல் AI",
    tracingLabel: "ட்ரேசிங்",
    scrollLabel: "ஸ்க்ரோல் செய்யவும்",
    micBtnTooltip: "மைக்கை கிளிக் செய்து பேசுங்கள்!",
    secReading: "வாசிப்பு",
    secWriting: "எழுதுதல்",
    secSpeaking: "பேசுதல்",
    secReasoning: "காரணம்",
    langHindi: "இந்தி",
    langTamil: "தமிழ்",
    langBengali: "பெங்காலி",
    ourApproachBadge: "எங்கள் அணுகுமுறை",
    whyWeBuiltTitle: "நாங்கள் ஏன் உருவாக்கினோம்",
    whyWeBuiltHighlight: "சாக்ஷர்",
    approachSubtitle: "தளத்தில் உள்ள ஒவ்வொரு பாடத்தையும் வடிவமைக்கும் நான்கு நம்பிக்கைகள்.",
    literacyGapTitle: "எழுத்தறிவு இடைவெளி மனிதநேயமானது",
    literacyGapBody: "மில்லியன் கணக்கான பெரியவர்கள் சரளமாகப் பேசுகிறார்கள், ஆனால் படிக்கவோ எழுதவோ கற்பிக்கப்படவில்லை. இது ஒரு தொழில்நுட்பப் பிரச்சினை அல்ல — பொறுமையுடன் வடிவமைக்கப்பட வேண்டிய மனிதப் பிரச்சினை.",
    oneSizeFitsTitle: "ஒரு அளவு அனைவருக்கும் பொருந்தாது",
    oneSizeFitsBody: "சாக்ஷர் ஒரு குறுகிய மதிப்பீட்டோடு தொடங்கி, கற்பவரின் சொந்த வேகம், மொழி மற்றும் நிலைக்கு ஏற்ப பாதையை உருவாக்குகிறது.",
    aiListensTitle: "திரும்பி கேட்கும் AI",
    aiListensBody: "நிகழ்நேர உச்சரிப்பு கருத்து மற்றும் எழுத்து ட்ரேசிங் செயலற்ற பாடங்களை இருவழி உரையாடலாக மாற்றுகின்றன.",
    fluencyMotherTitle: "தாய்மொழியில் ஆளுமை",
    fluencyMotherBody: "நீங்கள் கனவு காணும் மொழியில் கற்றல் மிகவும் ஆழமாகப் பதிகிறது. சாக்ஷர் 20+ இந்திய பிராந்திய மொழிகளில் கற்பிக்கிறது.",
    thePlatformBadge: "தளம்",
    platformTitle: "ஒவ்வொரு கற்பவருக்கும் ஏதுவாக மாறும் வகுப்பறை",
    platformSubtitle: "மூன்று நுண்ணறிவு தொகுதிகள் வாசிப்பு, எழுதுதல் மற்றும் பேசுதலை உருவாக்க ஒன்றாகச் செயல்படுகின்றன.",
    mod1Tag: "01 / வாசிப்பு",
    mod1Title: "இன்டராக்டிவ் வாசிப்பு",
    mod1Desc: "அன்றாட உள்ளூர் பணிகளைச் சுற்றி உருவாக்கப்பட்ட தனிப்பயன் உள்ளடக்க தொகுப்புகள்.",
    mod2Tag: "02 / எழுதுதல்",
    mod2Title: "நிகழ்நேர ட்ரேசிங்",
    mod2Desc: "திரையில் எழுத்துக்களை ட்ரேஸ் செய்து பக்கவாட்டு திருத்தத்தைப் பெறுங்கள்.",
    mod3Tag: "03 / பேசுதல்",
    mod3Title: "குரல் சரிபார்ப்பு",
    mod3Desc: "சத்தமாகப் பேசி உச்சரிப்பு துல்லியத்தைக் கேளுங்கள்.",
    stat1Label: "பிராந்திய மொழிகள்",
    stat2Label: "உச்சரிப்பு துல்லியம்",
    stat3Label: "சேர்ந்த கற்பவர்கள்",
    stat4Label: "எழுத்தறிவு தொகுதிகள்",
    beginYourJourney: "உங்கள் பயணத்தைத் தொடங்குங்கள்",
    ctaHeadlineLine1: "நீங்கள் கற்கும் ஒவ்வொரு வார்த்தையும்",
    ctaHeadlineLine2: "ஒரு புதிய கதவைத் திறக்கிறது.",
    getStartedFree: "இலவசமாகத் தொடங்குங்கள்",
    watchDemo: "டெமோவைப் பாருங்கள்",
    home: "முகப்பு", signIn: "உள்நுழை", createAccount: "கணக்கை உருவாக்கு", welcomeBack: "நல்வரவு",
    signInSub: "உங்கள் கற்றல் பயணத்தைத் தொடர உள்நுழையவும்.", email: "✉️ மின்னஞ்சல் முகவரி", password: "🔒 கடவுச்சொல்", fullName: "👤 முழு பெயர்", or: "அல்லது",
    googleSignIn: "கூகிள் மூலம் தொடரவும்", newHere: "புதியவரா?", alreadyHaveAccount: "ஏற்கனவே கணக்கு உள்ளதா?", landingTitle: "AI மூலம் எழுத்தறிவு மேம்பாடு",
    landingTitleLine1: "எழுத்தறிவு மேம்பாடு", landingTitleLine2: "AI நுண்ணறிவின் மூலம்",
    landingSub: "பெரியவர்கள் மற்றும் প্রথম தலைமுறை கற்பவர்கள் பிராந்திய மொழிகளில் அடிப்படை வாசிப்பு, எழுதுதல் மற்றும் பேசும் திறன்களைப் பெற உதவும் வகையில் வடிவமைக்கப்பட்ட தனிப்பயனாக்கப்பட்ட கற்றல் துணை.",
    getStarted: "தொடங்குங்கள்", registerTitle: "உங்கள் கணக்கை உருவாக்கவும்", registerSub: "எங்கள் சமூகத்தில் இணைந்து உங்கள் கற்றல் எல்லையை விரிவுபடுத்துங்கள்.",
    languageLabel: "🌐 விருப்பமான தாய்மொழி", registerLeftTitle: "உங்கள் எழுத்தறிவு பயணம் இங்கே தொடங்குகிறது.",
    registerLeftSub: "குரல் பயிற்சி மதிப்பீடுகள், நிகழ்நேர கருத்து மற்றும் தினசரி வாసిப்பு பாடங்களை அணுக ஒரு சுயவிவரத்தை உருவாக்கவும்.",
    loginLeftTitle: "நீங்கள் கற்கும் ஒவ்வொரு வார்த்தையும் ஒரு புதிய கதவைத் திறக்கிறது.", loginLeftSub: "தனிப்பயனாக்கப்பட்ட வாசிப்பு, எழுதுதல் மற்றும் பேசும் பயிற்சி — உங்கள் சொந்த மொழியில், உங்கள் சொந்த வேகத்தில்.",
    dashboardTitle: "உங்கள் டாஷ்போர்டிற்கு வரவேற்கிறோம்!", logout: "வெளியேறு"
  },
  gujarati: {
    ourApproachBadge: "અમારો અભિગમ",
    whyWeBuiltTitle: "અમે શા માટે બનાવ્યું",
    whyWeBuiltHighlight: "સાક્ષર",
    approachSubtitle: "પ્લેટફોર્મ પર દરેક પાઠ અને પ્રતિસાદને આકાર આપતા ચાર વિશ્વાસ.",
    literacyGapTitle: "સાક્ષરતાનો તફાવત માનવીય છે",
    literacyGapBody: "લાખો પુખ્ત વયના લોકો મુક્તપણે બોલે છે પરંતુ તેમને ક્યારેય આત્મવિશ્વાસથી વાંચતા કે લખતા શીખવવામાં આવ્યું નથી. આ ટેકનોલોજીની સમસ્યા નથી — તે ધીરજ સાથે ડિઝાઇન કરવાની માનવીય સમસ્યા છે.",
    oneSizeFitsTitle: "એક માપ બધા માટે યોગ્ય નથી",
    oneSizeFitsBody: "સાક્ષર ટૂંકા મૂલ્યાંકન સાથે શરૂ થાય છે અને શીખનારની પોતાની ગતિ, ભાષા અને સ્તરને અનુરૂપ માર્ગ બનાવે છે.",
    aiListensTitle: "પાછું સાંભળતું AI",
    aiListensBody: "રીઅલ-ટાઇમ ઉચ્ચારણ પ્રતિસાદ અને અક્ષર ટ્રેસિંગ નિષ્ક્રિય પાઠને દ્વિ-માર્ગી વાર્તાલાપમાં ફેરવે છે.",
    fluencyMotherTitle: "માતૃભાષામાં પ્રવાહ",
    fluencyMotherBody: "તમે જે ભાષામાં સ્વપ્ન જુઓ છો તેમાં શીખવું સૌથી ઊંડું ઉતરે છે. સાક્ષર 20+ ભારતીય પ્રાદેશિક ભાષાઓમાં શીખવે છે.",
    thePlatformBadge: "પ્લેટફોર્મ",
    platformTitle: "દરેક શીખનારને અનુકૂળ થતો વર્ગખંડ",
    platformSubtitle: "વાંચન, લેખન અને બોલવાનું કૌશલ્ય બનાવવા માટે ત્રણ બુદ્ધિશાળી મોડ્યુલ એકસાથે કામ કરે છે.",
    mod1Tag: "01 / વાંચન",
    mod1Title: "ઇન્ટરેક્ટિવ વાંચન",
    mod1Desc: "દૈનિક સ્થાનિક કાર્યોની આસપાસ બનાવેલ કસ્ટમ કન્ટેન્ટ ડેક.",
    mod2Tag: "02 / લેખન",
    mod2Title: "રીઅલ-ટાઇમ ટ્રેસિંગ",
    mod2Desc: "સ્ક્રીન પર અક્ષરો ટ્રેસ કરો અને સુધારણા મેળવો.",
    mod3Tag: "03 / બોલવું",
    mod3Title: "વોઇસ વેરિફિકેશન",
    mod3Desc: "મોટેથી બોલો અને સાંભળો કે તમે કેટલા સચોટ છો.",
    stat1Label: "પ્રાદેશિક ભાષાઓ",
    stat2Label: "ઉચ્ચાર સચોટતા",
    stat3Label: "શીખનારા જોડાયા",
    stat4Label: "સાક્ષરતા મોડ્યુલ્સ",
    aiCompanionBadge: "AI સાક્ષરતા સાથી",
    voiceDetectorLabel: "AI વોઇસ ભાષા પસંદગીકાર",
    listening: "સાંભળી રહ્યું છે…",
    voiceListeningPrompt: "તમારી માતૃભાષામાં બોલો…",
    detectedLabel: "ઓળખાયેલ",
    tryLiveDemo: "લાઇવ ડેમો અજમાવો",
    voiceAiLabel: "વોઇસ AI",
    tracingLabel: "ટ્રેસિંગ",
    scrollLabel: "સ્ક્રોલ કરો",
    micBtnTooltip: "માઇક પર ક્લિક કરો અને બોલો!",
    secReading: "વાંચન",
    secWriting: "લેખન",
    secSpeaking: "બોલવું",
    secReasoning: "તર્ક",
    langHindi: "હિન્દી",
    langTamil: "તમિલ",
    langBengali: "બંગાળી",
    ourApproachBadge: "અમારો અભિગમ",
    whyWeBuiltTitle: "અમે શા માટે બનાવ્યું",
    whyWeBuiltHighlight: "સાક્ષર",
    approachSubtitle: "પ્લેટફોર્મ પર દરેક પાઠ અને પ્રતિસાદને આકાર આપતા ચાર વિશ્વાસ.",
    literacyGapTitle: "સાક્ષરતાનો તફાવત માનવીય છે",
    literacyGapBody: "લાખો પુખ્ત વયના લોકો મુક્તપણે બોલે છે પરંતુ તેમને ક્યારેય આત્મવિશ્વાસથી વાંચતા કે લખતા શીખવવામાં આવ્યું નથી. આ ટેકનોલોજીની સમસ્યા નથી — તે ધીરજ સાથે ડિઝાઇન કરવાની માનવીય સમસ્યા છે.",
    oneSizeFitsTitle: "એક માપ બધા માટે યોગ્ય નથી",
    oneSizeFitsBody: "સાક્ષર ટૂંકા મૂલ્યાંકન સાથે શરૂ થાય છે અને શીખનારની પોતાની ગતિ, ભાષા અને સ્તરને અનુરૂપ માર્ગ બનાવે છે.",
    aiListensTitle: "પાછું સાંભળતું AI",
    aiListensBody: "રીઅલ-ટાઇમ ઉચ્ચારણ પ્રતિસાદ અને અક્ષર ટ્રેસિંગ નિષ્ક્રિય પાઠને દ્વિ-માર્ગી વાર્તાલાપમાં ફેરવે છે.",
    fluencyMotherTitle: "માતૃભાષામાં પ્રવાહ",
    fluencyMotherBody: "તમે જે ભાષામાં સ્વપ્ન જુઓ છો તેમાં શીખવું સૌથી ઊંડું ઉતરે છે. સાક્ષર 20+ ભારતીય પ્રાદેશિક ભાષાઓમાં શીખવે છે.",
    thePlatformBadge: "પ્લેટફોર્મ",
    platformTitle: "દરેક શીખનારને અનુકૂળ થતો વર્ગખંડ",
    platformSubtitle: "વાંચન, લેખન અને બોલવાનું કૌશલ્ય બનાવવા માટે ત્રણ બુદ્ધિશાળી મોડ્યુલ એકસાથે કામ કરે છે.",
    mod1Tag: "01 / વાંચન",
    mod1Title: "ઇન્ટરેક્ટિવ વાંચન",
    mod1Desc: "દૈનિક સ્થાનિક કાર્યોની આસપાસ બનાવેલ કસ્ટમ કન્ટેન્ટ ડેક.",
    mod2Tag: "02 / લેખન",
    mod2Title: "રીઅલ-ટાઇમ ટ્રેસિંગ",
    mod2Desc: "સ્ક્રીન પર અક્ષરો ટ્રેસ કરો અને સુધારણા મેળવો.",
    mod3Tag: "03 / બોલવું",
    mod3Title: "વોઇસ વેરિફિકેશન",
    mod3Desc: "મોટેથી બોલો અને સાંભળો કે તમે કેટલા સચોટ છો.",
    stat1Label: "પ્રાદેશિક ભાષાઓ",
    stat2Label: "ઉચ્ચાર સચોટતા",
    stat3Label: "શીખનારા જોડાયા",
    stat4Label: "સાક્ષરતા મોડ્યુલ્સ",
    beginYourJourney: "તમારી યાત્રા શરૂ કરો",
    ctaHeadlineLine1: "તમે શીખો છો તે દરેક શબ્દ",
    ctaHeadlineLine2: "એક નવો દરવાજો ખોલે છે.",
    getStartedFree: "મફતમાં શરૂ કરો",
    watchDemo: "ડેમો જુઓ",
    home: "હોમ", signIn: "સાઇન ઇન", createAccount: "ખાતું બનાવો", welcomeBack: "સ્વાગત છે",
    signInSub: "તમારી શીખવાની યાત્રા ચાલુ રાખવા માટે साઇન ઇન કરો.", email: "✉️ ઇમેઇલ સરનામું", password: "🔒 પાસવર્ડ", fullName: "👤 પૂરું નામ", or: "અથวา",
    googleSignIn: "ગુગલ સાથે ચાલુ રાખો", newHere: "અહીં નવા છો?", alreadyHaveAccount: "પહેલેથી ખાતું છે?", landingTitle: "AI દ્વારા સાક્ષરતા સશક્તિકરણ",
    landingTitleLine1: "સાક્ષરતા સશક્તિકરણ", landingTitleLine2: "AI બુદ્ધિ દ્વારા",
    landingSub: "એક વ્યક્તિગત શિક્ષણ સાથી જે પુખ્ત वયના લોકો અને પ્રથમ પેઢીના શીખનારાઓને પ્રાદેશિક ભાષાઓમાં પાયાના વાંચન, લેખન અને બોલવાના કૌશલ્યો પ્રાપ્ત કરવામાં મદદ કરવા માટે રચાયેલ છે.",
    getStarted: "શરૂ કરો", registerTitle: "તમારું ખાતું બનાવો", registerSub: "અમારા સમુદાયમાં જોડાઓ અને તમારી શીખવાની ક્ષિતિજોનો વિસ્તાર કરો.",
    languageLabel: "🌐 પસંદગીની માતૃભાષા", registerLeftTitle: "તમારી સાક્ષરતાની સફર અહીંથી શરૂ થાય છે.",
    registerLeftSub: "વોઇસ પ્રેક્ટિસ એસેસમેન્ટ્સ, રીઅલ-ટાઇમ ફીડબેક અને દૈનિક વાંચન પાઠોને અનલૉક કરવા માટે એક પ્રોફાઇલ બનાવો.",
    loginLeftTitle: "તમે શીખો છો તે દરેક શબ્દ એક નવો દરવાજો ખોલે છે.", loginLeftSub: "ব্যক্তিগত વાંચન, લેખન અને બોલવાની પ્રેક્ટિસ — તમારી પોતાની ભાષામાં, તમારી પોતાની ગતિએ.",
    dashboardTitle: "તમારા ડેશબોર્ડમાં સ્વાગત છે!", logout: "લોગ આઉट"
  },
  kannada: {
    ourApproachBadge: "ನಮ್ಮ ವಿಧಾನ",
    whyWeBuiltTitle: "ನಾವು ಏಕೆ ನಿರ್ಮಿಸಿದೆವು",
    whyWeBuiltHighlight: "ಸಾಕ್ಷರ್",
    approachSubtitle: "ವೇದಿಕೆಯಲ್ಲಿನ ಪ್ರತಿಯೊಂದು ಪಾಠ, ಪ್ರತಿಯೊಂದು ಪ್ರಾಂಪ್ಟ್ ಮತ್ತು ಪ್ರತಿಕ್ರಿಯೆಯನ್ನು ರೂಪಿಸುವ ನಾಲ್ಕು ನಂಬಿಕೆಗಳು.",
    literacyGapTitle: "ಸಾಕ್ಷರತೆಯ ಅಂತರವು ಮಾನವೀಯವಾಗಿದೆ",
    literacyGapBody: "ಲಕ್ಷಾಂತರ ವಯಸ್ಕರು ಸರಾಗವಾಗಿ ಮಾತನಾಡುತ್ತಾರೆ ಆದರೆ ಅವರಿಗೆ ಓದಲು ಅಥವಾ ಬರೆಯಲು ಎಂದಿಗೂ ಕಲಿಸಲಾಗಿಲ್ಲ. ಇದು ತಂತ್ರಜ್ಞಾನದ ಸಮಸ್ಯೆಯಲ್ಲ — ತಾಳ್ಮೆ ಮತ್ತು ಘನತೆಯಿಂದ ವಿನ್ಯಾಸಗೊಳಿಸಬೇಕಾದ ಮಾನವೀಯ ಸಮಸ್ಯೆ.",
    oneSizeFitsTitle: "ಒಂದೇ ಗಾತ್ರ ಎಲ್ಲರಿಗೂ ಹೊಂದುವುದಿಲ್ಲ",
    oneSizeFitsBody: "ಪಾರಂಪರಿಕ ತರಗತಿಗಳು ಆರಂಭಿಕ ಬಿಂದುವನ್ನು ಊಹಿಸುತ್ತವೆ. ಸಾಕ್ಷರ್ ಸಣ್ಣ ಮೌಲ್ಯಮಾಪನದೊಂದಿಗೆ ಪ್ರಾರಂಭವಾಗುತ್ತದೆ ಮತ್ತು ಕಲಿಯುವವರ ಸ್ವಂತ ವೇಗ, ಭಾಷೆ ಮತ್ತು ಮಟ್ಟಕ್ಕೆ ತಕ್ಕಂತೆ ಮಾರ್ಗವನ್ನು ರೂಪಿಸುತ್ತದೆ.",
    aiListensTitle: "ಮರಳಿ ಕೇಳುವ AI",
    aiListensBody: "ನೈಜ-ಸಮಯದ ಉಚ್ಚಾರಣೆ ಪ್ರತಿಕ್ರಿಯೆ ಮತ್ತು ಅಕ್ಷರ ಟ್ರೇಸಿಂಗ್ ನಿಷ್ಕ್ರಿಯ ಪಾಠಗಳನ್ನು ದ್ವಿಮುಖ ಸಂಭಾಷಣೆಯಾಗಿ ಮಾರ್ಪಡಿಸುತ್ತವೆ.",
    fluencyMotherTitle: "ಮಾತೃಭಾಷೆಯಲ್ಲಿ ನೈಪುಣ್ಯತೆ",
    fluencyMotherBody: "ನೀವು ಕನಸು ಕಾಣುವ ಭಾಷೆಯಲ್ಲಿ ಕಲಿಕೆಯು ಆಳವಾಗಿ ಇಳಿಯುತ್ತದೆ. ಸಾಕ್ಷರ್ 20+ ಭಾರತೀಯ ಪ್ರಾದೇಶಿಕ ಭಾಷೆಗಳಲ್ಲಿ ಬೋಧಿಸುತ್ತದೆ.",
    thePlatformBadge: "ವೇದಿಕೆ",
    platformTitle: "ಪ್ರತಿಯೊಬ್ಬ ಕಲಿಯುವವರಿಗೂ ಹೊಂದುವ ತರಗತಿ",
    platformSubtitle: "ಮೂರು ಬುದ್ಧಿವಂತ ಮಾಡ್ಯೂಲ್‌ಗಳು ಓದುವಿಕೆ, ಬರವಣಿಗೆ ಮತ್ತು ಮಾತನಾಡುವುದನ್ನು ನಿರ್ಮಿಸಲು ಒಟ್ಟಾಗಿ ಕೆಲಸ ಮಾಡುತ್ತವೆ.",
    mod1Tag: "01 / ಓದುವಿಕೆ",
    mod1Title: "ಸಂವಾದಾತ್ಮಕ ಓದುವಿಕೆ",
    mod1Desc: "ದೈನಂದಿನ ಸ್ಥಳೀಯ ಕಾರ್ಯಗಳ ಸುತ್ತ ನಿರ್ಮಿಸಲಾದ ಕಸ್ಟಮ್ ವಿಷಯ ಡೆಕ್‌ಗಳು.",
    mod2Tag: "02 / ಬರವಣಿಗೆ",
    mod2Title: "ನೈಜ-ಸಮಯದ ಟ್ರೇಸಿಂಗ್",
    mod2Desc: "ಪರದೆಯ ಮೇಲೆ ಅಕ್ಷರಗಳನ್ನು ಟ್ರೇಸ್ ಮಾಡಿ ಮತ್ತು ಪಾರ್ಶ್ವದ ತಿದ್ದುಪಡಿಯನ್ನು ಪಡೆಯಿರಿ.",
    mod3Tag: "03 / ಮಾತನಾಡುವುದು",
    mod3Title: "ಧ್ವನಿ ಪರಿಶೀಲನೆ",
    mod3Desc: "ಗಟ್ಟಿಯಾಗಿ ಮಾತನಾಡಿ ಮತ್ತು ಉಚ್ಚಾರಣೆಯ ನಿಖರತೆಯನ್ನು ಆಲಿಸಿ.",
    stat1Label: "ಪ್ರಾದೇಶಿಕ ಭಾಷೆಗಳು",
    stat2Label: "ಉಚ್ಚಾರಣೆ ನಿಖರತೆ",
    stat3Label: "ಸೇರ್ಪಡೆಯಾದ ಕಲಿಯುವವರು",
    stat4Label: "ಸಾಕ್ಷರತಾ ಮಾಡ್ಯೂಲ್‌ಗಳು",
    aiCompanionBadge: "AI ಸಾಕ್ಷರತಾ ಒಡನಾಡಿ",
    voiceDetectorLabel: "AI ಧ್ವನಿ ಭಾಷಾ ಆಯ್ಕೆಗಾರ",
    listening: "ಕೇಳುತ್ತಿದೆ…",
    voiceListeningPrompt: "ನಿಮ್ಮ ಮಾತೃಭಾಷೆಯಲ್ಲಿ ಮಾತನಾಡಿ…",
    detectedLabel: "ಗುರುತಿಸಲಾಗಿದೆ",
    tryLiveDemo: "ಲೈವ್ ಡೆಮೊ ಪ್ರಯತ್ನಿಸಿ",
    voiceAiLabel: "ಧ್ವನಿ AI",
    tracingLabel: "ಟ್ರೇಸಿಂಗ್",
    scrollLabel: "ಸ್ಕ್ರೋಲ್ ಮಾಡಿ",
    micBtnTooltip: "ಮೈಕ್ ಒತ್ತಿ ಮಾತನಾಡಿ!",
    secReading: "ಓದುವಿಕೆ",
    secWriting: "ಬರವಣಿಗೆ",
    secSpeaking: "ಮಾತನಾಡುವುದು",
    secReasoning: "ತರ್ಕ",
    langHindi: "ಹಿಂದಿ",
    langTamil: "ತಮಿಳು",
    langBengali: "ಬಂಗಾಳಿ",
    ourApproachBadge: "ನಮ್ಮ ವಿಧಾನ",
    whyWeBuiltTitle: "ನಾವು ಏಕೆ ನಿರ್ಮಿಸಿದೆವು",
    whyWeBuiltHighlight: "ಸಾಕ್ಷರ್",
    approachSubtitle: "ವೇದಿಕೆಯಲ್ಲಿನ ಪ್ರತಿಯೊಂದು ಪಾಠ, ಪ್ರತಿಯೊಂದು ಪ್ರಾಂಪ್ಟ್ ಮತ್ತು ಪ್ರತಿಕ್ರಿಯೆಯನ್ನು ರೂಪಿಸುವ ನಾಲ್ಕು ನಂಬಿಕೆಗಳು.",
    literacyGapTitle: "ಸಾಕ್ಷರತೆಯ ಅಂತರವು ಮಾನವೀಯವಾಗಿದೆ",
    literacyGapBody: "ಲಕ್ಷಾಂತರ ವಯಸ್ಕರು ಸರಾಗವಾಗಿ ಮಾತನಾಡುತ್ತಾರೆ ಆದರೆ ಅವರಿಗೆ ಓದಲು ಅಥವಾ ಬರೆಯಲು ಎಂದಿಗೂ ಕಲಿಸಲಾಗಿಲ್ಲ. ಇದು ತಂತ್ರಜ್ಞಾನದ ಸಮಸ್ಯೆಯಲ್ಲ — ತಾಳ್ಮೆ ಮತ್ತು ಘನತೆಯಿಂದ ವಿನ್ಯಾಸಗೊಳಿಸಬೇಕಾದ ಮಾನವೀಯ ಸಮಸ್ಯೆ.",
    oneSizeFitsTitle: "ಒಂದೇ ಗಾತ್ರ ಎಲ್ಲರಿಗೂ ಹೊಂದುವುದಿಲ್ಲ",
    oneSizeFitsBody: "ಪಾರಂಪರಿಕ ತರಗತಿಗಳು ಆರಂಭಿಕ ಬಿಂದುವನ್ನು ಊಹಿಸುತ್ತವೆ. ಸಾಕ್ಷರ್ ಸಣ್ಣ ಮೌಲ್ಯಮಾಪನದೊಂದಿಗೆ ಪ್ರಾರಂಭವಾಗುತ್ತದೆ ಮತ್ತು ಕಲಿಯುವವರ ಸ್ವಂತ ವೇಗ, ಭಾಷೆ ಮತ್ತು ಮಟ್ಟಕ್ಕೆ ತಕ್ಕಂತೆ ಮಾರ್ಗವನ್ನು ರೂಪಿಸುತ್ತದೆ.",
    aiListensTitle: "ಮರಳಿ ಕೇಳುವ AI",
    aiListensBody: "ನೈಜ-ಸಮಯದ ಉಚ್ಚಾರಣೆ ಪ್ರತಿಕ್ರಿಯೆ ಮತ್ತು ಅಕ್ಷರ ಟ್ರೇಸಿಂಗ್ ನಿಷ್ಕ್ರಿಯ ಪಾಠಗಳನ್ನು ದ್ವಿಮುಖ ಸಂಭಾಷಣೆಯಾಗಿ ಮಾರ್ಪಡಿಸುತ್ತವೆ.",
    fluencyMotherTitle: "ಮಾತೃಭಾಷೆಯಲ್ಲಿ ನೈಪುಣ್ಯತೆ",
    fluencyMotherBody: "ನೀವು ಕನಸು ಕಾಣುವ ಭಾಷೆಯಲ್ಲಿ ಕಲಿಕೆಯು ಆಳವಾಗಿ ಇಳಿಯುತ್ತದೆ. ಸಾಕ್ಷರ್ 20+ ಭಾರತೀಯ ಪ್ರಾದೇಶಿಕ ಭಾಷೆಗಳಲ್ಲಿ ಬೋಧಿಸುತ್ತದೆ.",
    thePlatformBadge: "ವೇದಿಕೆ",
    platformTitle: "ಪ್ರತಿಯೊಬ್ಬ ಕಲಿಯುವವರಿಗೂ ಹೊಂದುವ ತರಗತಿ",
    platformSubtitle: "ಮೂರು ಬುದ್ಧಿವಂತ ಮಾಡ್ಯೂಲ್‌ಗಳು ಓದುವಿಕೆ, ಬರವಣಿಗೆ ಮತ್ತು ಮಾತನಾಡುವುದನ್ನು ನಿರ್ಮಿಸಲು ಒಟ್ಟಾಗಿ ಕೆಲಸ ಮಾಡುತ್ತವೆ.",
    mod1Tag: "01 / ಓದುವಿಕೆ",
    mod1Title: "ಸಂವಾದಾತ್ಮಕ ಓದುವಿಕೆ",
    mod1Desc: "ದೈನಂದಿನ ಸ್ಥಳೀಯ ಕಾರ್ಯಗಳ ಸುತ್ತ ನಿರ್ಮಿಸಲಾದ ಕಸ್ಟಮ್ ವಿಷಯ ಡೆಕ್‌ಗಳು.",
    mod2Tag: "02 / ಬರವಣಿಗೆ",
    mod2Title: "ನೈಜ-ಸಮಯದ ಟ್ರೇಸಿಂಗ್",
    mod2Desc: "ಪರದೆಯ ಮೇಲೆ ಅಕ್ಷರಗಳನ್ನು ಟ್ರೇಸ್ ಮಾಡಿ ಮತ್ತು ಪಾರ್ಶ್ವದ ತಿದ್ದುಪಡಿಯನ್ನು ಪಡೆಯಿರಿ.",
    mod3Tag: "03 / ಮಾತನಾಡುವುದು",
    mod3Title: "ಧ್ವನಿ ಪರಿಶೀಲನೆ",
    mod3Desc: "ಗಟ್ಟಿಯಾಗಿ ಮಾತನಾಡಿ ಮತ್ತು ಉಚ್ಚಾರಣೆಯ ನಿಖರತೆಯನ್ನು ಆಲಿಸಿ.",
    stat1Label: "ಪ್ರಾದೇಶಿಕ ಭಾಷೆಗಳು",
    stat2Label: "ಉಚ್ಚಾರಣೆ ನಿಖರತೆ",
    stat3Label: "ಸೇರ್ಪಡೆಯಾದ ಕಲಿಯುವವರು",
    stat4Label: "ಸಾಕ್ಷರತಾ ಮಾಡ್ಯೂಲ್‌ಗಳು",
    beginYourJourney: "ನಿಮ್ಮ ಪ್ರಯಾಣವನ್ನು ಪ್ರಾರಂಭಿಸಿ",
    ctaHeadlineLine1: "ನೀವು ಕಲಿಯುವ ಪ್ರತಿಯೊಂದು ಪದವೂ",
    ctaHeadlineLine2: "ಹೊಸ ಬಾಗಿಲನ್ನು ತೆರೆಯುತ್ತದೆ.",
    getStartedFree: "ಉಚಿತವಾಗಿ ಪ್ರಾರಂಭಿಸಿ",
    watchDemo: "ಡೆಮೊ ವೀಕ್ಷಿಸಿ",
    home: "ಹೋಮ್", signIn: "ಸೈನ್ ಇನ್", createAccount: "ಖಾತೆ ರಚಿಸಿ", welcomeBack: "ಸ್ವಾಗತ",
    signInSub: "ನಿಮ್ಮ ಕಲಿಕೆಯ ಪ್ರಯಾಣವನ್ನು ಮುಂದುವರಿಸಲು ಸೈನ್ ಇನ್ ಮಾಡಿ.", email: "✉️ ಇಮೇಲ್ ವಿಳಾಸ", password: "🔒 ಪಾಸ್‌ವರ್ಡ್", fullName: "👤 ಪೂರ್ಣ ಹೆಸರು", or: "ಅಥವಾ",
    googleSignIn: "ಗೂಗಲ್‌ನೊಂದಿಗೆ ಮುಂದುವರಿಯಿರಿ", newHere: "ಇಲ್ಲಿ ಹೊಸಬರೇ?", alreadyHaveAccount: "ಈಗಾಗಲೇ ಖಾತೆ ಹೊಂದಿದ್ದೀರಾ?", landingTitle: "AI ಮೂಲಕ ಸಾಕ್ಷರತೆಯ ಸಬಲೀಕರಣ",
    landingTitleLine1: "ಸಾಕ್ಷರತೆಯ ಸಬಲೀಕರಣ", landingTitleLine2: "AI ಬುದ್ಧಿಮತ್ತೆ ಮೂಲಕ",
    landingSub: "ವಯಸ್ಕರು ಮತ್ತು ಮೊದಲ ತಲೆಮಾರಿನ ಕಲಿಯುವವರಿಗೆ ಪ್ರಾದೇಶಿಕ ಭಾಷೆಗಳಲ್ಲಿ ಮೂಲಭೂತ ಓದುವಿಕೆ, ಬರವಣಿಗೆ ಮತ್ತು ಮಾತನಾಡುವ ಕೌಶಲ್ಯಗಳನ್ನು ಪಡೆಯಲು ಸಹಾಯ ಮಾಡಲು ವಿನ್ಯಾಸಗೊಳಿಸಲಾದ ವೈಯಕ್ಕೀಕರಿಸಿದ ಕಲಿಕೆಯ ಒಡನಾಡಿ.",
    getStarted: "ಪ್ರಾರಂಭಿಸಿ", registerTitle: "ನಿಮ್ಮ ಖಾತೆಯನ್ನು ರಚಿಸಿ", registerSub: "ನಮ್ಮ ಸಮುದಾಯಕ್ಕೆ ಸೇರಿ ಮತ್ತು ನಿಮ್ಮ ಕಲಿಕೆಯ ಪರಿಧಿಯನ್ನು ವಿಸ್ತರಿಸಿ.",
    languageLabel: "🌐 ಆದ್ಯತೆಯ ಮಾತೃಭಾಷೆ", registerLeftTitle: "ನಿಮ್ಮ ಸಾಕ್ಷರತೆಯ ಪ್ರಯಾಣ ಇಲ್ಲಿಂದ ಪ್ರಾರಂಭವಾಗುತ್ತದೆ.",
    registerLeftSub: "ಧ್ವನಿ ಅಭ್ಯಾಸ ಮೌಲ್ಯಮಾಪನಗಳು, ನೈಜ-ಸಮಯದ ಪ್ರತಿಕ್ರಿಯೆ ಮತ್ತು ದೈನಂದิน ಓದುವ ಪಾಠಗಳನ್ನು ಅನ್ಲಾಕ್ ಮಾಡಲು ಪ್ರೊಫೈಲ್ ರಚಿಸಿ.",
    loginLeftTitle: "ನೀವು ಕಲಿಯುವ ಪ್ರತಿಯೊಂದು ಪದವೂ ಹೊಸ ಬಾಗಿಲನ್ನು ತೆರೆಯುತ್ತದೆ.", loginLeftSub: "ವೈಯಕ್ಕೀಕರಿಸಿದ ಓದುವಿಕೆ, ಬರವಣಿಗೆ ಮತ್ತು ಮಾತನಾಡುವ ಅಭ್ಯಾಸ — ನಿಮ್ಮದೇ ಭಾಷೆಯಲ್ಲಿ, ನಿಮ್ಮದೇ ವೇಗದಲ್ಲಿ.",
    dashboardTitle: "ನಿಮ್ಮ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್‌ಗೆ ಸ್ವಾಗತ!", logout: "ಲಾಗ್ ಔಟ್"
  },
  malayalam: {
    ourApproachBadge: "ഞങ്ങളുടെ സമീപനം",
    whyWeBuiltTitle: "ഞങ്ങൾ എന്തുകൊണ്ട് നിർമ്മിച്ചു",
    whyWeBuiltHighlight: "സാക്ഷർ",
    approachSubtitle: "പ്ലാറ്റ്‌ഫോമിലെ ഓരോ പാഠത്തെയും അഭിപ്രായങ്ങളെയും രൂപപ്പെടുത്തുന്ന നാല് വിശ്വാസങ്ങൾ.",
    literacyGapTitle: "സാക്ഷരതാ വിടവ് മാനവികമാണ്",
    literacyGapBody: "ദശലക്ഷക്കണക്കിന് മുതിർന്നവർ നന്നായി സംസാരിക്കുന്നുവെങ്കിലും ആത്മവിശ്വാസത്തോടെ വായിക്കാനോ എഴുതാനോ ഒരിക്കലും പഠിപ്പിച്ചിട്ടില്ല. ഇത് ഒരു സാങ്കേതിക പ്രശ്നമല്ല — ക്ഷമയോടെ രൂപകൽപ്പന ചെയ്യേണ്ട മാനുഷിക പ്രശ്നമാണ്.",
    oneSizeFitsTitle: "ഒരു അളവ് എല്ലാവർക്കും യോജിക്കില്ല",
    oneSizeFitsBody: "സാക്ഷർ ഒരു ചെറിയ വിലയിരുത്തലോടെ ആരംഭിക്കുകയും പഠിതാവിന്റെ സ്വന്തം വേഗതയ്ക്കും ഭാഷയ്ക്കും തലത്തിനും അനുയോജ്യമായ പാത രൂപപ്പെടുത്തുകയും ചെയ്യുന്നു.",
    aiListensTitle: "തിരികെ കേൾക്കുന്ന AI",
    aiListensBody: "തത്സമയ ഉച്ചാരണ ഫീഡ്‌ബാക്കും അക്ഷര ട്രെയ്‌സിംഗും പഠനത്തെ ഉഭയകക്ഷി സംഭാഷണമാക്കി മാറ്റുന്നു.",
    fluencyMotherTitle: "മാതൃഭാഷയിലെ പ്രാവീണ്യം",
    fluencyMotherBody: "നിങ്ങൾ സ്വപ്നം കാണുന്ന ഭാഷയിലാണ് പഠനം ഏറ്റവും ആഴത്തിൽ എത്തുന്നത്. സാക്ഷർ 20-ലധികം പ്രാദേശിക ഭാഷകളിൽ പഠിപ്പിക്കുന്നു.",
    thePlatformBadge: "പ്ലാറ്റ്‌ഫോം",
    platformTitle: "ഓരോ പഠിതാവിനും അനുയോജ്യമായ ക്ലാസ് റൂം",
    platformSubtitle: "വായന, എഴുത്ത്, സംസാരം എന്നിവ കെട്ടിപ്പടുക്കാൻ മൂന്ന് ബുദ്ധിപരമായ മൊഡ്യൂളുകൾ ഒരുമിച്ച് പ്രവർത്തിക്കുന്നു.",
    mod1Tag: "01 / വായന",
    mod1Title: "ഇന്ററാക്ടീവ് വായന",
    mod1Desc: "ദൈനംദിന പ്രാദേശിക ജോലികളെ അടിസ്ഥാനമാക്കി നിർമ്മിച്ച ഉള്ളടക്കം.",
    mod2Tag: "02 / എഴുത്ത്",
    mod2Title: "തത്സമയ ട്രെയ്‌സിംഗ്",
    mod2Desc: "സ്‌ക്രീനിൽ അക്ഷരങ്ങൾ വരച്ച് തിരുത്തലുകൾ നേടുക.",
    mod3Tag: "03 / സംസാരം",
    mod3Title: "ശബ്ദ പരിശോധന",
    mod3Desc: "ഉച്ചത്തിൽ സംസാരിച്ച് നിങ്ങളുടെ ഉച്ചാരണം എത്ര കൃത്യമാണെന്ന് കേൾക്കുക.",
    stat1Label: "പ്രാദേശിക ഭാഷകൾ",
    stat2Label: "ഉച്ചാരണ കൃത്യത",
    stat3Label: "പഠിതാക്കൾ ചേർന്നു",
    stat4Label: "സാക്ഷരതാ മൊഡ്യൂളുകൾ",
    aiCompanionBadge: "AI സാക്ഷരതാ കൂട്ടാളി",
    voiceDetectorLabel: "AI വോയ്‌സ് ഭാഷാ സെലക്ടർ",
    listening: "കേൾക്കുന്നു…",
    voiceListeningPrompt: "നിങ്ങളുടെ മാതൃഭാഷയിൽ സംസാരിക്കുക…",
    detectedLabel: "കണ്ടെത്തി",
    tryLiveDemo: "ലൈവ് ഡെമോ ശ്രമിക്കുക",
    voiceAiLabel: "വോയ്‌സ് AI",
    tracingLabel: "ട്രെയ്‌സിംഗ്",
    scrollLabel: "സ്ക്രോൾ ചെയ്യുക",
    micBtnTooltip: "മൈക്കിൽ ക്ലിക്ക് ചെയ്ത് സംസാരിക്കുക!",
    secReading: "വായന",
    secWriting: "എഴുത്ത്",
    secSpeaking: "സംസാരം",
    secReasoning: "ചിന്ത",
    langHindi: "ഹിന്ദി",
    langTamil: "തമിഴ്",
    langBengali: "ബംഗാളി",
    ourApproachBadge: "ഞങ്ങളുടെ സമീപനം",
    whyWeBuiltTitle: "ഞങ്ങൾ എന്തുകൊണ്ട് നിർമ്മിച്ചു",
    whyWeBuiltHighlight: "സാക്ഷർ",
    approachSubtitle: "പ്ലാറ്റ്‌ഫോമിലെ ഓരോ പാഠത്തെയും അഭിപ്രായങ്ങളെയും രൂപപ്പെടുത്തുന്ന നാല് വിശ്വാസങ്ങൾ.",
    literacyGapTitle: "സാക്ഷരതാ വിടവ് മാനവികമാണ്",
    literacyGapBody: "ദശലക്ഷക്കണക്കിന് മുതിർന്നവർ നന്നായി സംസാരിക്കുന്നുവെങ്കിലും ആത്മവിശ്വാസത്തോടെ വായിക്കാനോ എഴുതാനോ ഒരിക്കലും പഠിപ്പിച്ചിട്ടില്ല. ഇത് ഒരു സാങ്കേതിക പ്രശ്നമല്ല — ക്ഷമയോടെ രൂപകൽപ്പന ചെയ്യേണ്ട മാനുഷിക പ്രശ്നമാണ്.",
    oneSizeFitsTitle: "ഒരു അളവ് എല്ലാവർക്കും യോജിക്കില്ല",
    oneSizeFitsBody: "സാക്ഷർ ഒരു ചെറിയ വിലയിരുത്തലോടെ ആരംഭിക്കുകയും പഠിതാവിന്റെ സ്വന്തം വേഗതയ്ക്കും ഭാഷയ്ക്കും തലത്തിനും അനുയോജ്യമായ പാത രൂപപ്പെടുത്തുകയും ചെയ്യുന്നു.",
    aiListensTitle: "തിരികെ കേൾക്കുന്ന AI",
    aiListensBody: "തത്സമയ ഉച്ചാരണ ഫീഡ്‌ബാക്കും അക്ഷര ട്രെയ്‌സിംഗും പഠനത്തെ ഉഭയകക്ഷി സംഭാഷണമാക്കി മാറ്റുന്നു.",
    fluencyMotherTitle: "മാതൃഭാഷയിലെ പ്രാവീണ്യം",
    fluencyMotherBody: "നിങ്ങൾ സ്വപ്നം കാണുന്ന ഭാഷയിലാണ് പഠനം ഏറ്റവും ആഴത്തിൽ എത്തുന്നത്. സാക്ഷർ 20-ലധികം പ്രാദേശിക ഭാഷകളിൽ പഠിപ്പിക്കുന്നു.",
    thePlatformBadge: "പ്ലാറ്റ്‌ഫോം",
    platformTitle: "ഓരോ പഠിതാവിനും അനുയോജ്യമായ ക്ലാസ് റൂം",
    platformSubtitle: "വായന, എഴുത്ത്, സംസാരം എന്നിവ കെട്ടിപ്പടുക്കാൻ മൂന്ന് ബുദ്ധിപരമായ മൊഡ്യൂളുകൾ ഒരുമിച്ച് പ്രവർത്തിക്കുന്നു.",
    mod1Tag: "01 / വായന",
    mod1Title: "ഇന്ററാക്ടീവ് വായന",
    mod1Desc: "ദൈനംദിന പ്രാദേശിക ജോലികളെ അടിസ്ഥാനമാക്കി നിർമ്മിച്ച ഉള്ളടക്കം.",
    mod2Tag: "02 / എഴുത്ത്",
    mod2Title: "തത്സമയ ട്രെയ്‌സിംഗ്",
    mod2Desc: "സ്‌ക്രീനിൽ അക്ഷരങ്ങൾ വരച്ച് തിരുത്തലുകൾ നേടുക.",
    mod3Tag: "03 / സംസാരം",
    mod3Title: "ശബ്ദ പരിശോധന",
    mod3Desc: "ഉച്ചത്തിൽ സംസാരിച്ച് നിങ്ങളുടെ ഉച്ചാരണം എത്ര കൃത്യമാണെന്ന് കേൾക്കുക.",
    stat1Label: "പ്രാദേശിക ഭാഷകൾ",
    stat2Label: "ഉച്ചാരണ കൃത്യത",
    stat3Label: "പഠിതാക്കൾ ചേർന്നു",
    stat4Label: "സാക്ഷരതാ മൊഡ്യൂളുകൾ",
    beginYourJourney: "നിങ്ങളുടെ യാത്ര ആരംഭിക്കുക",
    ctaHeadlineLine1: "നിങ്ങൾ പഠിക്കുന്ന ഓരോ വാക്കും",
    ctaHeadlineLine2: "ഒരു പുതിയ വാതിൽ തുറക്കുന്നു.",
    getStartedFree: "സൗജന്യമായി ആരംഭിക്കുക",
    watchDemo: "ഡെമോ കാണുക",
    home: "ഹോം", signIn: "സൈൻ ഇൻ", createAccount: "അക്കൗണ്ട് സൃഷ്ടിക്കുക", welcomeBack: "സ്വാഗതം",
    signInSub: "നിങ്ങളുടെ പഠന യാത്ര തുടരാൻ സൈൻ ഇൻ ചെയ്യുക.", email: "✉️ ഇമെയിൽ വിലാസം", password: "🔒 പാസ്‌വേഡ്", fullName: "👤 പൂർണ്ണ നാമം", or: "അല്ലെങ്കിൽ",
    googleSignIn: "ഗൂഗിൾ ഉപയോഗിച്ച് തുടരുക", newHere: "പുതിയതാണോ?", alreadyHaveAccount: "നിലവിൽ അക്കൗണ്ട് ഉണ്ടോ?", landingTitle: "AI വഴിയുള്ള സാക്ഷരതാ ശാക്തീകരണം",
    landingTitleLine1: "സാക്ഷരതാ ശാക്തീകരണം", landingTitleLine2: "AI ബുദ്ധി വഴി",
    landingSub: "മുതിർന്നവർക്കും ആദ്യതലമുറ പഠിതാക്കൾക്കും പ്രാദേശിക ഭാഷകളിൽ അടിസ്ഥാന വായന, എഴുത്ത്, സംസാര കഴിവുകൾ എന്നിവ നേടിയെടുക്കാൻ സഹായിക്കുന്നതിനായി രൂപകൽപ്പന ചെയ്ത ഒരു വ്യക്തിഗത പഠന സഹായി.",
    getStarted: "ആരംഭിക്കുക", registerTitle: "ನಿങ്ങളുടെ അക്കൗണ്ട് സൃഷ്ടിക്കുക", registerSub: "ഞങ്ങളുടെ കമ്മ്യൂਣੀറ്റിയിൽ ചേരുക, നിങ്ങളുടെ പഠന ਚਕਰവാളങ്ങൾ വികസിപ്പിക്കുക.",
    languageLabel: "🌐 താൽപ്പര്യമുള്ള മാതൃഭാഷ", registerLeftTitle: "批准 സാക്ഷരതാ യാത്ര ഇവിടെ ആരംഭിക്കുന്നു.",
    registerLeftSub: "വോയ്‌സ് പ്രാക്ടീസ് അസസ്‌മെന്റുകൾ, തത്സമയ ഫീഡ്‌ബാക്ക്, വ്യക്തിഗതമാക്കിയ വായനാ പാഠങ്ങൾ എന്നിവ അൺലോക്ക് ചെയ്യാൻ ഒരു പ്രൊഫൈൽ സൃഷ്‌ടിക്കുക.",
    loginLeftTitle: "നിങ്ങൾ പഠിക്കുന്ന ഓരോ വാക്കും ഒരു പുതിയ വാതിൽ തുറക്കുന്നു.", loginLeftSub: "വ്യക്തിഗതമാക്കിയ വായന, എഴുത്ത്, സംസാര പരിശീലനം — നിങ്ങളുടെ സ്വന്തം ഭാഷയിൽ, നിങ്ങളുടെ സ്വന്തം വേഗതയിൽ.",
    dashboardTitle: "നിങ്ങളുടെ ഡാഷ്‌ബോർഡിലേക്ക് സ്വാഗതം!", logout: "ലോഗ് ഔട്ട്"
  },
  odia: {
    ourApproachBadge: "ଆମର ଦୃଷ୍ଟିକୋଣ",
    whyWeBuiltTitle: "ଆମେ କାହିଁକି ତିଆରି କଲୁ",
    whyWeBuiltHighlight: "ସାକ୍ଷର",
    approachSubtitle: "ଚାରୋଟି ବିଶ୍ୱାସ ଯାହା ପ୍ଲାଟଫର୍ମର ପ୍ରତ୍ୟେକ ପାଠ ଏବଂ ପ୍ରତିକ୍ରିୟାକୁ ଆକାର ଦେଇଥାଏ ।",
    literacyGapTitle: "ସାକ୍ଷରତା ବ୍ୟବଧାନ ମାନବୀୟ ଅଟେ",
    literacyGapBody: "ଲକ୍ଷ ଲକ୍ଷ ବୟସ୍କ ବ୍ୟକ୍ତି ସ୍ପଷ୍ଟ ଭାବରେ କଥାବାର୍ତ୍ତା କରନ୍ତି କିନ୍ତୁ ସେମାନଙ୍କୁ କଦାପି ଆତ୍ମବିଶ୍ୱାସର ସହିତ ପଢିବା କିମ୍ବା ଲେଖିବା ଶିଖାଯାଇନାହିଁ । ଏହା ବୈଷୟିକ ସମସ୍ୟା ନୁହେଁ — ଏହା ଏକ ମାନବୀୟ ସମସ୍ୟା ।",
    oneSizeFitsTitle: "ଗୋଟିଏ ମାପ ସମସ୍ତଙ୍କ ପାଇଁ ଉପଯୁକ୍ତ ନୁହେଁ",
    oneSizeFitsBody: "ସାକ୍ଷର ଏକ ସଂକ୍ଷିପ୍ତ ମୂଲ୍ୟାଙ୍କନରୁ ଆରମ୍ଭ ହୁଏ ଏବଂ ଶିକ୍ଷାର୍ଥୀଙ୍କ ନିଜ ଗତି, ଭାଷା ଏବଂ ସ୍ତର ଅନୁଯାୟୀ ପଥ ତିଆରି କରେ ।",
    aiListensTitle: "AI ଯାହା ଫେରସ୍ତ ଶୁଣେ",
    aiListensBody: "ରିଅଲ-ଟାଇମ୍ ଉଚ୍ଚାରଣ ପ୍ରତିକ୍ରିୟା ଏବଂ ଅକ୍ଷର ଟ୍ରେସିଂ ପାଠକୁ ଦୁଇପାଖିଆ କଥାବାର୍ତ୍ତାରେ ପରିଣତ କରେ ।",
    fluencyMotherTitle: "ମାତୃଭାଷାରେ ଦକ୍ଷତା",
    fluencyMotherBody: "ଆପଣ ସ୍ୱପ୍ନ ଦେଖୁଥିବା ଭାଷାରେ ଶିକ୍ଷା ସବୁଠାରୁ ଗଭୀର ହୋଇଥାଏ । ସାକ୍ଷର ୨୦ରୁ ଅଧିକ ଭାରତୀୟ ଆଞ୍ଚଳିକ ଭାଷାରେ ଶିକ୍ଷା ଦିଏ ।",
    thePlatformBadge: "ପ୍ଲାଟଫର୍ମ",
    platformTitle: "ଏକ ଶ୍ରେଣୀଗୃହ ଯାହା ପ୍ରତ୍ୟେକ ଶିକ୍ଷାର୍ଥୀଙ୍କ ପାଇଁ ଉପଯୁକ୍ତ",
    platformSubtitle: "ତିନୋଟି ବୁଦ୍ଧିମାନ ମଡ୍ୟୁଲ୍ ପଢିବା, ଲେଖିବା ଏବଂ କହିବା ଦକ୍ଷତା ବୃଦ୍ଧି କରିବା ପାଇଁ ଏକାଠି କାମ କରନ୍ତି ।",
    mod1Tag: "01 / ପଠନ",
    mod1Title: "ଇଣ୍ଟରାକ୍ଟିଭ୍ ପଠନ",
    mod1Desc: "ଦୈନନ୍ଦିନ ସ୍ଥାନୀୟ କାର୍ଯ୍ୟ ଉପରେ ଆଧାରିତ କଷ୍ଟମ୍ ବିଷୟବସ୍ତୁ ଡେକ୍ ।",
    mod2Tag: "02 / ଲେଖନ",
    mod2Title: "ରିଅଲ-ଟାଇମ୍ ଟ୍ରେସିଙ୍ଗ୍",
    mod2Desc: "ସ୍କ୍ରିନରେ ଅକ୍ଷର ଟ୍ରେସ୍ କରନ୍ତୁ ଏବଂ ସଂଶୋଧନ ପ୍ରାପ୍ତ କରନ୍ତୁ ।",
    mod3Tag: "03 / କଥନ",
    mod3Title: "ଭଏସ୍ ସତ୍ୟାପନ",
    mod3Desc: "ଉଚ୍ଚ ସ୍ୱରରେ କୁହନ୍ତୁ ଏବଂ ଶୁଣନ୍ତୁ ଆପଣ କେତେ ସଠିକ୍ ଅଛନ୍ତି ।",
    stat1Label: "ଆଞ୍ଚଳିକ ଭାଷା",
    stat2Label: "ଉଚ୍ଚାରଣ ସଠିକତା",
    stat3Label: "ଶିକ୍ଷାର୍ଥୀ ଯୋଗ ଦେଇଛନ୍ତି",
    stat4Label: "ସାକ୍ଷରତା ମଡ୍ୟୁଲ୍",
    aiCompanionBadge: "AI ସାକ୍ଷରତା ସାଥୀ",
    voiceDetectorLabel: "AI ଭଏସ୍ ଭାଷା ଚୟନକର୍ତ୍ତା",
    listening: "ଶୁଣୁଛି…",
    voiceListeningPrompt: "ଆପଣଙ୍କ ମାତୃଭାଷାରେ କୁହନ୍ତୁ…",
    detectedLabel: "ଚିହ୍ନଟ ହୋଇଛି",
    tryLiveDemo: "ଲାଇଭ୍ ଡେମୋ ଚେଷ୍ଟା କରନ୍ତୁ",
    voiceAiLabel: "ଭଏସ୍ AI",
    tracingLabel: "ଟ୍ରେସିଙ୍ଗ୍",
    scrollLabel: "ସ୍କ୍ରୋଲ୍ କରନ୍ତୁ",
    micBtnTooltip: "ମାଇକ୍ କ୍ଲିକ୍ କରନ୍ତୁ ଏବଂ କୁହନ୍ତୁ!",
    secReading: "ପଠନ",
    secWriting: "ଲେଖନ",
    secSpeaking: "କଥନ",
    secReasoning: "ଯୁକ୍ତି",
    langHindi: "ହିନ୍ଦୀ",
    langTamil: "ତାମିଲ୍",
    langBengali: "ବଙ୍ଗାଳୀ",
    ourApproachBadge: "ଆମର ଦୃଷ୍ଟିକୋଣ",
    whyWeBuiltTitle: "ଆମେ କାହିଁକି ତିଆରି କଲୁ",
    whyWeBuiltHighlight: "ସାକ୍ଷର",
    approachSubtitle: "ଚାରୋଟି ବିଶ୍ୱାସ ଯାହା ପ୍ଲାଟଫର୍ମର ପ୍ରତ୍ୟେକ ପାଠ ଏବଂ ପ୍ରତିକ୍ରିୟାକୁ ଆକାର ଦେଇଥାଏ ।",
    literacyGapTitle: "ସାକ୍ଷରତା ବ୍ୟବଧାନ ମାନବୀୟ ଅଟେ",
    literacyGapBody: "ଲକ୍ଷ ଲକ୍ଷ ବୟସ୍କ ବ୍ୟକ୍ତି ସ୍ପଷ୍ଟ ଭାବରେ କଥାବାର୍ତ୍ତା କରନ୍ତି କିନ୍ତୁ ସେମାନଙ୍କୁ କଦାପି ଆତ୍ମବିଶ୍ୱାସର ସହିତ ପଢିବା କିମ୍ବା ଲେଖିବା ଶିଖାଯାଇନାହିଁ । ଏହା ବୈଷୟିକ ସମସ୍ୟା ନୁହେଁ — ଏହା ଏକ ମାନବୀୟ ସମସ୍ୟା ।",
    oneSizeFitsTitle: "ଗୋଟିଏ ମାପ ସମସ୍ତଙ୍କ ପାଇଁ ଉପଯୁକ୍ତ ନୁହେଁ",
    oneSizeFitsBody: "ସାକ୍ଷର ଏକ ସଂକ୍ଷିପ୍ତ ମୂଲ୍ୟାଙ୍କନରୁ ଆରମ୍ଭ ହୁଏ ଏବଂ ଶିକ୍ଷାର୍ଥୀଙ୍କ ନିଜ ଗତି, ଭାଷା ଏବଂ ସ୍ତର ଅନୁଯାୟୀ ପଥ ତିଆରି କରେ ।",
    aiListensTitle: "AI ଯାହା ଫେରସ୍ତ ଶୁଣେ",
    aiListensBody: "ରିଅଲ-ଟାଇମ୍ ଉଚ୍ଚାରଣ ପ୍ରତିକ୍ରିୟା ଏବଂ ଅକ୍ଷର ଟ୍ରେସିଂ ପାଠକୁ ଦୁଇପାଖିଆ କଥାବାର୍ତ୍ତାରେ ପରିଣତ କରେ ।",
    fluencyMotherTitle: "ମାତୃଭାଷାରେ ଦକ୍ଷତା",
    fluencyMotherBody: "ଆପଣ ସ୍ୱପ୍ନ ଦେଖୁଥିବା ଭାଷାରେ ଶିକ୍ଷା ସବୁଠାରୁ ଗଭୀର ହୋଇଥାଏ । ସାକ୍ଷର ୨୦ରୁ ଅଧିକ ଭାରତୀୟ ଆଞ୍ଚଳିକ ଭାଷାରେ ଶିକ୍ଷା ଦିଏ ।",
    thePlatformBadge: "ପ୍ଲାଟଫର୍ମ",
    platformTitle: "ଏକ ଶ୍ରେଣୀଗୃହ ଯାହା ପ୍ରତ୍ୟେକ ଶିକ୍ଷାର୍ଥୀଙ୍କ ପାଇଁ ଉପଯୁକ୍ତ",
    platformSubtitle: "ତିନୋଟି ବୁଦ୍ଧିମାନ ମଡ୍ୟୁଲ୍ ପଢିବା, ଲେଖିବା ଏବଂ କହିବା ଦକ୍ଷତା ବୃଦ୍ଧି କରିବା ପାଇଁ ଏକାଠି କାମ କରନ୍ତି ।",
    mod1Tag: "01 / ପଠନ",
    mod1Title: "ଇଣ୍ଟରାକ୍ଟିଭ୍ ପଠନ",
    mod1Desc: "ଦୈନନ୍ଦିନ ସ୍ଥାନୀୟ କାର୍ଯ୍ୟ ଉପରେ ଆଧାରିତ କଷ୍ଟମ୍ ବିଷୟବସ୍ତୁ ଡେକ୍ ।",
    mod2Tag: "02 / ଲେଖନ",
    mod2Title: "ରିଅଲ-ଟାଇମ୍ ଟ୍ରେସିଙ୍ଗ୍",
    mod2Desc: "ସ୍କ୍ରିନରେ ଅକ୍ଷର ଟ୍ରେସ୍ କରନ୍ତୁ ଏବଂ ସଂଶୋଧନ ପ୍ରାପ୍ତ କରନ୍ତୁ ।",
    mod3Tag: "03 / କଥନ",
    mod3Title: "ଭଏସ୍ ସତ୍ୟାପନ",
    mod3Desc: "ଉଚ୍ଚ ସ୍ୱରରେ କୁହନ୍ତୁ ଏବଂ ଶୁଣନ୍ତୁ ଆପଣ କେତେ ସଠିକ୍ ଅଛନ୍ତି ।",
    stat1Label: "ଆଞ୍ଚଳିକ ଭାଷା",
    stat2Label: "ଉଚ୍ଚାରଣ ସଠିକତା",
    stat3Label: "ଶିକ୍ଷାର୍ଥୀ ଯୋଗ ଦେଇଛନ୍ତି",
    stat4Label: "ସାକ୍ଷରତା ମଡ୍ୟୁଲ୍",
    beginYourJourney: "ଆପଣଙ୍କର ଯାତ୍ରା ଆରମ୍ଭ କରନ୍ତୁ",
    ctaHeadlineLine1: "ଆପଣ ଶିଖୁଥିବା ପ୍ରତ୍ୟେକ ଶବ୍ଦ",
    ctaHeadlineLine2: "ଏକ ନୂତନ ଦ୍ୱାର ଖୋଲିଥାଏ ।",
    getStartedFree: "ମାଗଣାରେ ଆରମ୍ଭ କରନ୍ତୁ",
    watchDemo: "ଡେମୋ ଦେଖନ୍ତୁ",
    home: "ହୋମ୍", signIn: "ସାଇନ୍ ଇନ୍", createAccount: "ଆକାଉଣ୍ଟ୍ ତିଆରି କରନ୍ତୁ", welcomeBack: "ସ୍ୱାଗତ",
    signInSub: "ଆପଣଙ୍କର ଶିକ୍ଷା ଯାତ୍ରା ଜାରି ରଖିବା ପାଇଁ ସାଇନ୍ ଇନ୍ କରନ୍ତୁ ।", email: "✉️ ଇମେଲ୍ ଠିକଣା", password: "🔒 ପାସୱାର୍ଡ", fullName: "👤 ପୁରା ନାମ", or: "କିମ୍ବା",
    googleSignIn: "ଗୁଗଲ୍ ସହିତ ଆଗକୁ ବଢନ୍ତୁ", newHere: "ଏଠାରେ ନୂଆ କି?", alreadyHaveAccount: "ପୂର୍ବରୁ ଆକାଉଣ୍ଟ୍ ଅଛି କି?", landingTitle: "AI ମାଧ୍ୟମରେ ସାକ୍ଷରତା ସଶକ୍ତିକରଣ",
    landingTitleLine1: "ସାକ୍ଷରତା ସଶକ୍ତିକରଣ", landingTitleLine2: "AI ଜ୍ଞାନ ଦ୍ୱାରା",
    landingSub: "ଏକ ବ୍ୟକ୍ତିଗତ ଶିକ୍ଷଣ ସାଥୀ ଯାହା ବୟସ୍କ ଏବଂ ପ୍ରଥମ ପିଢ଼ିର ଶିକ୍ଷାର୍ଥୀମାନଙ୍କୁ ଆଞ୍ଚଳିକ ଭାଷାରେ ମୌଳିକ ପଢିବା, ଲେଖିବା ଏବଂ କହିବା ଦକ୍ଷତା ହାସଲ କରିବାରେ ସାହାଯ୍ୟ କରିବା ପାଇଁ ପ୍ରସ୍ତୁତ କରାଯାଇଛି ।",
    getStarted: "ଆରମ୍ଭ କରନ୍ତୁ", registerTitle: "ଆପଣଙ୍କ ଆକାଉଣ୍ଟ୍ ତିଆରି କରନ୍ତୁ", registerSub: "ଆମ ସମୁଦାୟରେ ଯୋଗ ଦିଅନ୍ତୁ ଏବଂ ଶିକ୍ଷାର ପରିସରକୁ ବୃଦ୍ଧି କରନ୍ତୁ ।",
    languageLabel: "🌐 ପସନ୍ଦର ମାତୃଭାଷା", registerLeftTitle: "ଆପଣଙ୍କର ସାକ୍ଷରତା ଯାତ୍ରା ଏଠାରୁ ଆରମ୍ଭ ହୁଏ ।",
    registerLeftSub: "ଭଏସ୍ ପ୍ରାକ୍ଟିସ୍ ଆସେସମେଣ୍ଟ୍ ଏବଂ ଦୈନିକ ପଠନ ପାଠ୍ୟକ୍ରମକୁ ଅନଲକ୍ କରିବା ପାଇଁ ଏକ ପ୍ରୋଫାଇଲ୍ ତିଆରି କରନ୍ତୁ ।",
    loginLeftTitle: "ଆପଣ ଶିଖୁଥିବା ପ୍ରତ୍ୟେକ ଶବ୍ଦ ଏକ ନୂତନ ଦ୍ୱାର ଖୋଲିଥାଏ ।", loginLeftSub: "ବ୍ୟକ୍ତିଗତ ପଢିବା, ଲେଖିବା ଏବଂ କହିବା ଅଭ୍ୟାସ — ଆପଣଙ୍କ ନିଜ ଭାଷାରେ, ଆପଣଙ୍କ ନିଜ ଗତିରେ ।",
    dashboardTitle: "ଆପଣଙ୍କ ଡ୍ୟାଶବୋର୍ଡକୁ ସ୍ୱାଗତ!", logout: "ଲଗ୍ ଆଉଟ୍"
  },
  urdu: {
    home: "ہوم", signIn: "سائن ان", createAccount: "اکاؤنٹ بنائیں", welcomeBack: "خوش آمدید",
    signInSub: "اپنا سیکھنے کا سفر جاری رکھنے کے لیے سائن ان کریں۔", email: "✉️ ای میل ایڈریس", password: "🔒 پاس ورڈ", fullName: "👤 پورا نام", or: "یا",
    googleSignIn: "گوگل کے ساتھ جاری رکھیں", newHere: "یہاں نئے ہیں؟", alreadyHaveAccount: "پہلے سے اکاؤنٹ ہے؟", landingTitle: "AI کے ذریعے خواندگی کا فروغ",
    landingTitleLine1: "خواندگی کا فروغ", landingTitleLine2: "AI ذہانت کے ذریعے",
    landingSub: "ایک ذاتی نوعیت کا تعلیمی ساتھی جو بالغوں اور پہلی نسل کے سیکھنے والوں کو علاقائی زبانوں میں بنیادی پڑھنے, لکھنے اور بولنے کی مہارت حاصل کرنے میں مدد کرتا ہے۔",
    getStarted: "شروع کریں", registerTitle: "اپنا اکاؤنٹ بنائیں", registerSub: "ہماری کمیونٹی میں شامل ہوں اور اپنے سیکھنے کے افق کو وسعت دیں۔",
    languageLabel: "🌐 پسندیدہ مادری زبان", registerLeftTitle: "آپ کا پڑھنے کا سفر یہاں سے شروع ہوتا ہے۔",
    registerLeftSub: "صوتی مشق کے جائزے، حقیقی وقت کے تاثرات، اور روزانہ پڑھنے کے اسباق کو غیر مقفل کرنے کے لیے پروفائل بنائیں۔",
    loginLeftTitle: "ہر وہ لفظ جو آپ سیکھتے ہیں ایک نیا دروازہ کھولتا ہے۔", loginLeftSub: "ذاتی نوعیت کا پڑھنا، لکھنا اور بولنا — آپ کی اپنی زبان میں, آپ کی اپنی رفتار سے۔",
    dashboardTitle: "آپ کے ڈیش بورڈ میں خوش آمدید!", logout: "لاگ آؤٹ"
  },
  assamese: {
    home: "হোম", signIn: "সাইন ইন", createAccount: "একাউণ্ট খোলক", welcomeBack: "স্বাগতম",
    signInSub: "আপোনাৰ শিকন যাত্ৰা অব্যাহত ৰাখিবলৈ ছাইন ইন কৰক।", email: "✉️ ইমেইল ঠিকনা", password: "🔒 পাছৱৰ্ড", fullName: "👤 সম্পূৰ্ণ নাম", or: "অথবা",
    googleSignIn: "গুগলৰ সৈতে আগবাঢ়ক", newHere: "ইয়াত নতুন নেকি?", alreadyHaveAccount: "ইতিমধ্যে একাউণ্ট আছে নেকি?", landingTitle: "AI ৰ জৰিয়তে সাক্ষৰতা সবলীকৰণ",
    landingTitleLine1: "সাক্ষৰতা সবলীকৰণ", landingTitleLine2: "AI বুদ্ধিৰ জৰিয়তে",
    landingSub: "এটা ব্যক্তিগতকৃত শিক্ষণ সহযোগী যি প্ৰাপ্তবয়স্ক আৰু প্ৰথম প্ৰজন্মৰ শিক্ষাৰ্থীক আঞ্চলিক ভাষাত মৌলিক পঢ়া, লিখা আৰু কোৱাৰ দক্ষতা অৰ্জন কৰাত সহায় কৰিবলৈ ডিজাইন কৰা হৈছে।",
    getStarted: "আৰম্ভ কৰক", registerTitle: "আপোনাৰ এককাউণ্ট খোলক", registerSub: "আমাৰ সমাজত যোগদান কৰক আৰু আপোনাৰ শিক্ষাৰ পৰিসৰ বৃদ্ধি কৰক।",
    languageLabel: "🌐 পছন্দৰ মাতৃভাষা", registerLeftTitle: "আপোনাৰ সাক্ষৰতাৰ যাত্ৰা ইয়াতেই আৰম্ভ হৈছে।",
    registerLeftSub: "ভয়েচ প্ৰেকটিচ এছেছমেণ্ট, ৰিয়েল-টাইম ফীডবেক আৰু দৈনিক পঢ়াৰ পাঠ আনলক কৰিবলৈ এটা প্ৰফাইল সৃষ্টি কৰক।",
    loginLeftTitle: "আপুনি শিকা প্ৰতিটো শব্দই এটা নতুন দুৱাৰ খোলে।", loginLeftSub: "ব্যক্তিগতকৃত পঢ়া, লিখা আৰু কোৱাৰ অভ্যাস — আপোনাৰ নিজৰ ভাষাত, আপোনাৰ নিজৰ গতিৰে।",
    dashboardTitle: "আপোনাৰ ডেশ্ববৰ্ডলৈ স্বাগতম!", logout: "লগ আউট"
  },
  maithili: {
    home: "होम", signIn: "साइन इन", createAccount: "खाता बनाउ", welcomeBack: "स्वागत अछि",
    signInSub: "अपन सीखबाक यात्रा जारी रखबाक लेल साइन इन करू।", email: "✉️ ईमेल पता", password: "🔒 पासवर्ड", fullName: "👤 पूरा नाम", or: "वा",
    googleSignIn: "गूगलक संग जारी राखू", newHere: "एतय नव छी?", alreadyHaveAccount: "पहले सं खाता अछि?", landingTitle: "AI क माध्यम सं साक्षरताक सशक्तिकरण",
    landingTitleLine1: "साक्षरताक सशक्तिकरण", landingTitleLine2: "AI बुद्धिमत्ता द्वारा",
    landingSub: "एकटा व्यक्तिगत शिक्षण साथी जे वयस्क आ पहিল पीढ़िक सीखनिहार लोकनिकेँ क्षेत्रीय भाषामे बुनियादी पढ़ब, लिखब आ बाजबाक कौशल हासिल करबामे मद्दति करबाक लेल बनाओल गेल अछि।",
    getStarted: "शुरू करू", registerTitle: "अपन खाता बनाउ", registerSub: "हमर समुदायमे शामिल होऊ आ अपन सीखबाक दायरा बढाउ।",
    languageLabel: "🌐 पसंदीदा मातृभाषा", registerLeftTitle: "अहाँक साक्षरताक यात्रा एतय सं शुरू होइत अछि।",
    registerLeftSub: "आवाज अभ्यास मूल्यांकन आ दैनिक पढ़बाक पाठकेँ अनलॉक करबाक लेल एकटा प्रोफाइल बनाउ।",
    loginLeftTitle: "अहाँक द्वारा सीखल गेल हर शब्द एकटा नव कपाट खोलैत अछि।", loginLeftSub: "व्यक्तिगत पढ़ब, लिखब आ बाजबाक अभ्यास — अहाँक अपन भाषामे, अपन गति सं।",
    dashboardTitle: "अहाँक डैशबोर्डमे स्वागत अछि!", logout: "लॉग आउट"
  },
  santhali: {
    home: "ᱦᱳᱢ", signIn: "ᱥᱟᱭᱤᱱ ᱤᱱ", createAccount: "ᱠᱷᱟᱛᱟ ᱵᱮᱱᱟᱣ", welcomeBack: "ᱥᱟᱹᱜᱩᱱ ᱫTransition",
    signInSub: "ᱟᱢᱟᱜ ᱪᱮᱫᱚᱜ ᱦᱚᱨา ᱞᱟᱦᱟ ᱤᱫᱤ ᱞᱟᱹᱜᱤᱫ ᱥᱟᱭᱤᱱ ᱤᱱ ᱢᱮ ᱾", email: "✉️ ਈਮੇਲ ᱴᱷᱮᱠਾᱬָᱟ", password: "🔒 ᱯᱟᱥᱣᱟᱨᱰ", fullName: "👤 ᱯᱩᱨᱟᱹ ᱧᱩᱛᱩᱢ", or: "ᱪᱮ",
    googleSignIn: "ᱜᱩᱜᱚᱞ ᱥᱟᱶ ᱞᱟᱦᱟᱜ ᱢᱮ", newHere: "ᱱᱚᱸᱰᱮ ᱱᱟᱣা ᱜᱮᱭᱟᱢ?", alreadyHaveAccount: "ᱞᱟᱦᱟ ᱠᱷᱚᱱ ᱠᱷᱟᱛᱟ ᱢᱮᱱᱟᱜ-ᱟ?", landingTitle: "AI ᱛᱮ ᱚᱞ ᱯᱟᱲᱦᱟᱣ",
    landingTitleLine1: "ᱚᱞ ᱯᱟᱲᱦᱟᱣ", landingTitleLine2: "AI ᱫᱚ ᱵᱩᱫᱷᱤ ᱛᱮ",
    landingSub: "ᱢᱤᱫ ᱟᱯնᱟᱨ ᱪᱮᱫᱚᱜ ᱜᱟᱛᱮ ᱡᱟᱦᱟᱸᱭ ᱫᱚ ᱦᱟᱨᱟ ᱵᱩᱨᱩ ᱟᱨ ᱯᱩᱭᱞᱩ ᱯᱤᱲᱦᱤ ᱪᱮᱫᱚᱜ ᱠᱚ ᱟᱠᱚᱣᱟᱜ ᱟᱭᳵ ᱟᱲᱟᱝ ᱛᱮ ᱚլ, ᱯᱟᱲᱦᱟᱣ ᱟᱨ ᱨᱚᱲ ᱪᱮᱫᱚᱜ ᱨᱮ ᱜᱚᱲᱚ ᱮᱢา ᱠᱚᱣᱟ ᱾",
    getStarted: "ᱮᱦᱚᱵ ᱢᱮ", registerTitle: "ᱟᱢาᱜ ᱠᱷᱟᱛᱟ ᱵᱮᱱᱟᱣ ᱢᱮ", registerSub: "ᱟᱞᱮ ᱥᱟᱶ ᱡᱩᱲᱟᱹᱣ ᱢᱮ ᱟᱨ ᱟᱢᱟᱜ ᱜᱮᱭᱟᱱ ᱯᱟᱥᱱᱟᱣ ᱢᱮ ᱾",
    languageLabel: "🌐 ᱠᱩᱥᱤᱭᱟᱜ ᱟᱭᳵ ᱟᱲᱟᱝ", registerLeftTitle: "Aᱢᱟᱜ ᱥᱮᱪᱮᱫ ᱦᱚᱨᱟ ᱱᱚᱸᳰᱮ ᱠᱷᱚᱱ ᱮᱦᱚᱵᱚᱜ-า ᱾",
    registerLeftSub: "Aᱲᱟᱝ ᱵᱤᰰᱟᱹᱣ ᱟᱨ དིᱱᱟᱹᱢ ᱯᱟᱲᱦᱟᱣ ᱞᱮᱥᱚᱱ ᱠᱚ ᱡᱷᱤᱡ ᱞᱟᱹᱜᱤᱫ ᱯᱨᱚᱯᱷᱟᱭᱤᱞ ᱵᱮᱱᱟᱣ ᱢᱮ ᱾",
    loginLeftTitle: "ᱪᱮᱫᱚᱜ ᱨᱮᱱᱟᱜ ᱢᱤᱫ ᱢᱤᱫ ᱥᱟᱵาᱫ ᱱᱟᱣᱟ དུ་ᱣᱟᱹր ᱡᱷᱤᱡ-ᱟ ᱾", loginLeftSub: "ᱟᱯᱱᱟᱨ ᱯᱟᱲᱦᱟᱣ, ᱚլ ᱟᱨ ᱨᱚᱲ ᱨᱮᱱᱟᱜ ᱵᱤᰰᱟᱹᱣ — ᱟᱢᱟᱜ ᱛᱮ, ᱟᱢᱟᱜ ᱛᱟᱹᱞ ᱛᱮ ᱾",
    dashboardTitle: "ᱟᱢᱟᱜ ᱰᱮᱥᱵᱳᱨᱰ ᱨᱮ ᱥᱟᱹᱜᱩᱱ ᱫTransition!", logout: "ᱳᱰᱳᱜ ᱢᱮ"
  },
  kashmiri: {
    home: "ہوم", signIn: "سائن ان", createAccount: "اکاؤنٹ بنایو", welcomeBack: "خوش آمدید",
    signInSub: "پنُن تعلیمی سفر جاری تھونہ خاطرہ کٔریو سائن ان۔", email: "✉️ ای میل پتہ", password: "🔒 پاس ورڈ", fullName: "👤 پۆرو ناؤ", or: "یا",
    googleSignIn: "گوگل پیتھ کٔریو جاری", newHere: "نۆو چُھا؟", alreadyHaveAccount: "برونہہ پؠٹھے چُھا اکاؤنٹ؟", landingTitle: "AI ذریہ تعلیمی بیداری",
    landingTitleLine1: "تعلیمی بیداری", landingTitleLine2: "AI ذہانت ذریہ",
    landingSub: "اکھ پنُن تعلیمی مددگار یُس وڈیرن تۂ گوڈنچہ نسلِ ہندین پرن والین ہنز مادری زبانن منز پراز پرنس، لیکھنس تۂ بولنس منز مدد کران چُھ۔",
    getStarted: "شروع کٔریو", registerTitle: "پنُن اکاؤنٹ بنایو", registerSub: "سٲنس برادری منز شمل کٔریو تۂ پنُن علم بڑھایو۔",
    languageLabel: "🌐 مادری زبان", registerLeftTitle: "تُہند پرنُک سفر چُھ یتنے شروع سپدان۔",
    registerLeftSub: "آواز ہند مشق تۂ پرنک سبق انلاک کرنہ خاطرہ کٔریو پروفائل تیار۔",
    loginLeftTitle: "ہر اکھ لفظ یُس تُہی پروو سو چُھ اکھ نیاو دروازہ کھولان۔", loginLeftSub: "پننہ زبانِ منز تۂ پننہ رفتارس پیتھ پرنُک تۂ بولنُک مشق۔",
    dashboardTitle: "تُہندس ڈیش بورڈس منز خوش آمدید!", logout: "لاگ آؤٹ"
  },
  nepali: {
    home: "होम", signIn: "साइन इन", createAccount: "खाता सिर्जना गर्नुहोस्", welcomeBack: "स्वागत छ",
    signInSub: "आफ्नो सिकाई यात्रा जारी राख्न साइन इन गर्नुहोस्।", email: "✉️ इमेल ठेगाना", password: "🔒 पासवर्ड", fullName: "👤 पूरा नाम", or: "वा",
    googleSignIn: "गुगलसँग जारी राख्नुहोस्", newHere: "यहाँ नयाँ हुनुहुन्छ?", alreadyHaveAccount: "पहिले नै खाता छ?", landingTitle: "AI मार्फत साक्षरता सशक्तिकरण",
    landingTitleLine1: "साक्षरता सशक्तिकरण", landingTitleLine2: "AI बुद्धिमत्ता मार्फत",
    landingSub: "एक व्यक्तिगत सिकाइ साथी जुन वयस्कहरू र पहिलो पुस्ताका शिक्षार्थीहरूलाई क्षेत्रीय भाषाहरूमा आधारभूत पढ्न, लेख्न र बोल्ने सीपहरू प्राप्त गर्न मद्दत गर्न डिजाइन गरिएको हो।",
    getStarted: "सुरु गर्नुहोस्", registerTitle: "आफ्नो खाता सिर्जना गर्नुहोस्", registerSub: "हाम्रो समुदायमा सामेल हुनुहोस् र आफ्नो सिकाई क्षितिज विस्तार गर्नुहोस्।",
    languageLabel: "🌐 रुचाइएको मातृभाषा", registerLeftTitle: "तपाईंको साक्षरता यात्रा यहाँबाट सुरु हुन्छ।",
    registerLeftSub: "आवाज अभ्यास मूल्याङ्कन र दैनिक पढ्ने पाठहरू अनलक गर्न प्रोफाइल सिर्जना गर्नुहोस्।",
    loginLeftTitle: "तपाईंले सिक्नुभएको हरेक शब्दले नयाँ ढोका खोल्छ।", loginLeftSub: "व्यक्तिगत पढ्ने, लेख्ने र बोल्ने अभ्यास — तपाईंको आफ्नै भाषामा, तपाईंको आफ्नै गतिमा।",
    dashboardTitle: "तपाईंको ड्यासबोर्डमा स्वागत छ!", logout: "लग आउट"
  },
  gondi: {
    home: "होम", signIn: "साइन इन", createAccount: "खाता कीम", welcomeBack: "सगताम",
    signInSub: "नीवा कलीना वेद्द्ता लोप्पे साइन इन कीम।", email: "✉️ ईमेल पता", password: "🔒 पासवर्ड", fullName: "👤 आक्खे पुदिर", or: "बाले",
    googleSignIn: "गूगल तोड़े सांगे मंत", newHere: "पुना मंत्या?", alreadyHaveAccount: "मुन्ने ने खाता मंता?", landingTitle: "AI ना वळते साक्षरता विकास",
    landingTitleLine1: "साक्षरता विकास", landingTitleLine2: "AI बुद्धि वळते",
    landingSub: "ऊंद मने कलीना तोड़े जश वयस्क और पहिल्या पीढ़ी ना कलीवाला न तोड़े भाषा ते वाचना, लीहना और वळना कली क कींत।",
    getStarted: "शुरू कीम", registerTitle: "नीवा खाता कीम", registerSub: "मावा गोट्टे ते कली और गियान वाधाय कीम।",
    languageLabel: "🌐 यालोळ नाटो भासा", registerLeftTitle: "नीवा साक्षरता कलीना इग्गने शुरू माता।",
    registerLeftSub: "वळना कलीना और रोज वाचना पाठ क तीरा कीले प्रोफाइल कीम।",
    loginLeftTitle: "जे शब्द कली कींत ओंद पुना कपाट तीरीत।", loginLeftSub: "नीवा भाषा ते नीवा नळ ते वाचना, लीहना और वळना क अभ्यास।",
    dashboardTitle: "नीवा डैशबोर्ड ते सगताम मंता!", logout: "बायदो"
  },
  sindhi: {
    home: "هوم", signIn: "سائن ان", createAccount: "खातो ٺاهيو", welcomeBack: "ڀلي ڪري آયા",
    signInSub: "پنهنجو سکڻ جو سفر جاري رکڻ لاءِ سائن ان ڪريو.", email: "✉️ اي ميل پتو", password: "🔒 پاسورڊ", fullName: "👤 پورو نالو", or: "يا",
    googleSignIn: "گوگل سان جاري رکو", newHere: "هتي نوان آهيو؟", alreadyHaveAccount: "پهرين کان خاتو آهي؟", landingTitle: "AI جي ذريعي تعليم جي سجاڳي",
    landingTitleLine1: "تعليم جي سجاڳي", landingTitleLine2: "AI ذهانت ذريعي",
    landingSub: "هڪ ذاتي سکيا جو ساٿي جيڪو وڏن ۽ پهرين نسل جي سکندڙن کي علائقائي ٻولين ۾ بنيادي پڙهڻ, لکڻ ۽ ڳالهائڻ جي صلاحيت حاصل ڪرڻ ۾ مدد ڪري ٿو.",
    getStarted: "شروع ڪريو", registerTitle: "پنهنجو खातो ٺاهيو", registerSub: "اسان جي برادري ۾ شامل ٿيو ۽ پنهنجي سکيا جو دائرو وڌايو.",
    languageLabel: "🌐 پسنديده مادري ٻولي", registerLeftTitle: "توهان جو سکڻ جو سفر هتان شروع ٿئي ٿو.",
    registerLeftSub: "آواز جي مشق ۽ روزاني پڙهڻ جا سبق کولڻ لاءِ هڪ پروفائل ٺاهيو.",
    loginLeftTitle: "توهان جيڪو به لفظ سکو ٿا اهو هڪ نئون دڙو کولي ٿو.", loginLeftSub: "پنهنجي ٻوليءَ ۾، پنهنجي رفتار سان پڙهڻ, لکڻ ۽ ڳالهائڻ جي مشق.",
    dashboardTitle: "توهان جي ڊيش بورڊ تي ڀلي ڪري آયા!", logout: "لاگ آئوٽ"
  },
  konkani: {
    home: "होम", signIn: "साइन इन", createAccount: "खातें तयार करात", welcomeBack: "येवकार",
    signInSub: "तुमची शिकपाची भोंवड जारी दवरपाक साइन इन करात.", email: "✉️ ईमेल पत्तो", password: "🔒 पासवर्ड", fullName: "👤 पूर्ण नांव", or: "वा",
    googleSignIn: "गूगल वांगडा फुडे वचात", newHere: "नवे आहात?", alreadyHaveAccount: "पयलींच खातें आसा?", landingTitle: "AI वरवीं साक्षरता उदरगत",
    landingTitleLine1: "साक्षरता उदरगत", landingTitleLine2: "AI बुद्धिमत्ता वरवीं",
    landingSub: "एक खाजगी शिकपाचो सांगाती जो जाणट्यांक आनी पयल्या पिळгеच्या शिकप्यांक थळाव्या भासांनी बुन्यादी वाचन, लेखन आनी उलोवपाचीं कौशल्यां मेळोવपाक मदत करता.",
    getStarted: "सुरू करात", registerTitle: "तुमचें खातें तयार करात", registerSub: "आमच्या पंगडांत आस्पावन तुमचें शिकপ वाडयात.",
    languageLabel: "🌐 pसंतीची आवयभास", registerLeftTitle: "तुमची साक्षरतेची भोंवड हांगासून सुरू जाता.",
    registerLeftSub: "आवाज सराव आनी दिसाळें वाचन धडे सुरू करपाक एक प्रोफाईल तयार करात.",
    loginLeftTitle: "तुम्ही शिकिल्लो दरेक शब्द एक नवें दार उघडटा.", loginLeftSub: "खंयच्याय अडखळा बगर तुमच्याच भाशेन आनी गतीन वाचन आनी उलोवपाचो सराव.",
    dashboardTitle: "तुमच्या डॅशबोर्डाचेर येवकार!", logout: "लॉग आउट"
  }
};

export const targetLanguages = [
  { value: 'english', native: 'English', label: 'English' },
  { value: 'hindi', native: 'हिन्दी', label: 'Hindi' },
  { value: 'telugu', native: 'తెలుగు', label: 'Telugu' },
  { value: 'punjabi', native: 'ਪੰਜਾਬੀ', label: 'Punjabi' },
  { value: 'bengali', native: 'বাংলা', label: 'Bengali' },
  { value: 'marathi', native: 'मराठी', label: 'Marathi' },
  { value: 'tamil', native: 'தமிழ்', label: 'Tamil' },
  { value: 'gujarati', native: 'ગુજરાતી', label: 'Gujarati' },
  { value: 'kannada', native: 'ಕನ್ನಡ', label: 'Kannada' },
  { value: 'malayalam', native: 'മലയാളം', label: 'Malayalam' },
  { value: 'odia', native: 'ଓଡ଼ିଆ', label: 'Odia' },
  { value: 'urdu', native: 'اُردُو', label: 'Urdu' },
  { value: 'assamese', native: 'অসমীয়া', label: 'Assamese' },
  { value: 'maithili', native: 'मैथिली', label: 'Maithili' },
  { value: 'santhali', native: 'ᱥᱟᱱᱛᱷᱟᱞᱤ', label: 'Santhali' },
  { value: 'kashmiri', native: 'کٲशুর', label: 'Kashmiri' },
  { value: 'nepali', native: 'नेपाली', label: 'Nepali' },
  { value: 'gondi', native: 'गोंडी', label: 'Gondi' },
  { value: 'sindhi', native: 'سنڌي', label: 'Sindhi' },
  { value: 'konkani', native: 'कोंकणी', label: 'Konkani' }
];