// src/config/languages.js

export const translations = {
  english: {
    home: "Home", signIn: "Sign In", createAccount: "Create Account", welcomeBack: "Welcome back",
    signInSub: "Sign in to continue your learning journey.", email: "✉️ Email Address", password: "🔒 Password", fullName: "👤 Full Name", or: "or",
    googleSignIn: "Continue with Google", newHere: "New here?", alreadyHaveAccount: "Already have an account?", landingTitle: "Empowering Literacy Through AI Intelligence",
    landingTitleLine1: "Empowering Literacy", landingTitleLine2: "Through AI Intelligence",
    aiConvertedMsg: "AI converted in selected language",
    landingSub: "A personalized learning companion designed to help adults and first-generation learners acquire foundational reading, writing, and speaking skills in regional languages.",
    getStarted: "Get Started", registerTitle: "Create your account", registerSub: "Join our community and expand your learning horizons.",
    languageLabel: "🌐 Preferred Native Language",
    wantToLearnLabel: "🎯 Language You Want to Learn",
    registerLeftTitle: "Your journey to literacy starts here.",
    registerLeftSub: "Create a profile to unlock voice practice assessments, real-time feedback, and adaptive daily reading lessons.",
    loginLeftTitle: "Every word you learn opens a new door.", loginLeftSub: "Personalized reading, writing, and speaking practice — in your own language, at your own pace.",
    dashboardTitle: "Welcome to Your Dashboard!", logout: "Log Out"
  },
  hindi: {
    home: "होम", signIn: "साइन इन करें", createAccount: "खाता बनाएं", welcomeBack: "आपका स्वागत है",
    signInSub: "अपनी सीखने की यात्रा जारी रखने के लिए साइन इन करें।", email: "✉️ ईमेल पता", password: "🔒 पासवर्ड", fullName: "👤 पूरा नाम", or: "या",
    googleSignIn: "गूगल के साथ जारी रखें", newHere: "यहाँ नए हैं?", alreadyHaveAccount: "पहले से ही एक खाता है?", landingTitle: "एआई बुद्धिमत्ता द्वारा साक्षरता का सशक्तिकरण",
    landingTitleLine1: "साक्षरता का सशक्तिकरण", landingTitleLine2: "एआई बुद्धिमत्ता द्वारा",
    aiConvertedMsg: "एआई चयनित भाषा में परिवर्तित हुआ",
    landingSub: "एक व्यक्तिगत शिक्षण साथी जो वयस्कों और पहली पीढ़ी के शिक्षार्थियों को क्षेत्रीय भाषाओं में बुनियादी पढ़ने, लिखने और बोलने के कौशल हासिल करने में मदद करने के लिए डिज़ाइन किया गया है।",
    getStarted: "शुरू करें", registerTitle: "अपना खाता बनाएं", registerSub: "हमारे समुदाय में शामिल हों और अपने सीखने के क्षितिज का विस्तार करें।",
    languageLabel: "🌐 पसंदीदा मातृभाषा",
    wantToLearnLabel: "🎯 भाषा जो आप सीखना चाहते हैं",
    registerLeftTitle: "आपकी साक्षरता की यात्रा यहीं से शुरू होती है।",
    registerLeftSub: "आवाज अभ्यास आकलन, वास्तविक समय प्रतिक्रिया, और अनुकूली दैनिक पढ़ने के पाठों को अनलॉक करने के लिए एक प्रोफ़ाइल बनाएं।",
    loginLeftTitle: "आपके द्वारा सीखा गया हर शब्द एक नया दरवाजा खोलता है।", loginLeftSub: "व्यक्तिगत पढ़ने, लिखने और बोलने का अभ्यास — आपकी अपनी भाषा में, आपकी अपनी गति से।",
    dashboardTitle: "आपके डैशबोर्ड में आपका स्वागत है!", logout: "लॉग आउट"
  },
  telugu: {
    home: "హోమ్", signIn: "సైన్ ఇన్ చేయండి", createAccount: "ఖాతాను సృష్టించండి", welcomeBack: "తిరిగి સ્વાगतम",
    signInSub: "మీ అభ్యాస ప్రయాణాన్ని కొనసాగించడానికి సైన్ ఇన్ చేయండి.", email: "✉️ ఇమెయిల్ చిరునామా", password: "🔒 పాస్‌వర్డ్", fullName: "👤 పూర్తి పేరు", or: "లేదా",
    googleSignIn: "గూగుల్‌తో కొనసాగండి", newHere: "ఇక్కడ కొత్తవారా?", alreadyHaveAccount: "ఇప్పటికే खाता ఉందా?", landingTitle: "AI ద్వారా అక్షరాస్యత సాధికారత",
    landingTitleLine1: "అక్షరాస్యత సాధికారత", landingTitleLine2: "AI మేధస్సు ద్వారా",
    landingSub: "ప్రాంతీయ భాషలలో ప్రాథమిక పఠనం, రాయడం మరియు మాట్లాడే నైపుణ్యాలను పొందడంలో పెద్దలు మరియు మొదటి తരം అభ్యాసకులకు సహాయపడటానికి రూపొందించబడిన వ్యక్తిగతీకరించిన అభ్యాస సహచరుడు.",
    getStarted: "ప్రారంభించండి", registerTitle: "మీ ఖాతాన్ని సృష్టించండి", registerSub: "మా సంఘంలో చేరండి మరియు మీ అభ్యాస పరిధులను విస్తృతం చేసుకోండి.",
    languageLabel: "🌐 ఇష్టపడే మాతృభాష", registerLeftTitle: "మీ అక్షరాస్యత ప్రయాణం ఇక్కడే ప్రారంభమవుతుంది.",
    registerLeftSub: "వాయిస్ ప్రాక్టీస్ అసెస్‌మెంట్‌లు, రియల్ టైమ్ ఫీడ్‌బ్యాక్ మరియు అదాప్టివ్ రోజువారీ పఠన పాఠాలను అన్‌లాక့် చేయడానికి ప్రొఫైల్‌ను సృష్టించండి.",
    loginLeftTitle: "మీరు నేర్చుకునే ప్రతి పదం ఒక కొత్త తలుపును తెరుస్తుంది.", loginLeftSub: "వ్యक्तिগত పఠనం, రాయడం మరియు మాట్లాడటం ప్రాక్టీस — మీ స్వంత భాషలో, మీ స్వంత వేగంతో.",
    dashboardTitle: "మీ డాష్‌బోర్డుకు స్వాगతం!", logout: "లాగ్ అవుట్"
  },
  punjabi: {
    home: "ਹੋਮ", signIn: "ਸਾਈਨ ਇਨ", createAccount: "ਖਾਤਾ ਬਣਾਓ", welcomeBack: "ਜੀ ਆਇਆਂ ਨੂੰ",
    signInSub: "ਆਪਣੀ ਸਿੱਖਣ ਦੀ ਯਾਤਰਾ ਜਾਰੀ ਰੱਖਣ ਲਈ ਸਾਈਨ ਇਨ ਕਰੋ।", email: "✉️ ਈਮੇਲ ਪਤਾ", password: "🔒 ਪਾਸਵਰਡ", fullName: "👤 ਪੂਰਾ ਨਾਮ", or: "ਜਾਂ",
    googleSignIn: "ਗੂਗਲ ਨਾਲ ਜਾਰੀ ਰੱਖੋ", newHere: "ਇੱਥੇ ਨਵੇਂ ਹੋ?", alreadyHaveAccount: "ਖਾਤਾ ਹੈਗਾ ਹੈ?", landingTitle: "ਵਿਅਕਤੀਗਤ AI ਰਾਹੀਂ ਸਾਖਰਤਾ ਦਾ ਸਸ਼ਕਤੀਕਰਨ",
    landingTitleLine1: "ਸਾਖਰਤਾ ਦਾ ਸਸ਼ਕਤੀਕਰਨ", landingTitleLine2: "AI ਬੁੱਧੀ ਰਾਹੀਂ",
    landingSub: "ਇੱਕ ਅਨੁਕੂਲ ਸਿੱਖਣ ਪਲੇਟਫਾਰਮ ਜੋ ਬਾਲਗਾਂ ਅਤੇ ਪਹਿਲੀ ਪੀੜ੍ਹੀ ਦੇ ਸਿੱਖਣ ਵਾਲਿਆਂ ਨੂੰ ਉਹਨਾਂ ਦੀਆਂ ਖੇਤਰੀ ਮਾਤ੍ਰਭਾਸ਼ਾਵਾਂ ਦੀ ਵਰਤੋਂ ਕਰਕੇ ਮੁਢਲੀ ਪੜ੍ਹਨ, ਲਿਖਣ ਅਤੇ ਬੋਲਣ ਦਾ ਵਿਸ਼ਵਾਸ ਹਾਸਲ ਕਰਨ ਵਿੱਚ ਮਦਦ ਕਰਦਾ ਹੈ।",
    getStarted: "ਸ਼ੁਰూ ਕਰੋ", registerTitle: "ਆਪਣੀ ਪ੍ਰੋਫਾਈਲ ਬਣਾਓ", registerSub: "ਸਾਡੇ ਭਾਈਚਾਰੇ ਵਿੱਚ ਸਭਲ ਹੋਵੋ ਅਤੇ ਆਪਣੇ ਸਿੱਖਣ ਦੇ ਦਾਇਰੇ ਦਾ ਵਿਸਤਾਰ ਕਰੋ।",
    languageLabel: "🌐 ਪਸੰਦੀਦਾ ਮਾਤਭਾਸ਼ਾ", registerLeftTitle: "ਤੁਹਾਡੀ ਸਾਖਰਤਾ ਦੀ ਯਾਤਰਾ ਇੱਥੋਂ ਸੁਰੂ ਹੁੰਦੀ ਹੈ।",
    registerLeftSub: "ਆਵਾਜ਼ ਅਭਿਆਸ ਮੁਲਾਂਕਣ, ਰੀਅਲ-ਟਾਈਮ ਫੀਡਬੈਕ, ਅਤੇ ਰੋਜ਼ਾਨਾ ਪੜ੍ਹਨ ਦੇ ਪਾਠਾਂ ਨੂੰ ਅਨਲੌਕ ਕਰਨ ਲਈ ਇੱਕ ਪ੍ਰੋਫਾਈਲ ਬਣਾਓ।",
    loginLeftTitle: "ਤੁਹਾਡਾ ਸਿੱਖਿਆ ਹਰ ਸ਼ਬਦ ਇੱਕ ਨਵਾਂ ਦਰਵਾਜ਼ਾ ਖੋਲ੍ਹਦਾ ਹੈ।", loginLeftSub: "ਨਿੱਜੀ ਪੜ੍ਹਨ, ਲਿਖਣ ਅਤੇ ਬੋਲਣ ਦਾ ਅਭਿਆਸ — ਤੁਹਾਡੀ ਆਪਣੀ ਭਾਸ਼ਾ ਵਿੱਚ, ਤੁਹਾਡੀ ਆਪਣੀ ਰਫ਼ਤਾਰ ਨਾਲ।",
    dashboardTitle: "ਤੁਹਾਡੇ ਡੈਸ਼ਬੋਰਡ ਵਿੱਚ ਜੀ ਆਇਆਂ ਨੂੰ!", logout: "ਲੌਗ ਆਊਟ"
  },
  bengali: {
    home: "হোম", signIn: "সাইন ইন", createAccount: "অ্যাকাউন্ট তৈরি করুন", welcomeBack: "স্বাগতম",
    signInSub: "আপনার শেখার যাত্রা চালিয়ে যেতে সাইন ইন করুন।", email: "✉️ ইমেল ঠিকানা", password: "🔒 পাসওয়ার্ড", fullName: "👤 পুরো নাম", or: "অথবা",
    googleSignIn: "গুগল এর সাথে এগিয়ে যান", newHere: "এখানে নতুন?", alreadyHaveAccount: "ইতিমধ্যে অ্যাকাউন্ট আছে?", landingTitle: "এআই এর মাধ্যমে সাক্ষরতার ক্ষমতায়ন",
    landingTitleLine1: "সাক্ষরতার ক্ষমতায়ন", landingTitleLine2: "AI বুদ্ধিমত্তার মাধ্যমে",
    landingSub: "একটি ব্যক্তিগতকৃত শেখার সঙ্গী যা প্রাপ্তবয়স্ক এবং প্রথম প্রজন্মের শিক্ষার্থীদের আঞ্চলিক ভাষায় মৌলিক পড়া, লেখা এবং বলার দক্ষতা অর্জন করতে সহায়তা করার জন্য ডিজাইন করা হয়েছে।",
    getStarted: "শুরু করুন", registerTitle: "আপনার অ্যাকাউন্ট তৈরি করুন", registerSub: "আমাদের সম্প্রদায়ে যোগ দিন এবং আপনার শেখার দিগন্ত প্রসারিত করুন।",
    languageLabel: "🌐 পছন্দের মাতৃভাষা", registerLeftTitle: "আপনার সাক্ষরতার যাত্রা এখানেই শুরু।",
    registerLeftSub: "ভয়েস প্র্যাকটিস অ্যাসেসমেন্ট, রিয়েল-টাইম ফিডব্যাক এবং অভিযোজিত দৈনিক পাঠ আনলক করতে একটি প্রোফাইল তৈরি করুন।",
    loginLeftTitle: "আপনার শেখা প্রতিটি শব্দ একটি নতুন দরজা খুলে দেয়।", loginLeftSub: "ব্যক্তিগতকৃত পড়া, লেখা এবং বলার অনুশীলন — আপনার নিজস্ব ভাষায়, আপনার নিজস্ব গতিতে।",
    dashboardTitle: "আপনার ড্যাশবোর্ডে স্বাগতম!", logout: "লগ আউট"
  },
  marathi: {
    home: "होम", signIn: "साइन इन", createAccount: "खाते तयार करा", welcomeBack: "स्वागत आहे",
    signInSub: "तुमचा शिकण्याचा प्रवास सुरू ठेवण्यासाठी साइन इन करा.", email: "✉️ ईमेल पत्ता", password: "🔒 पासवर्ड", fullName: "👤 पूर्ण नाव", or: "किंवा",
    googleSignIn: "गुगलसह पुढे जा", newHere: "नवीन आहात?", alreadyHaveAccount: "आधीच खाते आहे का?", landingTitle: "एआई द्वारे साक्षरतेचे सक्षमीकरण",
    landingTitleLine1: "साक्षरता सक्षमीकरण", landingTitleLine2: "एआई बुद्धिमत्तेद्वारे",
    landingSub: "एक वैयक्तिकृत शिक्षण सोबती जो प्रौढ आणि पहिल्या पिढीतील शिकणाऱ्यांना प्रादेशिक भाषांमध्ये मूलभूत वाचन, लेखन आणि बोलण्याचे कौशल्य आत्मसात करण्यास मदत करण्यासाठी डिझाइन केलेले है.",
    getStarted: "सुरू करा", registerTitle: "तुमचे खाते तयार करा", registerSub: "आमच्या समुदायात सामील व्हा आणि तुमच्या शिकण्याच्या कक्षा रुंदावा.",
    languageLabel: "🌐 पसंतीची मातृभाषा", registerLeftTitle: "तुमचा साक्षरतेचा प्रवास इथून सुरू होतो.",
    registerLeftSub: "व्हॉइस प्रॅक्टिस असेसमेंट, रिअल-टाइम फीडबॅक आणि अडॅप्टिव्ह डेली रीडिंग धडे अनलॉक करण्यासाठी एक प्रोफाईल तयार करा.",
    loginLeftTitle: "तुम्ही शिकलेला प्रत्येक शब्द एक नवीन दार उघडतो.", loginLeftSub: "वैयक्तिकृत वाचन, लेखन आणि बोलण्याचा सराव — तुमच्या स्वतःच्या भाषेत, तुमच्या स्वतःच्या गतीने.",
    dashboardTitle: "तुमच्या डॅशबोर्डवर स्वागत आहे!", logout: "लॉग आउट"
  },
  tamil: {
    home: "முகப்பு", signIn: "உள்நுழை", createAccount: "கணக்கை உருவாக்கு", welcomeBack: "நல்வரவு",
    signInSub: "உங்கள் கற்றல் பயணத்தைத் தொடர உள்நுழையவும்.", email: "✉️ மின்னஞ்சல் முகவரி", password: "🔒 கடவுச்சொல்", fullName: "👤 முழு பெயர்", or: "அல்லது",
    googleSignIn: "கூகிள் மூலம் தொடரவும்", newHere: "புதியவரா?", alreadyHaveAccount: "ஏற்கனவே கணக்கு உள்ளதா?", landingTitle: "AI மூலம் எழுத்தறிவு மேம்பாடு",
    landingTitleLine1: "எழுத்தறிவு மேம்பாடு", landingTitleLine2: "AI நுண்ணறிவின் மூலம்",
    landingSub: "பெரியவர்கள் மற்றும் প্রথম தலைமுறை கற்பவர்கள் பிராந்திய மொழிகளில் அடிப்படை வாசிப்பு, எழுதுதல் மற்றும் பேசும் திறன்களைப் பெற உதவும் வகையில் வடிவமைக்கப்பட்ட தனிப்பயனாக்கப்பட்ட கற்றல் துணை.",
    getStarted: "தொடங்குங்கள்", registerTitle: "உங்கள் கணக்கை உருவாக்கவும்", registerSub: "எங்கள் சமூகத்தில் இணைந்து உங்கள் கற்றல் எல்லையை விரிவுபடுத்துங்கள்.",
    languageLabel: "🌐 விருப்பமான தாய்மொழி", registerLeftTitle: "உங்கள் எழுத்தறிவு பயணம் இங்கே தொடங்குகிறது.",
    registerLeftSub: "குரல் பயிற்சி மதிப்பீடுகள், நிகழ்நேர கருத்து மற்றும் தினசரி வாసిப்பு பாடங்களை அணுக ஒரு சுயவிவரத்தை உருவாக்கவும்.",
    loginLeftTitle: "நீங்கள் கற்கும் ஒவ்வொரு வார்த்தையும் ஒரு புதிய கதவைத் திறக்கிறது.", loginLeftSub: "தனிப்பயனாக்கப்பட்ட வாசிப்பு, எழுதுதல் மற்றும் பேசும் பயிற்சி — உங்கள் சொந்த மொழியில், உங்கள் சொந்த வேகத்தில்.",
    dashboardTitle: "உங்கள் டாஷ்போர்டிற்கு வரவேற்கிறோம்!", logout: "வெளியேறு"
  },
  gujarati: {
    home: "હોમ", signIn: "સાઇન ઇન", createAccount: "ખાતું બનાવો", welcomeBack: "સ્વાગત છે",
    signInSub: "તમારી શીખવાની યાત્રા ચાલુ રાખવા માટે साઇન ઇન કરો.", email: "✉️ ઇમેઇલ સરનામું", password: "🔒 પાસવર્ડ", fullName: "👤 પૂરું નામ", or: "અથวา",
    googleSignIn: "ગુગલ સાથે ચાલુ રાખો", newHere: "અહીં નવા છો?", alreadyHaveAccount: "પહેલેથી ખાતું છે?", landingTitle: "AI દ્વારા સાક્ષરતા સશક્તિકરણ",
    landingTitleLine1: "સાક્ષરતા સશક્તિકરણ", landingTitleLine2: "AI બુદ્ધિ દ્વારા",
    landingSub: "એક વ્યક્તિગત શિક્ષણ સાથી જે પુખ્ત वયના લોકો અને પ્રથમ પેઢીના શીખનારાઓને પ્રાદેશિક ભાષાઓમાં પાયાના વાંચન, લેખન અને બોલવાના કૌશલ્યો પ્રાપ્ત કરવામાં મદદ કરવા માટે રચાયેલ છે.",
    getStarted: "શરૂ કરો", registerTitle: "તમારું ખાતું બનાવો", registerSub: "અમારા સમુદાયમાં જોડાઓ અને તમારી શીખવાની ક્ષિતિજોનો વિસ્તાર કરો.",
    languageLabel: "🌐 પસંદગીની માતૃભાષા", registerLeftTitle: "તમારી સાક્ષરતાની સફર અહીંથી શરૂ થાય છે.",
    registerLeftSub: "વોઇસ પ્રેક્ટિસ એસેસમેન્ટ્સ, રીઅલ-ટાઇમ ફીડબેક અને દૈનિક વાંચન પાઠોને અનલૉક કરવા માટે એક પ્રોફાઇલ બનાવો.",
    loginLeftTitle: "તમે શીખો છો તે દરેક શબ્દ એક નવો દરવાજો ખોલે છે.", loginLeftSub: "ব্যক্তিগত વાંચન, લેખન અને બોલવાની પ્રેક્ટિસ — તમારી પોતાની ભાષામાં, તમારી પોતાની ગતિએ.",
    dashboardTitle: "તમારા ડેશબોર્ડમાં સ્વાગત છે!", logout: "લોગ આઉट"
  },
  kannada: {
    home: "ಹೋಮ್", signIn: "ಸೈನ್ ಇನ್", createAccount: "ಖಾತೆ ರಚಿಸಿ", welcomeBack: "ಸ್ವಾಗತ",
    signInSub: "ನಿಮ್ಮ ಕಲಿಕೆಯ ಪ್ರಯಾಣವನ್ನು ಮುಂದುವರಿಸಲು ಸೈನ್ ಇನ್ ಮಾಡಿ.", email: "✉️ ಇಮೇಲ್ ವಿಳಾಸ", password: "🔒 ಪಾಸ್‌ವರ್ಡ್", fullName: "👤 ಪೂರ್ಣ ಹೆಸರು", or: "ಅಥವಾ",
    googleSignIn: "ಗೂಗಲ್‌ನೊಂದಿಗೆ ಮುಂದುವರಿಯಿರಿ", newHere: "ಇಲ್ಲಿ ಹೊಸಬರೇ?", alreadyHaveAccount: "ಈಗಾಗಲೇ ಖಾತೆ ಹೊಂದಿದ್ದೀರಾ?", landingTitle: "AI ಮೂಲಕ ಸಾಕ್ಷರತೆಯ ಸಬಲೀಕರಣ",
    landingTitleLine1: "ಸಾಕ್ಷರತೆಯ ಸಬಲೀಕರಣ", landingTitleLine2: "AI ಬುದ್ಧಿಮತ್ತೆ ಮೂಲಕ",
    landingSub: "ವಯಸ್ಕರು ಮತ್ತು ಮೊದಲ ತಲೆಮಾರಿನ ಕಲಿಯುವವರಿಗೆ ಪ್ರಾದೇಶಿಕ ಭಾಷೆಗಳಲ್ಲಿ ಮೂಲಭೂತ ಓದುವಿಕೆ, ಬರವಣಿಗೆ ಮತ್ತು ಮಾತನಾಡುವ ಕೌಶಲ್ಯಗಳನ್ನು ಪಡೆಯಲು ಸಹಾಯ ಮಾಡಲು ವಿನ್ಯಾಸಗೊಳಿಸಲಾದ ವೈಯಕ್ಕೀಕರಿಸಿದ ಕಲಿಕೆಯ ಒಡನಾಡಿ.",
    getStarted: "ಪ್ರಾರಂಭಿಸಿ", registerTitle: "ನಿಮ್ಮ ಖಾತೆಯನ್ನು ರಚಿಸಿ", registerSub: "ನಮ್ಮ ಸಮುದಾಯಕ್ಕೆ ಸೇರಿ ಮತ್ತು ನಿಮ್ಮ ಕಲಿಕೆಯ ಪರಿಧಿಯನ್ನು ವಿಸ್ತರಿಸಿ.",
    languageLabel: "🌐 ಆದ್ಯತೆಯ ಮಾತೃಭಾಷೆ", registerLeftTitle: "ನಿಮ್ಮ ಸಾಕ್ಷರತೆಯ ಪ್ರಯಾಣ ಇಲ್ಲಿಂದ ಪ್ರಾರಂಭವಾಗುತ್ತದೆ.",
    registerLeftSub: "ಧ್ವನಿ ಅಭ್ಯಾಸ ಮೌಲ್ಯಮಾಪನಗಳು, ನೈಜ-ಸಮಯದ ಪ್ರತಿಕ್ರಿಯೆ ಮತ್ತು ದೈನಂದิน ಓದುವ ಪಾಠಗಳನ್ನು ಅನ್ಲಾಕ್ ಮಾಡಲು ಪ್ರೊಫೈಲ್ ರಚಿಸಿ.",
    loginLeftTitle: "ನೀವು ಕಲಿಯುವ ಪ್ರತಿಯೊಂದು ಪದವೂ ಹೊಸ ಬಾಗಿಲನ್ನು ತೆರೆಯುತ್ತದೆ.", loginLeftSub: "ವೈಯಕ್ಕೀಕರಿಸಿದ ಓದುವಿಕೆ, ಬರವಣಿಗೆ ಮತ್ತು ಮಾತನಾಡುವ ಅಭ್ಯಾಸ — ನಿಮ್ಮದೇ ಭಾಷೆಯಲ್ಲಿ, ನಿಮ್ಮದೇ ವೇಗದಲ್ಲಿ.",
    dashboardTitle: "ನಿಮ್ಮ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್‌ಗೆ ಸ್ವಾಗತ!", logout: "ಲಾಗ್ ಔಟ್"
  },
  malayalam: {
    home: "ഹോം", signIn: "സൈൻ ഇൻ", createAccount: "അക്കൗണ്ട് സൃഷ്ടിക്കുക", welcomeBack: "സ്വാഗതം",
    signInSub: "നിങ്ങളുടെ പഠന യാത്ര തുടരാൻ സൈൻ ഇൻ ചെയ്യുക.", email: "✉️ ഇമെയിൽ വിലാസം", password: "🔒 പാസ്‌വേഡ്", fullName: "👤 പൂർണ്ണ നാമം", or: "അല്ലെങ്കിൽ",
    googleSignIn: "ഗൂഗിൾ ഉപയോഗിച്ച് തുടരുക", newHere: "പുതിയതാണോ?", alreadyHaveAccount: "നിലവിൽ അക്കൗണ്ട് ഉണ്ടോ?", landingTitle: "AI വഴിയുള്ള സാക്ഷരതാ ശാക്തീകരണം",
    landingTitleLine1: "സാക്ഷരതാ ശാക്തീകരണം", landingTitleLine2: "AI ബുദ്ധി വഴി",
    landingSub: "മുതിർന്നവർക്കും ആദ്യതലമുറ പഠിതാക്കൾക്കും പ്രാദേശിക ഭാഷകളിൽ അടിസ്ഥാന വായന, എഴുത്ത്, സംസാര കഴിവുകൾ എന്നിവ നേടിയെടുക്കാൻ സഹായിക്കുന്നതിനായി രൂപകൽപ്പന ചെയ്ത ഒരു വ്യക്തിഗത പഠന സഹായി.",
    getStarted: "ആരംഭിക്കുക", registerTitle: "ನಿങ്ങളുടെ അക്കൗണ്ട് സൃഷ്ടിക്കുക", registerSub: "ഞങ്ങളുടെ കമ്മ്യൂਣੀറ്റിയിൽ ചേരുക, നിങ്ങളുടെ പഠന ਚਕਰവാളങ്ങൾ വികസിപ്പിക്കുക.",
    languageLabel: "🌐 താൽപ്പര്യമുള്ള മാതൃഭാഷ", registerLeftTitle: "批准 സാക്ഷരതാ യാത്ര ഇവിടെ ആരംഭിക്കുന്നു.",
    registerLeftSub: "വോയ്‌സ് പ്രാക്ടീസ് അസസ്‌മെന്റുകൾ, തത്സമയ ഫീഡ്‌ബാക്ക്, വ്യക്തിഗതമാക്കിയ വായനാ പാഠങ്ങൾ എന്നിവ അൺലോക്ക് ചെയ്യാൻ ഒരു പ്രൊഫൈൽ സൃഷ്‌ടിക്കുക.",
    loginLeftTitle: "നിങ്ങൾ പഠിക്കുന്ന ഓരോ വാക്കും ഒരു പുതിയ വാതിൽ തുറക്കുന്നു.", loginLeftSub: "വ്യക്തിഗതമാക്കിയ വായന, എഴുത്ത്, സംസാര പരിശീലനം — നിങ്ങളുടെ സ്വന്തം ഭാഷയിൽ, നിങ്ങളുടെ സ്വന്തം വേഗതയിൽ.",
    dashboardTitle: "നിങ്ങളുടെ ഡാഷ്‌ബോർഡിലേക്ക് സ്വാഗതം!", logout: "ലോഗ് ഔട്ട്"
  },
  odia: {
    home: "ହୋମ୍", signIn: "ସାଇନ୍ ଇନ୍", createAccount: "ଆକାଉଣ୍ଟ୍ ତିଆରି କରନ୍ତୁ", welcomeBack: "ସ୍ୱାଗତ",
    signInSub: "ଆପଣଙ୍କର ଶିକ୍ଷା ଯାତ୍ରା ଜାରି ରଖିବା ପାଇଁ ସାଇନ୍ ଇନ୍ କରନ୍ତୁ ।", email: "✉️ ଇମେଲ୍ ଠିକଣା", password: "🔒 ପାସୱାର୍ଡ", fullName: "👤 ପୁରା ନାମ", or: "କିମ୍ବା",
    googleSignIn: "ଗୁଗଲ୍ ସହିତ ଆଗକୁ ବଢନ୍ତୁ", newHere: "ଏଠାରେ ନୂଆ କି?", alreadyHaveAccount: "ପୂର୍ବରୁ ଆକାଉଣ୍ଟ୍ ଅଛି କି?", landingTitle: "AI ମାଧ୍ୟମରେ ସାକ୍ଷରତା ସଶକ୍ତିକରଣ",
    landingTitleLine1: "ସାକ୍ଷରତା ସଶକ୍ତିକରଣ", landingTitleLine2: "AI ଜ୍ଞାନ ଦ୍ୱାରା",
    landingSub: "ଏକ ବ୍ୟକ୍ତିଗତ ଶିକ୍ଷଣ ସାଥୀ ଯାହା ବୟସ୍କ ଏବଂ ପ୍ରଥମ ପିଢ଼ିର ଶିକ୍ଷାର୍ଥୀମାନଙ୍କୁ ଆଞ୍ଚଳିକ ଭାଷାରେ ମୌଳିକ ପଢିବା, ଲେଖିବା ଏବଂ କହିବା ଦକ୍ଷତା ହାସଲ କରିବାରେ ସାହାଯ୍ୟ କରିବା ପାଇଁ ପ୍ରସ୍ତୁତ କରାଯାଇଛି ।",
    getStarted: "ଆରମ୍ଭ କରନ୍ତୁ", registerTitle: "ଆପଣଙ୍କ ଆକାଉଣ୍ଟ୍ ତିଆରି କରନ୍ତୁ", registerSub: "ଆମ ସମୁଦାୟରେ ଯୋଗ ଦିଅନ୍ତୁ ଏବଂ ଶିକ୍ଷାର ପରିସରକୁ ବୃଦ୍ଧି କରନ୍ତୁ ।",
    languageLabel: "🌐 ପସନ୍ଦର ମାତୃଭାଷା", registerLeftTitle: "ଆପଣଙ୍କର ସାକ୍ଷରତା ଯାତ୍ରା ଏଠାରୁ ଆରମ୍ଭ ହୁଏ ।",
    registerLeftSub: "ଭଏସ୍ ପ୍ରାକ୍ଟିସ୍ ଆସେସମେଣ୍ଟ୍ ଏବଂ ଦୈନିକ ପଠନ ପାଠ୍ୟକ୍ରମକୁ ଅନଲକ୍ କରିବା ପାଇଁ ଏକ ପ୍ରୋଫାଇଲ୍ ତିଆରି କରନ୍ତୁ ।",
    loginLeftTitle: "ଆପଣ ଶିଖୁଥିବା ପ୍ରତ୍ୟେକ ଶବ୍ଦ ଏକ ନୂତନ ଦ୍ୱାର ଖୋଲିଥାଏ ।", loginLeftSub: "ବ୍ୟକ୍ତିଗତ ପଢିବା, ଲେଖିବା ଏବଂ କହିବା ଅଭ୍ୟାସ — ଆପଣଙ୍କ ନିଜ ଭାଷାରେ, ଆପଣଙ୍କ ନିଜ ଗତିରେ ।",
    dashboardTitle: "ଆପଣଙ୍କ ଡ୍ୟାଶବୋର୍ଡକୁ ସ୍ୱାଗତ!", logout: "ଲଗ୍ ଆଉଟ୍"
  },
  urdu: {
    home: "ہوم", signIn: "سائن ان", createAccount: "اکاؤنٹ بنائیں", welcomeBack: "خوش آمدید",
    signInSub: "اپنا سیکھنے کا سفر جاری رکھنے کے لیے سائن ان کریں۔", email: "✉️ ای میل ایڈریس", password: "🔒 پاس ورڈ", fullName: "👤 پورا نام", or: "یا",
    googleSignIn: "گوگل کے ساتھ جاری رکھیں", newHere: "یہاں نئے ہیں؟", alreadyHaveAccount: "پہلے سے اکاؤنٹ ہے؟", landingTitle: "AI کے ذریعے خواندگی کا فروغ",
    landingTitleLine1: "خواندگی کا فروغ", landingTitleLine2: "AI ذہانت کے ذریعے",
    landingSub: "ایک ذاتی نوعیت کا تعلیمی ساتھی جو بالغوں اور پہلی نسل کے سیکھنے والوں کو علاقائی زبانوں میں بنیادی پڑھنے, لکھنے اور بولنے کی مہارت حاصل کرنے میں مدد کرتا ہے۔",
    getStarted: "شروع کریں", registerTitle: "اپنا اکاؤنٹ بنائیں", registerSub: "ہماری کمیونٹی میں شامل ہوں اور اپنے سیکھنے کے افق کو وسعت دیں۔",
    languageLabel: "🌐 پسندیدہ مادری زبان", registerLeftTitle: "آپ کا پڑھنے کا سفر یہاں سے شروع ہوتا ہے۔",
    registerLeftSub: "صوتی مشق کے جائزے، حقیقی وقت کے تاثرات، اور روزانہ پڑھنے کے اسباق کو غیر مقفل کرنے کے لیے پروفائل بنائیں۔",
    loginLeftTitle: "ہر وہ لفظ جو آپ سیکھتے ہیں ایک نیا دروازہ کھولتا ہے۔", loginLeftSub: "ذاتی نوعیت کا پڑھنا، لکھنا اور بولنا — آپ کی اپنی زبان میں, آپ کی اپنی رفتار سے۔",
    dashboardTitle: "آپ کے ڈیش بورڈ میں خوش آمدید!", logout: "لاگ آؤٹ"
  },
  assamese: {
    home: "হোম", signIn: "সাইন ইন", createAccount: "একাউণ্ট খোলক", welcomeBack: "স্বাগতম",
    signInSub: "আপোনাৰ শিকন যাত্ৰা অব্যাহত ৰাখিবলৈ ছাইন ইন কৰক।", email: "✉️ ইমেইল ঠিকনা", password: "🔒 পাছৱৰ্ড", fullName: "👤 সম্পূৰ্ণ নাম", or: "অথবা",
    googleSignIn: "গুগলৰ সৈতে আগবাঢ়ক", newHere: "ইয়াত নতুন নেকি?", alreadyHaveAccount: "ইতিমধ্যে একাউণ্ট আছে নেকি?", landingTitle: "AI ৰ জৰিয়তে সাক্ষৰতা সবলীকৰণ",
    landingTitleLine1: "সাক্ষৰতা সবলীকৰণ", landingTitleLine2: "AI বুদ্ধিৰ জৰিয়তে",
    landingSub: "এটা ব্যক্তিগতকৃত শিক্ষণ সহযোগী যি প্ৰাপ্তবয়স্ক আৰু প্ৰথম প্ৰজন্মৰ শিক্ষাৰ্থীক আঞ্চলিক ভাষাত মৌলিক পঢ়া, লিখা আৰু কোৱাৰ দক্ষতা অৰ্জন কৰাত সহায় কৰিবলৈ ডিজাইন কৰা হৈছে।",
    getStarted: "আৰম্ভ কৰক", registerTitle: "আপোনাৰ এককাউণ্ট খোলক", registerSub: "আমাৰ সমাজত যোগদান কৰক আৰু আপোনাৰ শিক্ষাৰ পৰিসৰ বৃদ্ধি কৰক।",
    languageLabel: "🌐 পছন্দৰ মাতৃভাষা", registerLeftTitle: "আপোনাৰ সাক্ষৰতাৰ যাত্ৰা ইয়াতেই আৰম্ভ হৈছে।",
    registerLeftSub: "ভয়েচ প্ৰেকটিচ এছেছমেণ্ট, ৰিয়েল-টাইম ফীডবেক আৰু দৈনিক পঢ়াৰ পাঠ আনলক কৰিবলৈ এটা প্ৰফাইল সৃষ্টি কৰক।",
    loginLeftTitle: "আপুনি শিকা প্ৰতিটো শব্দই এটা নতুন দুৱাৰ খোলে।", loginLeftSub: "ব্যক্তিগতকৃত পঢ়া, লিখা আৰু কোৱাৰ অভ্যাস — আপোনাৰ নিজৰ ভাষাত, আপোনাৰ নিজৰ গতিৰে।",
    dashboardTitle: "আপোনাৰ ডেশ্ববৰ্ডলৈ স্বাগতম!", logout: "লগ আউট"
  },
  maithili: {
    home: "होम", signIn: "साइन इन", createAccount: "खाता बनाउ", welcomeBack: "स्वागत अछि",
    signInSub: "अपन सीखबाक यात्रा जारी रखबाक लेल साइन इन करू।", email: "✉️ ईमेल पता", password: "🔒 पासवर्ड", fullName: "👤 पूरा नाम", or: "वा",
    googleSignIn: "गूगलक संग जारी राखू", newHere: "एतय नव छी?", alreadyHaveAccount: "पहले सं खाता अछि?", landingTitle: "AI क माध्यम सं साक्षरताक सशक्तिकरण",
    landingTitleLine1: "साक्षरताक सशक्तिकरण", landingTitleLine2: "AI बुद्धिमत्ता द्वारा",
    landingSub: "एकटा व्यक्तिगत शिक्षण साथी जे वयस्क आ पहিল पीढ़िक सीखनिहार लोकनिकेँ क्षेत्रीय भाषामे बुनियादी पढ़ब, लिखब आ बाजबाक कौशल हासिल करबामे मद्दति करबाक लेल बनाओल गेल अछि।",
    getStarted: "शुरू करू", registerTitle: "अपन खाता बनाउ", registerSub: "हमर समुदायमे शामिल होऊ आ अपन सीखबाक दायरा बढाउ।",
    languageLabel: "🌐 पसंदीदा मातृभाषा", registerLeftTitle: "अहाँक साक्षरताक यात्रा एतय सं शुरू होइत अछि।",
    registerLeftSub: "आवाज अभ्यास मूल्यांकन आ दैनिक पढ़बाक पाठकेँ अनलॉक करबाक लेल एकटा प्रोफाइल बनाउ।",
    loginLeftTitle: "अहाँक द्वारा सीखल गेल हर शब्द एकटा नव कपाट खोलैत अछि।", loginLeftSub: "व्यक्तिगत पढ़ब, लिखब आ बाजबाक अभ्यास — अहाँक अपन भाषामे, अपन गति सं।",
    dashboardTitle: "अहाँक डैशबोर्डमे स्वागत अछि!", logout: "लॉग आउट"
  },
  santhali: {
    home: "ᱦᱳᱢ", signIn: "ᱥᱟᱭᱤᱱ ᱤᱱ", createAccount: "ᱠᱷᱟᱛᱟ ᱵᱮᱱᱟᱣ", welcomeBack: "ᱥᱟᱹᱜᱩᱱ ᱫTransition",
    signInSub: "ᱟᱢᱟᱜ ᱪᱮᱫᱚᱜ ᱦᱚᱨา ᱞᱟᱦᱟ ᱤᱫᱤ ᱞᱟᱹᱜᱤᱫ ᱥᱟᱭᱤᱱ ᱤᱱ ᱢᱮ ᱾", email: "✉️ ਈਮੇਲ ᱴᱷᱮᱠਾᱬָᱟ", password: "🔒 ᱯᱟᱥᱣᱟᱨᱰ", fullName: "👤 ᱯᱩᱨᱟᱹ ᱧᱩᱛᱩᱢ", or: "ᱪᱮ",
    googleSignIn: "ᱜᱩᱜᱚᱞ ᱥᱟᱶ ᱞᱟᱦᱟᱜ ᱢᱮ", newHere: "ᱱᱚᱸᱰᱮ ᱱᱟᱣা ᱜᱮᱭᱟᱢ?", alreadyHaveAccount: "ᱞᱟᱦᱟ ᱠᱷᱚᱱ ᱠᱷᱟᱛᱟ ᱢᱮᱱᱟᱜ-ᱟ?", landingTitle: "AI ᱛᱮ ᱚᱞ ᱯᱟᱲᱦᱟᱣ",
    landingTitleLine1: "ᱚᱞ ᱯᱟᱲᱦᱟᱣ", landingTitleLine2: "AI ᱫᱚ ᱵᱩᱫᱷᱤ ᱛᱮ",
    landingSub: "ᱢᱤᱫ ᱟᱯնᱟᱨ ᱪᱮᱫᱚᱜ ᱜᱟᱛᱮ ᱡᱟᱦᱟᱸᱭ ᱫᱚ ᱦᱟᱨᱟ ᱵᱩᱨᱩ ᱟᱨ ᱯᱩᱭᱞᱩ ᱯᱤᱲᱦᱤ ᱪᱮᱫᱚᱜ ᱠᱚ ᱟᱠᱚᱣᱟᱜ ᱟᱭᳵ ᱟᱲᱟᱝ ᱛᱮ ᱚլ, ᱯᱟᱲᱦᱟᱣ ᱟᱨ ᱨᱚᱲ ᱪᱮᱫᱚᱜ ᱨᱮ ᱜᱚᱲᱚ ᱮᱢา ᱠᱚᱣᱟ ᱾",
    getStarted: "ᱮᱦᱚᱵ ᱢᱮ", registerTitle: "ᱟᱢาᱜ ᱠᱷᱟᱛᱟ ᱵᱮᱱᱟᱣ ᱢᱮ", registerSub: "ᱟᱞᱮ ᱥᱟᱶ ᱡᱩᱲᱟᱹᱣ ᱢᱮ ᱟᱨ ᱟᱢᱟᱜ ᱜᱮᱭᱟᱱ ᱯᱟᱥᱱᱟᱣ ᱢᱮ ᱾",
    languageLabel: "🌐 ᱠᱩᱥᱤᱭᱟᱜ ᱟᱭᳵ ᱟᱲᱟᱝ", registerLeftTitle: "Aᱢᱟᱜ ᱥᱮᱪᱮᱫ ᱦᱚᱨᱟ ᱱᱚᱸᳰᱮ ᱠᱷᱚᱱ ᱮᱦᱚᱵᱚᱜ-า ᱾",
    registerLeftSub: "Aᱲᱟᱝ ᱵᱤᰰᱟᱹᱣ ᱟᱨ དིᱱᱟᱹᱢ ᱯᱟᱲᱦᱟᱣ ᱞᱮᱥᱚᱱ ᱠᱚ ᱡᱷᱤᱡ ᱞᱟᱹᱜᱤᱫ ᱯᱨᱚᱯᱷᱟᱭᱤᱞ ᱵᱮᱱᱟᱣ ᱢᱮ ᱾",
    loginLeftTitle: "ᱪᱮᱫᱚᱜ ᱨᱮᱱᱟᱜ ᱢᱤᱫ ᱢᱤᱫ ᱥᱟᱵาᱫ ᱱᱟᱣᱟ དུ་ᱣᱟᱹր ᱡᱷᱤᱡ-ᱟ ᱾", loginLeftSub: "ᱟᱯᱱᱟᱨ ᱯᱟᱲᱦᱟᱣ, ᱚլ ᱟᱨ ᱨᱚᱲ ᱨᱮᱱᱟᱜ ᱵᱤᰰᱟᱹᱣ — ᱟᱢᱟᱜ ᱛᱮ, ᱟᱢᱟᱜ ᱛᱟᱹᱞ ᱛᱮ ᱾",
    dashboardTitle: "ᱟᱢᱟᱜ ᱰᱮᱥᱵᱳᱨᱰ ᱨᱮ ᱥᱟᱹᱜᱩᱱ ᱫTransition!", logout: "ᱳᱰᱳᱜ ᱢᱮ"
  },
  kashmiri: {
    home: "ہوم", signIn: "سائن ان", createAccount: "اکاؤنٹ بنایو", welcomeBack: "خوش آمدید",
    signInSub: "پنُن تعلیمی سفر جاری تھونہ خاطرہ کٔریو سائن ان۔", email: "✉️ ای میل پتہ", password: "🔒 پاس ورڈ", fullName: "👤 پۆرو ناؤ", or: "یا",
    googleSignIn: "گوگل پیتھ کٔریو جاری", newHere: "نۆو چُھا؟", alreadyHaveAccount: "برونہہ پؠٹھے چُھا اکاؤنٹ؟", landingTitle: "AI ذریہ تعلیمی بیداری",
    landingTitleLine1: "تعلیمی بیداری", landingTitleLine2: "AI ذہانت ذریہ",
    landingSub: "اکھ پنُن تعلیمی مددگار یُس وڈیرن تۂ گوڈنچہ نسلِ ہندین پرن والین ہنز مادری زبانن منز پراز پرنس، لیکھنس تۂ بولنس منز مدد کران چُھ۔",
    getStarted: "شروع کٔریو", registerTitle: "پنُن اکاؤنٹ بنایو", registerSub: "سٲنس برادری منز شمل کٔریو تۂ پنُن علم بڑھایو۔",
    languageLabel: "🌐 مادری زبان", registerLeftTitle: "تُہند پرنُک سفر چُھ یتنے شروع سپدان۔",
    registerLeftSub: "آواز ہند مشق تۂ پرنک سبق انلاک کرنہ خاطرہ کٔریو پروفائل تیار۔",
    loginLeftTitle: "ہر اکھ لفظ یُس تُہی پروو سو چُھ اکھ نیاو دروازہ کھولان۔", loginLeftSub: "پننہ زبانِ منز تۂ پننہ رفتارس پیتھ پرنُک تۂ بولنُک مشق۔",
    dashboardTitle: "تُہندس ڈیش بورڈس منز خوش آمدید!", logout: "لاگ آؤٹ"
  },
  nepali: {
    home: "होम", signIn: "साइन इन", createAccount: "खाता सिर्जना गर्नुहोस्", welcomeBack: "स्वागत छ",
    signInSub: "आफ्नो सिकाई यात्रा जारी राख्न साइन इन गर्नुहोस्।", email: "✉️ इमेल ठेगाना", password: "🔒 पासवर्ड", fullName: "👤 पूरा नाम", or: "वा",
    googleSignIn: "गुगलसँग जारी राख्नुहोस्", newHere: "यहाँ नयाँ हुनुहुन्छ?", alreadyHaveAccount: "पहिले नै खाता छ?", landingTitle: "AI मार्फत साक्षरता सशक्तिकरण",
    landingTitleLine1: "साक्षरता सशक्तिकरण", landingTitleLine2: "AI बुद्धिमत्ता मार्फत",
    landingSub: "एक व्यक्तिगत सिकाइ साथी जुन वयस्कहरू र पहिलो पुस्ताका शिक्षार्थीहरूलाई क्षेत्रीय भाषाहरूमा आधारभूत पढ्न, लेख्न र बोल्ने सीपहरू प्राप्त गर्न मद्दत गर्न डिजाइन गरिएको हो।",
    getStarted: "सुरु गर्नुहोस्", registerTitle: "आफ्नो खाता सिर्जना गर्नुहोस्", registerSub: "हाम्रो समुदायमा सामेल हुनुहोस् र आफ्नो सिकाई क्षितिज विस्तार गर्नुहोस्।",
    languageLabel: "🌐 रुचाइएको मातृभाषा", registerLeftTitle: "तपाईंको साक्षरता यात्रा यहाँबाट सुरु हुन्छ।",
    registerLeftSub: "आवाज अभ्यास मूल्याङ्कन र दैनिक पढ्ने पाठहरू अनलक गर्न प्रोफाइल सिर्जना गर्नुहोस्।",
    loginLeftTitle: "तपाईंले सिक्नुभएको हरेक शब्दले नयाँ ढोका खोल्छ।", loginLeftSub: "व्यक्तिगत पढ्ने, लेख्ने र बोल्ने अभ्यास — तपाईंको आफ्नै भाषामा, तपाईंको आफ्नै गतिमा।",
    dashboardTitle: "तपाईंको ड्यासबोर्डमा स्वागत छ!", logout: "लग आउट"
  },
  gondi: {
    home: "होम", signIn: "साइन इन", createAccount: "खाता कीम", welcomeBack: "सगताम",
    signInSub: "नीवा कलीना वेद्द्ता लोप्पे साइन इन कीम।", email: "✉️ ईमेल पता", password: "🔒 पासवर्ड", fullName: "👤 आक्खे पुदिर", or: "बाले",
    googleSignIn: "गूगल तोड़े सांगे मंत", newHere: "पुना मंत्या?", alreadyHaveAccount: "मुन्ने ने खाता मंता?", landingTitle: "AI ना वळते साक्षरता विकास",
    landingTitleLine1: "साक्षरता विकास", landingTitleLine2: "AI बुद्धि वळते",
    landingSub: "ऊंद मने कलीना तोड़े जश वयस्क और पहिल्या पीढ़ी ना कलीवाला न तोड़े भाषा ते वाचना, लीहना और वळना कली क कींत।",
    getStarted: "शुरू कीम", registerTitle: "नीवा खाता कीम", registerSub: "मावा गोट्टे ते कली और गियान वाधाय कीम।",
    languageLabel: "🌐 यालोळ नाटो भासा", registerLeftTitle: "नीवा साक्षरता कलीना इग्गने शुरू माता।",
    registerLeftSub: "वळना कलीना और रोज वाचना पाठ क तीरा कीले प्रोफाइल कीम।",
    loginLeftTitle: "जे शब्द कली कींत ओंद पुना कपाट तीरीत।", loginLeftSub: "नीवा भाषा ते नीवा नळ ते वाचना, लीहना और वळना क अभ्यास।",
    dashboardTitle: "नीवा डैशबोर्ड ते सगताम मंता!", logout: "बायदो"
  },
  sindhi: {
    home: "هوم", signIn: "سائن ان", createAccount: "खातो ٺاهيو", welcomeBack: "ڀلي ڪري آયા",
    signInSub: "پنهنجو سکڻ جو سفر جاري رکڻ لاءِ سائن ان ڪريو.", email: "✉️ اي ميل پتو", password: "🔒 پاسورڊ", fullName: "👤 پورو نالو", or: "يا",
    googleSignIn: "گوگل سان جاري رکو", newHere: "هتي نوان آهيو؟", alreadyHaveAccount: "پهرين کان خاتو آهي؟", landingTitle: "AI جي ذريعي تعليم جي سجاڳي",
    landingTitleLine1: "تعليم جي سجاڳي", landingTitleLine2: "AI ذهانت ذريعي",
    landingSub: "هڪ ذاتي سکيا جو ساٿي جيڪو وڏن ۽ پهرين نسل جي سکندڙن کي علائقائي ٻولين ۾ بنيادي پڙهڻ, لکڻ ۽ ڳالهائڻ جي صلاحيت حاصل ڪرڻ ۾ مدد ڪري ٿو.",
    getStarted: "شروع ڪريو", registerTitle: "پنهنجو खातो ٺاهيو", registerSub: "اسان جي برادري ۾ شامل ٿيو ۽ پنهنجي سکيا جو دائرو وڌايو.",
    languageLabel: "🌐 پسنديده مادري ٻولي", registerLeftTitle: "توهان جو سکڻ جو سفر هتان شروع ٿئي ٿو.",
    registerLeftSub: "آواز جي مشق ۽ روزاني پڙهڻ جا سبق کولڻ لاءِ هڪ پروفائل ٺاهيو.",
    loginLeftTitle: "توهان جيڪو به لفظ سکو ٿا اهو هڪ نئون دڙو کولي ٿو.", loginLeftSub: "پنهنجي ٻوليءَ ۾، پنهنجي رفتار سان پڙهڻ, لکڻ ۽ ڳالهائڻ جي مشق.",
    dashboardTitle: "توهان جي ڊيش بورڊ تي ڀلي ڪري آયા!", logout: "لاگ آئوٽ"
  },
  konkani: {
    home: "होम", signIn: "साइन इन", createAccount: "खातें तयार करात", welcomeBack: "येवकार",
    signInSub: "तुमची शिकपाची भोंवड जारी दवरपाक साइन इन करात.", email: "✉️ ईमेल पत्तो", password: "🔒 पासवर्ड", fullName: "👤 पूर्ण नांव", or: "वा",
    googleSignIn: "गूगल वांगडा फुडे वचात", newHere: "नवे आहात?", alreadyHaveAccount: "पयलींच खातें आसा?", landingTitle: "AI वरवीं साक्षरता उदरगत",
    landingTitleLine1: "साक्षरता उदरगत", landingTitleLine2: "AI बुद्धिमत्ता वरवीं",
    landingSub: "एक खाजगी शिकपाचो सांगाती जो जाणट्यांक आनी पयल्या पिळгеच्या शिकप्यांक थळाव्या भासांनी बुन्यादी वाचन, लेखन आनी उलोवपाचीं कौशल्यां मेळोવपाक मदत करता.",
    getStarted: "सुरू करात", registerTitle: "तुमचें खातें तयार करात", registerSub: "आमच्या पंगडांत आस्पावन तुमचें शिकপ वाडयात.",
    languageLabel: "🌐 pसंतीची आवयभास", registerLeftTitle: "तुमची साक्षरतेची भोंवड हांगासून सुरू जाता.",
    registerLeftSub: "आवाज सराव आनी दिसाळें वाचन धडे सुरू करपाक एक प्रोफाईल तयार करात.",
    loginLeftTitle: "तुम्ही शिकिल्लो दरेक शब्द एक नवें दार उघडटा.", loginLeftSub: "खंयच्याय अडखळा बगर तुमच्याच भाशेन आनी गतीन वाचन आनी उलोवपाचो सराव.",
    dashboardTitle: "तुमच्या डॅशबोर्डाचेर येवकार!", logout: "लॉग आउट"
  }
};

export const targetLanguages = [
  { value: 'english', native: 'English', label: 'English' },
  { value: 'hindi', native: 'हिन्दी', label: 'Hindi' },
  { value: 'telugu', native: 'తెలుగు', label: 'Telugu' },
  { value: 'punjabi', native: 'ਪੰਜਾਬੀ', label: 'Punjabi' },
  { value: 'bengali', native: 'বাংলা', label: 'Bengali' },
  { value: 'marathi', native: 'मराठी', label: 'Marathi' },
  { value: 'tamil', native: 'தமிழ்', label: 'Tamil' },
  { value: 'gujarati', native: 'ગુજરાતી', label: 'Gujarati' },
  { value: 'kannada', native: 'ಕನ್ನಡ', label: 'Kannada' },
  { value: 'malayalam', native: 'മലയാളം', label: 'Malayalam' },
  { value: 'odia', native: 'ଓଡ଼ିଆ', label: 'Odia' },
  { value: 'urdu', native: 'اُردُو', label: 'Urdu' },
  { value: 'assamese', native: 'অসমীয়া', label: 'Assamese' },
  { value: 'maithili', native: 'मैथिली', label: 'Maithili' },
  { value: 'santhali', native: 'ᱥᱟᱱᱛᱷᱟᱞᱤ', label: 'Santhali' },
  { value: 'kashmiri', native: 'کٲशুর', label: 'Kashmiri' },
  { value: 'nepali', native: 'नेपाली', label: 'Nepali' },
  { value: 'gondi', native: 'गोंडी', label: 'Gondi' },
  { value: 'sindhi', native: 'سنڌي', label: 'Sindhi' },
  { value: 'konkani', native: 'कोंकणी', label: 'Konkani' }
];